// AUTO-GENERATED by scripts/gen-const-files.ts — do not edit by hand

import { Pokemon, type PokemonConst } from "./pokemon";

/** All pokemon sorted by national dex number (game-exclusives last) */
export const POKEMON_LIST: PokemonConst[] = Object.values(Pokemon).sort(
  (a, b) => {
    const na = a.nationalDexNum ?? 99999;
    const nb = b.nationalDexNum ?? 99999;
    return na !== nb ? na - nb : a.num - b.num;
  },
);

/** Pokemon keyed by slug for O(1) lookup */
export const POKEMON_BY_SLUG: Record<string, PokemonConst> = Object.fromEntries(
  Object.values(Pokemon).map((p) => [p.slug, p]),
);

/** Pokemon grouped by specialty slug */
export const POKEMON_BY_SPECIALTY: Record<string, PokemonConst[]> = POKEMON_LIST.reduce<Record<string, PokemonConst[]>>(
  (acc, p) => { p.specialties.forEach((s) => (acc[s.slug] ??= []).push(p)); return acc; },
  {},
);

/** Pokemon grouped by habitat config slug */
export const POKEMON_BY_HABITAT_CONFIG: Record<string, PokemonConst[]> = POKEMON_LIST.reduce<Record<string, PokemonConst[]>>(
  (acc, p) => { p.habitatList.forEach((h) => (acc[h.habitat.slug] ??= []).push(p)); return acc; },
  {},
);

/** Zero-padded dex number for display */
export function dexNum(p: {
  nationalDexNum: number | null;
  num: number;
}): string {
  return String(p.nationalDexNum ?? p.num).padStart(3, "0");
}

/** Icon URL for a pokemon */
export function pkmnIconUrl(p: PokemonConst): string {
  return `/icons/pokemon/${p.icon}`;
}
