// AUTO-GENERATED by scripts/gen-const-files.ts — do not edit by hand

import { Pokemon, type PokemonConst } from "./pokemon";

/** All pokemon sorted by national dex number (game-exclusives last) */
export const POKEMON_LIST: PokemonConst[] = Object.values(Pokemon).sort(
  (a, b) => {
    const na = a.nationalDexNum ?? 99999;
    const nb = b.nationalDexNum ?? 99999;
    return na !== nb ? na - nb : a.num - b.num;
  },
);

/** Pokemon keyed by slug for O(1) lookup */
export const POKEMON_BY_SLUG: Record<string, PokemonConst> = Object.fromEntries(
  Object.values(Pokemon).map((p) => [p.slug, p]),
);

/** Pokemon grouped by specialty slug */
export const POKEMON_BY_SPECIALTY: Record<string, PokemonConst[]> = {};
for (const p of POKEMON_LIST) {
  for (const s of p.specialties) {
    (POKEMON_BY_SPECIALTY[s.slug] ??= []).push(p);
  }
}

/** Pokemon grouped by habitat config slug */
export const POKEMON_BY_HABITAT_CONFIG: Record<string, PokemonConst[]> = {};
for (const p of POKEMON_LIST) {
  for (const h of p.habitatList) {
    (POKEMON_BY_HABITAT_CONFIG[h.habitat.slug] ??= []).push(p);
  }
}

/** Zero-padded dex number for display */
export function dexNum(p: {
  nationalDexNum: number | null;
  num: number;
}): string {
  return String(p.nationalDexNum ?? p.num).padStart(3, "0");
}

/** Icon URL for a pokemon */
export function pkmnIconUrl(p: PokemonConst): string {
  return `/icons/pokemon/${p.icon}`;
}

const LEGENDARY_NUMS = new Set([
  144, 145, 146, 150, 151,
  243, 244, 245, 249, 250, 251,
  377, 378, 379, 380, 381, 382, 383, 384, 385, 386,
  480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
  494, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
  716, 717, 718, 719, 720, 721,
  772, 773, 785, 786, 787, 788, 789, 790, 791, 792, 800,
]);

export function getRarity(p: { nationalDexNum: number | null }) {
  const isLegendary = p.nationalDexNum != null && LEGENDARY_NUMS.has(p.nationalDexNum);
  return {
    holoIntensity: isLegendary ? 100 : 25,
    sparkles: isLegendary,
    rarityLabel: isLegendary ? "LEGENDARY" : "COMMON",
  };
}
