// AUTO-GENERATED by scripts/gen-const-files.ts — do not edit by hand

import { Pokemon, type PokemonConst } from "./pokemon";
import { type SpecialtyConst } from "./specialties";
import { type HabitatConfigConst } from "./habitat-config";
import { type CategoryConst } from "./categories";
import { type PokemonHabitatConst } from "./enum";

/** All pokemon sorted by national dex number (game-exclusives last) */
export const POKEMON_LIST: PokemonConst[] = Object.values(Pokemon)
  .sort((a, b) => {
    const na = a.nationalDexNum ?? 99999;
    const nb = b.nationalDexNum ?? 99999;
    return na !== nb ? na - nb : a.num - b.num;
  });

/** Pokemon keyed by slug for O(1) lookup */
export const POKEMON_BY_SLUG: Record<string, PokemonConst> = Object.fromEntries(
  Object.values(Pokemon).map((p) => [p.slug, p])
);

/** Pokemon grouped by specialty slug */
export const POKEMON_BY_SPECIALTY: Record<string, PokemonConst[]> = {};
for (const p of POKEMON_LIST) {
  for (const s of p.specialties) {
    (POKEMON_BY_SPECIALTY[s.slug] ??= []).push(p);
  }
}

/** Pokemon grouped by habitat config slug */
export const POKEMON_BY_HABITAT_CONFIG: Record<string, PokemonConst[]> = {};
for (const p of POKEMON_LIST) {
  for (const h of p.habitatList) {
    (POKEMON_BY_HABITAT_CONFIG[h.habitat.slug] ??= []).push(p);
  }
}

/** Zero-padded dex number for display */
export function dexNum(p: { nationalDexNum: number | null; num: number }): string {
  return String(p.nationalDexNum ?? p.num).padStart(3, "0");
}

/** Icon URL for a pokemon */
export function pkmnIconUrl(p: PokemonConst): string {
  return `/icons/pokemon/${p.icon}`;
}
