// AUTO-GENERATED by scripts/gen-const-files.ts — do not edit by hand

/** Weather conditions */
export const Weather = {
  Cloud: { slug: "cloud", label: "Cloud" },
  Rain: { slug: "rain", label: "Rain" },
  Sun: { slug: "sun", label: "Sun" },
} as const;
export type WeatherConst = (typeof Weather)[keyof typeof Weather];

/** Time of day */
export const Time = {
  Day: { slug: "day", label: "Day" },
  Evening: { slug: "evening", label: "Evening" },
  Morning: { slug: "morning", label: "Morning" },
  Night: { slug: "night", label: "Night" },
} as const;
export type TimeConst = (typeof Time)[keyof typeof Time];

/** Spawn rarity */
export const Rarity = {
  Common: { slug: "common", label: "Common" },
  Rare: { slug: "rare", label: "Rare" },
} as const;
export type RarityConst = (typeof Rarity)[keyof typeof Rarity];

/** Berry flavor preferences */
export const Flavor = {
  Bitter: { slug: "bitter", label: "Bitter" },
  Dry: { slug: "dry", label: "Dry" },
  Sour: { slug: "sour", label: "Sour" },
  Spicy: { slug: "spicy", label: "Spicy" },
  Sweet: { slug: "sweet", label: "Sweet" },
} as const;
export type FlavorConst = (typeof Flavor)[keyof typeof Flavor];

/** Pokemon types */
export const PokemonType = {
  Bug:      { slug: "bug",      label: "Bug"      },
  Dark:     { slug: "dark",     label: "Dark"     },
  Dragon:   { slug: "dragon",   label: "Dragon"   },
  Electric: { slug: "electric", label: "Electric" },
  Fairy:    { slug: "fairy",    label: "Fairy"    },
  Fighting: { slug: "fighting", label: "Fighting" },
  Fire:     { slug: "fire",     label: "Fire"     },
  Flying:   { slug: "flying",   label: "Flying"   },
  Ghost:    { slug: "ghost",    label: "Ghost"    },
  Grass:    { slug: "grass",    label: "Grass"    },
  Ground:   { slug: "ground",   label: "Ground"   },
  Ice:      { slug: "ice",      label: "Ice"      },
  Normal:   { slug: "normal",   label: "Normal"   },
  Poison:   { slug: "poison",   label: "Poison"   },
  Psychic:  { slug: "psychic",  label: "Psychic"  },
  Rock:     { slug: "rock",     label: "Rock"     },
  Steel:    { slug: "steel",    label: "Steel"    },
  Water:    { slug: "water",    label: "Water"    },
} as const;
export type PokemonTypeConst = (typeof PokemonType)[keyof typeof PokemonType];

/** Pokemon top-level habitat types */
export const PokemonHabitat = {
  Bright: { slug: "bright", label: "Bright" },
  Cool: { slug: "cool", label: "Cool" },
  Dark: { slug: "dark", label: "Dark" },
  Dry: { slug: "dry", label: "Dry" },
  Humid: { slug: "humid", label: "Humid" },
  Warm: { slug: "warm", label: "Warm" },
} as const;
export type PokemonHabitatConst =
  (typeof PokemonHabitat)[keyof typeof PokemonHabitat];
