import { Item, type ItemConst } from "./items";

/** Pokemon slug → the item it passively drops near its home (Litter specialty). */
export const PASSIVE_DROPS: Record<string, ItemConst> = {
  "venusaur":       Item.Leaf,
  "vileplume":      Item.Leaf,
  "jumpluff":       Item.Fluff,
  "bellsprout":     Item.VineRope,
  "weepinbell":     Item.VineRope,
  "tangela":        Item.VineRope,
  "tangrowth":      Item.VineRope,
  "snivy":          Item.VineRope,
  "servine":        Item.VineRope,
  "serperior":      Item.VineRope,
  "cacturne":       Item.SturdyStick,
  "combee":         Item.Honey,
  "haxorus":        Item.SmallLog,
  "grimer":         Item.NonburnableGarbage,
  "muk":            Item.NonburnableGarbage,
  "garbodor":       Item.NonburnableGarbage,
  "blissey":        Item.Stone,
  "rampardos":      Item.Stone,
  "bastiodon":      Item.Stone,
  "tyrantrum":      Item.Stone,
  "aurorus":        Item.Stone,
  "spinarak":       Item.Twine,
  "ariados":        Item.Twine,
  "larvesta":       Item.Twine,
  "volcarona":      Item.Twine,
  "mareep":         Item.Fluff,
  "flaaffy":        Item.Fluff,
  "swablu":         Item.Fluff,
  "altaria":        Item.Fluff,
  "paldean-wooper": Item.SquishyClay,
  "clodsire":       Item.SquishyClay,
  "trapinch":       Item.SquishyClay,
  "glimmet":        Item.IronOre,
  "glimmora":       Item.IronOre,
};
