// AUTO-GENERATED by scripts/gen-const-files.ts — do not edit by hand

export const Specialty = {
  Appraise: {
    slug: "appraise",
    label: "Appraise",
    description:
      "You can show lost relics you've found to Professor Tangrowth, who will appraise them for you",
  },
  Build: {
    slug: "build",
    label: "Build",
    description:
      "Pokemon with the Build specialty will lead your building projects",
  },
  Bulldoze: {
    slug: "bulldoze",
    label: "Bulldoze",
    description:
      "Pokemon with the Bulldoze specialty can lead your demolition, rebuilding or relocation projects",
  },
  Burn: {
    slug: "burn",
    label: "Burn",
    description:
      "Pokemon with the Burn specialty can set fire to Flammable objects. They can also turn Squish clay into Brick",
  },
  Chop: {
    slug: "chop",
    label: "Chop",
    description:
      "Pokemon with the Chop specialty can process small logs into lumber",
  },
  Collect: {
    slug: "collect",
    label: "Collect",
    description:
      "Pokemon with the Collect specialty will trade you rare things for certain items",
  },
  Crush: {
    slug: "crush",
    label: "Crush",
    description:
      "Pokemon with the Crush specialty can mash materials into different things",
  },
  DJ: {
    slug: "dj",
    label: "DJ",
    description: "DJ Rotom can use the DJ specialty to play music CDs for you",
  },
  DreamIsland: {
    slug: "dreamisland",
    label: "Dream Island",
    description:
      "Pokemon with the Dream Island specialty can transport you to a Dream Island",
  },
  Eat: {
    slug: "eat",
    label: "Eat",
    description:
      "Mosslax has the Eat specialty. Something good may happen if you offer them food",
  },
  Engineer: {
    slug: "engineer",
    label: "Engineer",
    description:
      "Tinkmaster has the Engineer specialty and can lead huge building projects",
  },
  Explode: {
    slug: "explode",
    label: "Explode",
    description:
      "Pokemon with the Explode specialty can be fired out of a cannon, destroying everything around them on impact",
  },
  Fly: {
    slug: "fly",
    label: "Fly",
    description:
      "Pokemon with the Fly spceialty can fly you to a Pokemon you're searching fo",
  },
  Gather: {
    slug: "gather",
    label: "Gather",
    description:
      "Pokemon with the Gather specialty will pick up items on the ground and put them inside a community box",
  },
  GatherHoney: {
    slug: "gatherhoney",
    label: "Gather Honey",
    description:
      "Pokemon with the Gather Honey specialty will give you special furniture if you bring them honey",
  },
  Generate: {
    slug: "generate",
    label: "Generate",
    description:
      "Pokemon with the Generate specialty can power machines with electricty",
  },
  Grow: {
    slug: "grow",
    label: "Grow",
    description: "Pokemon with the Grow specialty can make plants grow faster",
  },
  Hype: {
    slug: "hype",
    label: "Hype",
    description:
      "Pokemon with the Hype specialty will start dancing when they hear music, improving the mood",
  },
  Illuminate: {
    slug: "illuminate",
    label: "Illuminate",
    description:
      "Peakychu can use the Illuminate specialty to light up the whole town for you",
  },
  Litter: {
    slug: "litter",
    label: "Litter",
    description:
      "Pokemon with the Litter specialty will drop useful materials near their homes",
  },
  Paint: {
    slug: "paint",
    label: "Paint",
    description:
      "Smearguru has the Paint specialty and can recolor certain items, such as furniture",
  },
  Party: {
    slug: "party",
    label: "Party",
    description:
      "Chef Dente can use the Party specialty to help you prepare food for parties",
  },
  Rarify: {
    slug: "rarify",
    label: "Rarify",
    description:
      "Pokemon with the Rarify specialty can turn Star Pieces into rare Pokemetal",
  },
  Recycle: {
    slug: "recycle",
    label: "Recycle",
    description:
      "Pokemon with the Recycle specialty can process nonburnable garbage into iron ore and wastepaper into paper",
  },
  Search: {
    slug: "search",
    label: "Search",
    description:
      "Pokemon with the Search specialty can help you find buried items",
  },
  Storage: {
    slug: "storage",
    label: "Storage",
    description:
      "Pokemon with the Storage specialty can hold on to your items for you",
  },
  Teleport: {
    slug: "teleport",
    label: "Teleport",
    description:
      "Pokemon with the Teleport specialty can instantly take you to a Pokemon you're searching for",
  },
  Trade: {
    slug: "trade",
    label: "Trade",
    description:
      "Pokemon with the Trade speicalty can exchange items with you at a cash register",
  },
  Transform: {
    slug: "transform",
    label: "Transform",
    description: "Ditto can improve its moves by using Transform",
  },
  Water: {
    slug: "water",
    label: "Water",
    description:
      "Pokemon with the Water specialty can use a full water basin to spray water on nearby fields and plants",
  },
  Yawn: {
    slug: "yawn",
    label: "Yawn",
    description: "Pokemon with the Yawn specialty can tell you how humid it is",
  },
} as const;
export type SpecialtyConst = (typeof Specialty)[keyof typeof Specialty];
export type SpecialtyKey = keyof typeof Specialty;
