// AUTO-GENERATED by scripts/migrate-data.ts — do not edit by hand
import type { HabitatRequirement } from "../types";

export const HABITAT_REQUIREMENTS: Record<string, HabitatRequirement[]> = {
  "absoluteluxury": [
    {
      "type": "item",
      "value": "luxury-lamp",
      "name": "Luxury lamp",
      "qty": 1
    },
    {
      "type": "item",
      "value": "luxury-bed",
      "name": "Luxury bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": "luxury-sofa",
      "name": "Luxury sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": "luxury-table",
      "name": "Luxury table",
      "qty": 1
    }
  ],
  "alarmclocksleepzone": [
    {
      "type": "group",
      "value": "bed",
      "name": "Bed (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "alarm-clock",
      "name": "Alarm clock",
      "qty": 1
    }
  ],
  "allpackedup": [
    {
      "type": "item",
      "value": "cart",
      "name": "Cart",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cardboard-boxes",
      "name": "Cardboard boxes",
      "qty": 2
    }
  ],
  "ampedrockstage": [
    {
      "type": "item",
      "value": "speaker",
      "name": "Speaker",
      "qty": 2
    },
    {
      "type": "item",
      "value": "small-stage",
      "name": "Small stage",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cool-electric-guitar",
      "name": "Cool electric guitar",
      "qty": 1
    },
    {
      "type": "item",
      "value": "standing-mic",
      "name": "Standing mic",
      "qty": 1
    }
  ],
  "armorfossildisplay": [
    {
      "type": "group",
      "value": "pedestal",
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "armor-fossil",
      "name": "Armor Fossil",
      "qty": 1
    }
  ],
  "beachset": [
    {
      "type": "item",
      "value": "beach-chair",
      "name": "Beach chair",
      "qty": 1
    },
    {
      "type": "item",
      "value": "beach-parasol",
      "name": "Beach Parasol",
      "qty": 1
    },
    {
      "type": "item",
      "value": "side-table",
      "name": "Side table",
      "qty": 1
    }
  ],
  "bedwithaplush": [
    {
      "type": "group",
      "value": "bed",
      "name": "Bed (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "doll",
      "name": "Doll (any)",
      "qty": 1
    }
  ],
  "benchwithgreenery": [
    {
      "type": "group",
      "value": "hedge",
      "name": "Hedge (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    }
  ],
  "berry-feastcampsite": [
    {
      "type": "group",
      "value": "castform weather charm (sun)",
      "name": "Castform weather charm (sun) (any)",
      "qty": 2
    },
    {
      "type": "item",
      "value": "bonfire",
      "name": "Bonfire",
      "qty": 1
    },
    {
      "type": "item",
      "value": "berry-basket",
      "name": "Berry Basket",
      "qty": 1
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up Location (any)",
      "qty": 1
    }
  ],
  "bestbreadbakery": [
    {
      "type": "item",
      "value": "bread-oven",
      "name": "Bread oven",
      "qty": 1
    },
    {
      "type": "item",
      "value": "counter",
      "name": "Counter",
      "qty": 2
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "birdsonggarden": [
    {
      "type": "item",
      "value": "stylish-hedge",
      "name": "Stylish hedge",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wooden-birdhouse",
      "name": "Wooden Birdhouse",
      "qty": 1
    }
  ],
  "boulder-shadedtallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "item",
      "value": "large-boulder",
      "name": "Large Boulder",
      "qty": 1
    }
  ],
  "boundlessbluebeverage": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "soda-float",
      "name": "Soda Float",
      "qty": 1
    }
  ],
  "boxtotherhythm": [
    {
      "type": "item",
      "value": "punching-bag",
      "name": "Punching bag",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cd-player",
      "name": "CD player",
      "qty": 1
    }
  ],
  "breezyflowerbed": [
    {
      "type": "item",
      "value": "seashore-flowers",
      "name": "Seashore flowers",
      "qty": 4
    }
  ],
  "bronzelandmark": [
    {
      "type": "group",
      "value": "hedge",
      "name": "Hedge (any)",
      "qty": 4
    },
    {
      "type": "group",
      "value": "moonlight dance statue",
      "name": "Moonlight dance statue (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "sign",
      "name": "Sign",
      "qty": 1
    }
  ],
  "burning-hotspice": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "pizza",
      "name": "Pizza",
      "qty": 1
    }
  ],
  "cafespace": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "potted plant",
      "name": "Potted Plant (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "counter",
      "name": "Counter",
      "qty": 2
    },
    {
      "type": "item",
      "value": "mug",
      "name": "Mug",
      "qty": 1
    },
    {
      "type": "item",
      "value": "menu-board",
      "name": "Menu board",
      "qty": 1
    }
  ],
  "campsite": [
    {
      "type": "item",
      "value": "campfire",
      "name": "Campfire",
      "qty": 1
    },
    {
      "type": "item",
      "value": "straw-table",
      "name": "Straw Table",
      "qty": 1
    },
    {
      "type": "item",
      "value": "straw-stool",
      "name": "Straw stool",
      "qty": 1
    }
  ],
  "changingarea": [
    {
      "type": "group",
      "value": "closet",
      "name": "Closet (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "mirror (large)",
      "name": "Mirror (large) (any)",
      "qty": 1
    }
  ],
  "chanseyrestingarea": [
    {
      "type": "group",
      "value": "hedge",
      "name": "Hedge (any)",
      "qty": 6
    },
    {
      "type": "item",
      "value": "chansey-plant",
      "name": "Chansey plant",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (wide) (any)",
      "qty": 1
    }
  ],
  "chillyshavedice": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "shaved-ice",
      "name": "Shaved ice",
      "qty": 1
    }
  ],
  "chirp-chirpmeal": [
    {
      "type": "item",
      "value": "wooden-birdhouse",
      "name": "Wooden birdhouse",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "chirpingrecital": [
    {
      "type": "item",
      "value": "perch",
      "name": "Perch",
      "qty": 1
    },
    {
      "type": "item",
      "value": "standing-mic",
      "name": "Standing mic",
      "qty": 1
    }
  ],
  "clink-clangironconstruction": [
    {
      "type": "group",
      "value": "iron beam or column",
      "name": "Iron beam or column (any)",
      "qty": 3
    },
    {
      "type": "item",
      "value": "wheelbarrow",
      "name": "Wheelbarrow",
      "qty": 1
    },
    {
      "type": "item",
      "value": "sandbags",
      "name": "Sandbags",
      "qty": 1
    },
    {
      "type": "item",
      "value": "excavation-tools",
      "name": "Excavation tools",
      "qty": 1
    }
  ],
  "concretepipesecretbase": [
    {
      "type": "item",
      "value": "concrete-pipe",
      "name": "Concrete Pipe",
      "qty": 3
    },
    {
      "type": "group",
      "value": "tall grass",
      "name": "Tall Grass (any)",
      "qty": 4
    }
  ],
  "construction-sitegenerator": [
    {
      "type": "group",
      "value": "furnace",
      "name": "Furnace (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "iron-scaffold",
      "name": "Iron scaffold",
      "qty": 2
    },
    {
      "type": "item",
      "value": "iron-pipes",
      "name": "Iron pipes",
      "qty": 1
    }
  ],
  "containersnacking": [
    {
      "type": "item",
      "value": "barrel",
      "name": "Barrel",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wooden-crate",
      "name": "Wooden crate",
      "qty": 1
    },
    {
      "type": "item",
      "value": "lantern",
      "name": "Lantern",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "cozyloghandicrafts": [
    {
      "type": "item",
      "value": "log-chair",
      "name": "Log chair",
      "qty": 1
    },
    {
      "type": "item",
      "value": "log-bed",
      "name": "Log bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": "log-table",
      "name": "Log table",
      "qty": 1
    }
  ],
  "creepygraveoffering": [
    {
      "type": "item",
      "value": "eerie-candle",
      "name": "Eerie candle",
      "qty": 2
    },
    {
      "type": "item",
      "value": "gravestone",
      "name": "Gravestone",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "creepywhiterocks": [
    {
      "type": "item",
      "value": "stalagmites",
      "name": "Stalagmites",
      "qty": 1
    },
    {
      "type": "item",
      "value": "moss",
      "name": "Moss",
      "qty": 4
    },
    {
      "type": "item",
      "value": "wooden-crate",
      "name": "Wooden crate",
      "qty": 1
    },
    {
      "type": "item",
      "value": "lantern",
      "name": "Lantern",
      "qty": 1
    }
  ],
  "cutenessoverload": [
    {
      "type": "item",
      "value": "cute-sofa",
      "name": "Cute sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cute-table",
      "name": "Cute table",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cute-lamp",
      "name": "Cute lamp",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cute-bed",
      "name": "Cute bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cute-dresser",
      "name": "Cute dresser",
      "qty": 1
    }
  ],
  "cyclingreststop": [
    {
      "type": "item",
      "value": "bike",
      "name": "Bike",
      "qty": 1
    },
    {
      "type": "item",
      "value": "vending-machine",
      "name": "Vending Machine",
      "qty": 1
    }
  ],
  "dandelionlunchtime": [
    {
      "type": "item",
      "value": "dandy-flowers",
      "name": "Dandy flowers",
      "qty": 1
    },
    {
      "type": "item",
      "value": "flower-cushion",
      "name": "Flower cushion",
      "qty": 1
    },
    {
      "type": "item",
      "value": "lunch-box",
      "name": "Lunch box",
      "qty": 1
    },
    {
      "type": "item",
      "value": "flowery-table-setting",
      "name": "Flowery table setting",
      "qty": 1
    }
  ],
  "dark-chocolatecookies": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "chocolate-cookies",
      "name": "Chocolate cookies",
      "qty": 1
    }
  ],
  "despotfossildisplay": [
    {
      "type": "group",
      "value": "pedestal",
      "name": "Pedestal (any)",
      "qty": 2
    },
    {
      "type": "item",
      "value": "despot-fossil-head",
      "name": "Despot fossil (head)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "despot-fossil-body",
      "name": "Despot fossil (body)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "despot-fossil-legs",
      "name": "Despot fossil (legs)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "despot-fossil-tail",
      "name": "Despot fossil(tail)",
      "qty": 1
    }
  ],
  "diggingandburning": [
    {
      "type": "item",
      "value": "wheelbarrow",
      "name": "Wheelbarrow",
      "qty": 1
    },
    {
      "type": "item",
      "value": "smelting-furnace",
      "name": "Smelting furnace",
      "qty": 1
    },
    {
      "type": "item",
      "value": "excavation-tools",
      "name": "Excavation tools",
      "qty": 1
    }
  ],
  "dinnertablesurprise": [
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (wide) (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "table (large)",
      "name": "Table (large) (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "party-platter",
      "name": "Party Platter",
      "qty": 4
    }
  ],
  "dock": [
    {
      "type": "item",
      "value": "walkway",
      "name": "Walkway",
      "qty": 4
    },
    {
      "type": "group",
      "value": "streetlight",
      "name": "Streetlight (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "ocean water",
      "name": "Ocean Water (any)",
      "qty": 2
    }
  ],
  "dojotraining": [
    {
      "type": "item",
      "value": "hanging-scroll",
      "name": "Hanging scroll",
      "qty": 2
    },
    {
      "type": "item",
      "value": "strength-rock",
      "name": "Strength rock",
      "qty": 2
    }
  ],
  "electrifyingpotatoes": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "fried-potatoes",
      "name": "Fried Potatoes",
      "qty": 1
    }
  ],
  "elegantdaytimetreats": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "afternoon-tea-set",
      "name": "Afternoon tea set",
      "qty": 1
    }
  ],
  "elevatedflowerbed": [
    {
      "type": "item",
      "value": "wildflowers",
      "name": "Wildflowers",
      "qty": 4
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "elevatedpinktallgrass": [
    {
      "type": "item",
      "value": "pink-tall-grass",
      "name": "Pink tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "elevatedredtallgrass": [
    {
      "type": "item",
      "value": "red-tall-grass",
      "name": "Red tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "elevatedtallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up Location (any)",
      "qty": 1
    }
  ],
  "elevatedyellowtallgrass": [
    {
      "type": "item",
      "value": "yellow-tall-grass",
      "name": "Yellow tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "evilorganizationhq": [
    {
      "type": "group",
      "value": "potted plant",
      "name": "Potted plant (any)",
      "qty": 2
    },
    {
      "type": "item",
      "value": "team-rocket-wall-hanging",
      "name": "Team Rocket wall hanging",
      "qty": 1
    },
    {
      "type": "item",
      "value": "luxury-sofa",
      "name": "Luxury sofa",
      "qty": 1
    }
  ],
  "exerciserestingspot": [
    {
      "type": "item",
      "value": "punching-bag",
      "name": "Punching Bag",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    }
  ],
  "experimentspace": [
    {
      "type": "item",
      "value": "science-experiment",
      "name": "Science Experiment",
      "qty": 1
    },
    {
      "type": "item",
      "value": "microscope",
      "name": "Microscope",
      "qty": 1
    },
    {
      "type": "item",
      "value": "papers",
      "name": "Papers",
      "qty": 1
    }
  ],
  "factorystorage": [
    {
      "type": "group",
      "value": "streetlight",
      "name": "Streetlight (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "control-unit",
      "name": "Control unit",
      "qty": 1
    },
    {
      "type": "item",
      "value": "metal-drum",
      "name": "Metal drum",
      "qty": 1
    },
    {
      "type": "item",
      "value": "jumbled-cords",
      "name": "Jumbled cords",
      "qty": 1
    }
  ],
  "field-tripfriends": [
    {
      "type": "item",
      "value": "flower-backpack",
      "name": "Flower backpack",
      "qty": 1
    },
    {
      "type": "item",
      "value": "hoppip-water-bottle",
      "name": "Hoppip water bottle",
      "qty": 1
    },
    {
      "type": "item",
      "value": "lunch-box",
      "name": "Lunch box",
      "qty": 1
    }
  ],
  "fieldofflowers": [
    {
      "type": "item",
      "value": "wildflowers",
      "name": "Wildflowers",
      "qty": 8
    }
  ],
  "fireplacenapspot": [
    {
      "type": "item",
      "value": "stone-fireplace",
      "name": "Stone fireplace",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (wide) (any)",
      "qty": 1
    }
  ],
  "fishingpond": [
    {
      "type": "item",
      "value": "fishing-rod",
      "name": "Fishing Rod",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 1
    }
  ],
  "floatingintheshade": [
    {
      "type": "item",
      "value": "inflatable-boat",
      "name": "Inflatable boat",
      "qty": 1
    },
    {
      "type": "item",
      "value": "beach-parasol",
      "name": "Beach Parasol",
      "qty": 1
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "flowergarden": [
    {
      "type": "group",
      "value": "hedge",
      "name": "Hedge (any)",
      "qty": 4
    },
    {
      "type": "item",
      "value": "wildflowers",
      "name": "Wildflowers",
      "qty": 4
    }
  ],
  "flowergardenstumpstage": [
    {
      "type": "item",
      "value": "mountain-flowers",
      "name": "Mountain flowers",
      "qty": 4
    },
    {
      "type": "group",
      "value": "tree stump",
      "name": "Tree stump (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "mushroom-lamp",
      "name": "Mushroom lamp",
      "qty": 2
    }
  ],
  "flowerytable": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "small-vase",
      "name": "Small vase",
      "qty": 1
    }
  ],
  "fluffyflowerbed": [
    {
      "type": "item",
      "value": "skyland-flowers",
      "name": "Skyland flowers",
      "qty": 4
    }
  ],
  "freshveggiefield": [
    {
      "type": "group",
      "value": "vegetables",
      "name": "Vegetables (any)",
      "qty": 8
    }
  ],
  "fullrecovery": [
    {
      "type": "group",
      "value": "bed",
      "name": "Bed (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "plain-chest",
      "name": "Plain chest",
      "qty": 1
    },
    {
      "type": "item",
      "value": "first-aid-kit",
      "name": "First aid kit",
      "qty": 1
    }
  ],
  "furnacespot": [
    {
      "type": "item",
      "value": "metal-drum",
      "name": "Metal drum",
      "qty": 1
    },
    {
      "type": "group",
      "value": "furnace",
      "name": "Furnace (any)",
      "qty": 1
    }
  ],
  "gamecornerbattlezone": [
    {
      "type": "item",
      "value": "arcade-machine",
      "name": "Arcade Machine",
      "qty": 2
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 2
    }
  ],
  "gardenterrace": [
    {
      "type": "item",
      "value": "wildflowers",
      "name": "Wildflowers",
      "qty": 4
    },
    {
      "type": "item",
      "value": "garden-chair",
      "name": "Garden chair",
      "qty": 1
    },
    {
      "type": "item",
      "value": "garden-light",
      "name": "Garden light",
      "qty": 1
    },
    {
      "type": "item",
      "value": "garden-table",
      "name": "Garden table",
      "qty": 1
    }
  ],
  "gentlylitbed": [
    {
      "type": "group",
      "value": "bed",
      "name": "Bed (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "slender-candle",
      "name": "Slender Candle",
      "qty": 1
    }
  ],
  "goodold-fashionedantiques": [
    {
      "type": "item",
      "value": "antique-closet",
      "name": "Antique closet",
      "qty": 1
    },
    {
      "type": "item",
      "value": "antique-bed",
      "name": "Antique bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": "antique-dresser",
      "name": "Antique dresser",
      "qty": 1
    },
    {
      "type": "item",
      "value": "antique-chair",
      "name": "Antique chair",
      "qty": 1
    }
  ],
  "gracefulflowerbed": [
    {
      "type": "item",
      "value": "mountain-flowers",
      "name": "Mountain flowers",
      "qty": 4
    }
  ],
  "grassytrainingfield": [
    {
      "type": "item",
      "value": "sandbags",
      "name": "Sandbags",
      "qty": 2
    },
    {
      "type": "item",
      "value": "red-tall-grass",
      "name": "Red tall grass",
      "qty": 4
    }
  ],
  "graveoffering": [
    {
      "type": "item",
      "value": "gravestone",
      "name": "Gravestone",
      "qty": 1
    },
    {
      "type": "item",
      "value": "slender-candle",
      "name": "Slender candle",
      "qty": 2
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "gravewithflowers": [
    {
      "type": "item",
      "value": "wildflowers",
      "name": "Wildflowers",
      "qty": 4
    },
    {
      "type": "item",
      "value": "gravestone",
      "name": "Gravestone",
      "qty": 1
    }
  ],
  "gymfirstaid": [
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "punching-bag",
      "name": "Punching bag",
      "qty": 1
    },
    {
      "type": "item",
      "value": "first-aid-kit",
      "name": "First aid kit",
      "qty": 1
    }
  ],
  "harmonioushotspring": [
    {
      "type": "item",
      "value": "hot-spring-spout",
      "name": "Hot-spring spout",
      "qty": 1
    },
    {
      "type": "item",
      "value": "water-basin",
      "name": "Water Basin",
      "qty": 1
    },
    {
      "type": "group",
      "value": "hot-spring water",
      "name": "Hot-spring Water (any)",
      "qty": 2
    }
  ],
  "headbuttfossildisplay": [
    {
      "type": "group",
      "value": "pedestal",
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "headbutt-fossil-head",
      "name": "Headbutt fossil (head)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "headbutt-fossil-body",
      "name": "Headbutt fossil (body)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "headbutt-fossil-tail",
      "name": "Headbutt fossil (tail)",
      "qty": 1
    }
  ],
  "heart-poundingsurprisebox": [
    {
      "type": "item",
      "value": "spotlight",
      "name": "Spotlight",
      "qty": 2
    },
    {
      "type": "item",
      "value": "big-drum",
      "name": "Big drum",
      "qty": 1
    },
    {
      "type": "item",
      "value": "boo-in-the-box",
      "name": "Boo-in-the-box",
      "qty": 1
    }
  ],
  "heavyiron": [
    {
      "type": "item",
      "value": "iron-bed",
      "name": "Iron bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": "iron-table",
      "name": "Iron table",
      "qty": 1
    },
    {
      "type": "item",
      "value": "iron-chair",
      "name": "Iron chair",
      "qty": 1
    },
    {
      "type": "item",
      "value": "lantern",
      "name": "Lantern",
      "qty": 1
    }
  ],
  "hometheater": [
    {
      "type": "item",
      "value": "speaker",
      "name": "Speaker",
      "qty": 2
    },
    {
      "type": "group",
      "value": "stand",
      "name": "Stand (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "television",
      "name": "Television",
      "qty": 1
    }
  ],
  "hot-springfishingspot": [
    {
      "type": "item",
      "value": "fishing-rod",
      "name": "Fishing Rod",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "hot-spring water",
      "name": "Hot-spring Water (any)",
      "qty": 1
    }
  ],
  "hot-springshower": [
    {
      "type": "item",
      "value": "shower",
      "name": "Shower",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "hot-spring water",
      "name": "Hot-spring Water (any)",
      "qty": 2
    }
  ],
  "houseparty": [
    {
      "type": "item",
      "value": "food-counter",
      "name": "Food counter",
      "qty": 1
    },
    {
      "type": "item",
      "value": "paper-party-cups",
      "name": "Paper party cups",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "hydratedflowerbed": [
    {
      "type": "item",
      "value": "wildflowers",
      "name": "Wildflowers",
      "qty": 4
    }
  ],
  "hydratedfluffyflowerbed": [
    {
      "type": "item",
      "value": "skyland-flowers",
      "name": "Skyland flowers",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "hydratedgracefulflowerbed": [
    {
      "type": "item",
      "value": "mountain-flowers",
      "name": "Mountain flowers",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "hydratedpinktallgrass": [
    {
      "type": "item",
      "value": "pink-tall-grass",
      "name": "Pink tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "hydratedredtallgrass": [
    {
      "type": "item",
      "value": "red-tall-grass",
      "name": "Red tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "hydratedtallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "hydratedyellowtallgrass": [
    {
      "type": "item",
      "value": "yellow-tall-grass",
      "name": "Yellow tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "illuminatedbench": [
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (wide) (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "streetlight",
      "name": "Streetlight (any)",
      "qty": 1
    }
  ],
  "illuminatedtallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "lighting",
      "name": "Lighting (any)",
      "qty": 10
    }
  ],
  "illuminatedwaterfall": [
    {
      "type": "item",
      "value": "stepping-stones",
      "name": "Stepping stones",
      "qty": 3
    },
    {
      "type": "item",
      "value": "torch",
      "name": "Torch",
      "qty": 2
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 3
    },
    {
      "type": "group",
      "value": "waterfall",
      "name": "Waterfall (any)",
      "qty": 1
    }
  ],
  "interrogationdesk": [
    {
      "type": "item",
      "value": "arcanine-doll",
      "name": "Arcanine doll",
      "qty": 1
    },
    {
      "type": "item",
      "value": "folding-chair",
      "name": "Folding chair",
      "qty": 2
    },
    {
      "type": "item",
      "value": "industrial-desk",
      "name": "Industrial desk",
      "qty": 1
    },
    {
      "type": "item",
      "value": "desk-light",
      "name": "Desk light",
      "qty": 1
    }
  ],
  "irresistiblescentandglow": [
    {
      "type": "item",
      "value": "pitcher-plant-pot",
      "name": "Pitcher-plant pot",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "mushroom-lamp",
      "name": "Mushroom lamp",
      "qty": 1
    }
  ],
  "jawfossildisplay": [
    {
      "type": "group",
      "value": "pedestal",
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "jaw-fossil",
      "name": "Jaw Fossil",
      "qty": 1
    }
  ],
  "knittingstation": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "knitting-supplies",
      "name": "Knitting supplies",
      "qty": 1
    }
  ],
  "largeluggagecarrier": [
    {
      "type": "item",
      "value": "cart",
      "name": "Cart",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wooden-crate",
      "name": "Wooden crate",
      "qty": 2
    }
  ],
  "lazy-photoalbumscrolling": [
    {
      "type": "item",
      "value": "tablet",
      "name": "Tablet",
      "qty": 1
    },
    {
      "type": "item",
      "value": "paper-party-cups",
      "name": "Paper party cups",
      "qty": 1
    }
  ],
  "leafygreenssandwich": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "sandwiches",
      "name": "Sandwiches",
      "qty": 1
    }
  ],
  "light-upstage": [
    {
      "type": "item",
      "value": "spotlight",
      "name": "Spotlight",
      "qty": 2
    },
    {
      "type": "item",
      "value": "small-stage",
      "name": "Small Stage",
      "qty": 1
    }
  ],
  "lovelyribboncake": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "ribbon-cake",
      "name": "Ribbon Cake",
      "qty": 1
    }
  ],
  "low-keyrockstage": [
    {
      "type": "item",
      "value": "speaker",
      "name": "Speaker",
      "qty": 2
    },
    {
      "type": "item",
      "value": "small-stage",
      "name": "Small stage",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cool-bass-guitar",
      "name": "Cool bass guitar",
      "qty": 1
    },
    {
      "type": "item",
      "value": "standing-mic",
      "name": "Standing mic",
      "qty": 1
    }
  ],
  "luxurychirp-chirpmeal": [
    {
      "type": "item",
      "value": "wooden-birdhouse",
      "name": "Wooden birdhouse",
      "qty": 1
    },
    {
      "type": "item",
      "value": "berry-basket",
      "name": "Berry Basket",
      "qty": 1
    }
  ],
  "magmafishingspot": [
    {
      "type": "item",
      "value": "fishing-rod",
      "name": "Fishing rod",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "lava",
      "name": "Lava (any)",
      "qty": 1
    }
  ],
  "marshfishingspot": [
    {
      "type": "item",
      "value": "fishing-rod",
      "name": "Fishing Rod",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "muddy water",
      "name": "Muddy Water (any)",
      "qty": 1
    }
  ],
  "marshytallgrass": [
    {
      "type": "item",
      "value": "yellow-tall-grass",
      "name": "Yellow tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "muddy water",
      "name": "Muddy Water (any)",
      "qty": 2
    }
  ],
  "minigamecorner": [
    {
      "type": "item",
      "value": "arcade-machine",
      "name": "Arcade Machine",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "punching-game",
      "name": "Punching game",
      "qty": 1
    }
  ],
  "minikitchen": [
    {
      "type": "item",
      "value": "kitchen-table",
      "name": "Kitchen table",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cooking-stove",
      "name": "Cooking stove",
      "qty": 1
    },
    {
      "type": "item",
      "value": "frying-pan",
      "name": "Frying pan",
      "qty": 1
    },
    {
      "type": "item",
      "value": "modern-sink",
      "name": "Modern sink",
      "qty": 1
    }
  ],
  "minilibrary": [
    {
      "type": "item",
      "value": "bookcase",
      "name": "Bookcase",
      "qty": 2
    },
    {
      "type": "item",
      "value": "step-stool",
      "name": "Step stool",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "lighting",
      "name": "Lighting (any)",
      "qty": 1
    }
  ],
  "minimuseum": [
    {
      "type": "group",
      "value": "post",
      "name": "Post (any)",
      "qty": 3
    },
    {
      "type": "group",
      "value": "pedestal",
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "lost relic (large)",
      "name": "Lost relic (large) (any)",
      "qty": 1
    }
  ],
  "modernliving": [
    {
      "type": "item",
      "value": "industrial-bed",
      "name": "Industrial bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": "industrial-desk",
      "name": "Industrial desk",
      "qty": 1
    },
    {
      "type": "item",
      "value": "industrial-chair",
      "name": "Industrial chair",
      "qty": 1
    }
  ],
  "moisturizingmakeupstand": [
    {
      "type": "group",
      "value": "dresser",
      "name": "Dresser (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "humidifier",
      "name": "Humidifier",
      "qty": 1
    }
  ],
  "mossyboulder": [
    {
      "type": "item",
      "value": "moss",
      "name": "Moss",
      "qty": 4
    },
    {
      "type": "item",
      "value": "mossy-boulder",
      "name": "Mossy Boulder",
      "qty": 1
    }
  ],
  "mossyhotspring": [
    {
      "type": "item",
      "value": "moss",
      "name": "Moss",
      "qty": 4
    },
    {
      "type": "group",
      "value": "hot-spring water",
      "name": "Hot-spring Water (any)",
      "qty": 2
    }
  ],
  "mossyrestspot": [
    {
      "type": "item",
      "value": "moss",
      "name": "Moss",
      "qty": 4
    }
  ],
  "musicandmagazines": [
    {
      "type": "item",
      "value": "cd-player",
      "name": "CD Player",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cd-rack",
      "name": "CD rack",
      "qty": 1
    },
    {
      "type": "item",
      "value": "magazine-rack",
      "name": "Magazine rack",
      "qty": 1
    }
  ],
  "nightfestivalvenue": [
    {
      "type": "item",
      "value": "balloons",
      "name": "Balloons",
      "qty": 2
    },
    {
      "type": "item",
      "value": "raichu-sign",
      "name": "Raichu Sign",
      "qty": 1
    }
  ],
  "nineflames": [
    {
      "type": "item",
      "value": "firepit",
      "name": "Firepit",
      "qty": 9
    }
  ],
  "oceanfishingspot": [
    {
      "type": "item",
      "value": "fishing-rod",
      "name": "Fishing Rod",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "ocean water",
      "name": "Ocean Water (any)",
      "qty": 1
    }
  ],
  "officestoreroom": [
    {
      "type": "item",
      "value": "office-shelf",
      "name": "Office shelf",
      "qty": 1
    },
    {
      "type": "item",
      "value": "step-stool",
      "name": "Step stool",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cardboard-boxes",
      "name": "Cardboard boxes",
      "qty": 1
    }
  ],
  "open-airbath": [
    {
      "type": "item",
      "value": "hot-spring-spout",
      "name": "Hot-spring spout",
      "qty": 1
    },
    {
      "type": "group",
      "value": "hot-spring water",
      "name": "Hot-spring Water (any)",
      "qty": 1
    }
  ],
  "overgrowthvendingmachine": [
    {
      "type": "item",
      "value": "vending-machine",
      "name": "Vending machine",
      "qty": 1
    },
    {
      "type": "item",
      "value": "yellow-tall-grass",
      "name": "Yellow tall grass",
      "qty": 4
    }
  ],
  "oversizeddumpingground": [
    {
      "type": "group",
      "value": "iron beam or column",
      "name": "Iron beam or column (any)",
      "qty": 3
    },
    {
      "type": "item",
      "value": "tires",
      "name": "Tires",
      "qty": 1
    },
    {
      "type": "group",
      "value": "waste bin",
      "name": "Waste bin (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "microwave-oven",
      "name": "Microwave oven",
      "qty": 1
    }
  ],
  "parkbench": [
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (Wide) (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "garbage-bin",
      "name": "Garbage Bin",
      "qty": 1
    }
  ],
  "perpetualmess": [
    {
      "type": "group",
      "value": "cardboard boxes",
      "name": "Cardboard boxes (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "toy",
      "name": "Toy (any)",
      "qty": 2
    }
  ],
  "picnicset": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "picnic-basket",
      "name": "Picnic basket",
      "qty": 1
    }
  ],
  "picturesquephotocutoutboard": [
    {
      "type": "item",
      "value": "photo-cutout-board",
      "name": "Photo cutout board",
      "qty": 1
    },
    {
      "type": "item",
      "value": "spotlight",
      "name": "Spotlight",
      "qty": 2
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "pikachuspace": [
    {
      "type": "item",
      "value": "pikachu-sofa",
      "name": "Pikachu sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": "pikachu-doll",
      "name": "Pikachu doll",
      "qty": 1
    }
  ],
  "pinktallgrass": [
    {
      "type": "item",
      "value": "pink-tall-grass",
      "name": "Pink tall grass",
      "qty": 4
    }
  ],
  "piping-hotlava": [
    {
      "type": "item",
      "value": "molten-rock",
      "name": "Molten rock",
      "qty": 1
    },
    {
      "type": "group",
      "value": "lava",
      "name": "Lava (any)",
      "qty": 2
    }
  ],
  "plainlife": [
    {
      "type": "item",
      "value": "plain-bed",
      "name": "Plain bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": "plain-sofa",
      "name": "Plain sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": "plain-table",
      "name": "Plain table",
      "qty": 1
    },
    {
      "type": "item",
      "value": "plain-lamp",
      "name": "Plain lamp",
      "qty": 1
    }
  ],
  "playingpirate": [
    {
      "type": "item",
      "value": "barrel",
      "name": "Barrel",
      "qty": 2
    },
    {
      "type": "item",
      "value": "ship-s-wheel",
      "name": "Ship's wheel",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cannon",
      "name": "Cannon",
      "qty": 2
    }
  ],
  "playland": [
    {
      "type": "item",
      "value": "slide",
      "name": "Slide",
      "qty": 1
    },
    {
      "type": "group",
      "value": "toy",
      "name": "Toy (Any)",
      "qty": 1
    }
  ],
  "plushcentral": [
    {
      "type": "item",
      "value": "arcanine-doll",
      "name": "Arcanine doll",
      "qty": 1
    },
    {
      "type": "item",
      "value": "pikachu-doll",
      "name": "Pikachu doll",
      "qty": 1
    },
    {
      "type": "item",
      "value": "dragonite-doll",
      "name": "Dragonite doll",
      "qty": 1
    },
    {
      "type": "item",
      "value": "eevee-doll",
      "name": "Eevee Doll",
      "qty": 1
    }
  ],
  "pointytree-shadedrockytallgrass": [
    {
      "type": "item",
      "value": "pointy-tree",
      "name": "Pointy tree",
      "qty": 1
    },
    {
      "type": "item",
      "value": "red-tall-grass",
      "name": "Red tall grass",
      "qty": 4
    },
    {
      "type": "item",
      "value": "large-boulder",
      "name": "Large Boulder",
      "qty": 1
    }
  ],
  "prankbutton": [
    {
      "type": "item",
      "value": "floor-switch",
      "name": "Floor switch",
      "qty": 1
    },
    {
      "type": "group",
      "value": "boo-in-the-box",
      "name": "Boo-in-the-box (any)",
      "qty": 1
    }
  ],
  "prettyflowerbed": [
    {
      "type": "item",
      "value": "wildflowers",
      "name": "Wildflowers",
      "qty": 4
    }
  ],
  "privatemakeupstand": [
    {
      "type": "group",
      "value": "partition",
      "name": "Partition (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "closet",
      "name": "Closet (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "dresser",
      "name": "Dresser (any)",
      "qty": 1
    }
  ],
  "publicreadingmaterial": [
    {
      "type": "item",
      "value": "magazine-rack",
      "name": "Magazine rack",
      "qty": 1
    },
    {
      "type": "item",
      "value": "newspaper",
      "name": "Newspaper",
      "qty": 1
    }
  ],
  "railroadcrossing": [
    {
      "type": "item",
      "value": "railway-track",
      "name": "Railway track",
      "qty": 1
    },
    {
      "type": "item",
      "value": "crossing-gate",
      "name": "Crossing gate",
      "qty": 1
    }
  ],
  "raindancesite": [
    {
      "type": "group",
      "value": "castform weather charm (rain)",
      "name": "Castform weather charm (rain) (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "recitalstage": [
    {
      "type": "item",
      "value": "speaker",
      "name": "Speaker",
      "qty": 2
    },
    {
      "type": "item",
      "value": "small-stage",
      "name": "Small stage",
      "qty": 1
    },
    {
      "type": "item",
      "value": "standing-mic",
      "name": "Standing mic",
      "qty": 1
    }
  ],
  "redtallgrass": [
    {
      "type": "item",
      "value": "red-tall-grass",
      "name": "Red tall grass",
      "qty": 4
    }
  ],
  "refreshinglockerroom": [
    {
      "type": "item",
      "value": "office-locker",
      "name": "Office locker",
      "qty": 2
    },
    {
      "type": "group",
      "value": "potted plant",
      "name": "Potted plant (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (wide) (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "punching-game",
      "name": "Punching game",
      "qty": 1
    }
  ],
  "resortmealprep": [
    {
      "type": "item",
      "value": "large-palm-tree",
      "name": "Large palm tree",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "campfire",
      "name": "Campfire",
      "qty": 1
    }
  ],
  "restingspot": [
    {
      "type": "group",
      "value": "cardboard boxes",
      "name": "Cardboard boxes (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "straw-bed",
      "name": "Straw bed",
      "qty": 1
    }
  ],
  "rhythmiclivingroom": [
    {
      "type": "item",
      "value": "speaker",
      "name": "Speaker",
      "qty": 2
    },
    {
      "type": "item",
      "value": "television",
      "name": "Television",
      "qty": 1
    },
    {
      "type": "group",
      "value": "music mat",
      "name": "Music mat (any)",
      "qty": 4
    }
  ],
  "ridingwarmupdrafts": [
    {
      "type": "item",
      "value": "campfire",
      "name": "Campfire",
      "qty": 3
    }
  ],
  "roadsign": [
    {
      "type": "item",
      "value": "arrow-sign",
      "name": "Arrow sign",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wooden-path",
      "name": "Wooden path",
      "qty": 3
    }
  ],
  "sailfossildisplay": [
    {
      "type": "group",
      "value": "pedestal",
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "sail-fossil",
      "name": "Sail Fossil",
      "qty": 1
    }
  ],
  "seasidetallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "ocean water",
      "name": "Ocean Water (any)",
      "qty": 2
    }
  ],
  "sewerholeinspection": [
    {
      "type": "item",
      "value": "iron-pipes",
      "name": "Iron Pipes",
      "qty": 1
    },
    {
      "type": "item",
      "value": "sewer-hole-cover",
      "name": "Sewer-hole cover",
      "qty": 1
    },
    {
      "type": "item",
      "value": "excavation-tools",
      "name": "Excavation tools",
      "qty": 1
    },
    {
      "type": "item",
      "value": "traffic-cone",
      "name": "Traffic cone",
      "qty": 1
    }
  ],
  "shadedbeach": [
    {
      "type": "item",
      "value": "large-palm-tree",
      "name": "Large palm tree",
      "qty": 1
    },
    {
      "type": "item",
      "value": "beach-chair",
      "name": "Beach chair",
      "qty": 1
    }
  ],
  "shieldfossildisplay": [
    {
      "type": "group",
      "value": "pedestal",
      "name": "Pedestal (any)",
      "qty": 2
    },
    {
      "type": "item",
      "value": "shield-fossil-head",
      "name": "Shield fossil (head)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "shield-fossil-body",
      "name": "Shield fossil (body)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "shield-fossil-tail",
      "name": "Shield fossil (tail)",
      "qty": 1
    }
  ],
  "simplebathroom": [
    {
      "type": "item",
      "value": "shower",
      "name": "Shower",
      "qty": 1
    },
    {
      "type": "item",
      "value": "bathtub",
      "name": "Bathtub",
      "qty": 1
    }
  ],
  "skullfossildisplay": [
    {
      "type": "group",
      "value": "pedestal",
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "skull-fossil",
      "name": "Skull Fossil",
      "qty": 1
    }
  ],
  "smoothtallgrass": [
    {
      "type": "item",
      "value": "dry-tall-grass",
      "name": "Dry tall grass",
      "qty": 4
    },
    {
      "type": "item",
      "value": "smooth-rock",
      "name": "Smooth Rock",
      "qty": 1
    }
  ],
  "spookystudy": [
    {
      "type": "item",
      "value": "bookcase",
      "name": "Bookcase",
      "qty": 1
    },
    {
      "type": "item",
      "value": "chic-sofa",
      "name": "Chic sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": "plain-table",
      "name": "Plain table",
      "qty": 1
    },
    {
      "type": "item",
      "value": "slender-candle",
      "name": "Slender candle",
      "qty": 1
    }
  ],
  "spotlesswashingstation": [
    {
      "type": "item",
      "value": "towel-rack",
      "name": "Towel Rack",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wall-mirror",
      "name": "Wall mirror",
      "qty": 1
    },
    {
      "type": "item",
      "value": "sink",
      "name": "Sink",
      "qty": 1
    }
  ],
  "squeakyclean": [
    {
      "type": "item",
      "value": "bathtub",
      "name": "Bathtub",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cleaning-supplies",
      "name": "Cleaning supplies",
      "qty": 1
    }
  ],
  "studyarea": [
    {
      "type": "item",
      "value": "bookcase",
      "name": "Bookcase",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "pencil-holder",
      "name": "Pencil holder",
      "qty": 1
    }
  ],
  "sunnydaysite": [
    {
      "type": "group",
      "value": "castform weather charm (sun)",
      "name": "Castform weather charm (sun) (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "surgingpsychicpower": [
    {
      "type": "item",
      "value": "simple-cushion",
      "name": "Simple cushion",
      "qty": 1
    },
    {
      "type": "item",
      "value": "crystal-ball",
      "name": "Crystal Ball",
      "qty": 1
    }
  ],
  "surpriseinstore": [
    {
      "type": "item",
      "value": "balloons",
      "name": "Balloons",
      "qty": 2
    },
    {
      "type": "item",
      "value": "boo-in-the-box",
      "name": "Boo-in-the-box",
      "qty": 1
    }
  ],
  "tablesidedeliverycart": [
    {
      "type": "item",
      "value": "chic-chair",
      "name": "Chic chair",
      "qty": 2
    },
    {
      "type": "item",
      "value": "chic-table",
      "name": "Chic table",
      "qty": 1
    },
    {
      "type": "item",
      "value": "small-vase",
      "name": "Small vase",
      "qty": 1
    },
    {
      "type": "item",
      "value": "push-cart",
      "name": "Push cart",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "tallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    }
  ],
  "tantalizingdiningset": [
    {
      "type": "item",
      "value": "leppa-berry",
      "name": "Leppa Berry",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wooden-stool",
      "name": "Wooden Stool",
      "qty": 1
    }
  ],
  "tantalizingrestaurant": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "menu-board",
      "name": "Menu board",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated Food (any)",
      "qty": 1
    }
  ],
  "tinyatelier": [
    {
      "type": "group",
      "value": "canvas",
      "name": "Canvas (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    }
  ],
  "tirepark": [
    {
      "type": "item",
      "value": "slide",
      "name": "Slide",
      "qty": 1
    },
    {
      "type": "item",
      "value": "tires",
      "name": "Tires",
      "qty": 1
    },
    {
      "type": "item",
      "value": "tire-toy",
      "name": "Tire Toy",
      "qty": 2
    }
  ],
  "toilinthesoil": [
    {
      "type": "group",
      "value": "vegetable field",
      "name": "Vegetable field (any)",
      "qty": 4
    },
    {
      "type": "item",
      "value": "wheelbarrow",
      "name": "Wheelbarrow",
      "qty": 1
    }
  ],
  "toppop": [
    {
      "type": "item",
      "value": "pop-art-bed",
      "name": "Pop art bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": "pop-art-sofa",
      "name": "Pop art sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": "pop-art-table",
      "name": "Pop art table",
      "qty": 1
    }
  ],
  "trainingwaterfall": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "waterfall",
      "name": "Waterfall (any)",
      "qty": 1
    }
  ],
  "trashcancentral": [
    {
      "type": "item",
      "value": "garbage-bin",
      "name": "Garbage bin",
      "qty": 4
    }
  ],
  "trashcollectionsite": [
    {
      "type": "item",
      "value": "garbage-bin",
      "name": "Garbage bin",
      "qty": 1
    },
    {
      "type": "item",
      "value": "sign",
      "name": "Sign",
      "qty": 1
    },
    {
      "type": "item",
      "value": "garbage-bags",
      "name": "Garbage bags",
      "qty": 1
    }
  ],
  "trashdisposalsite": [
    {
      "type": "item",
      "value": "utility-pole",
      "name": "Utility pole",
      "qty": 1
    },
    {
      "type": "group",
      "value": "garbage bags",
      "name": "Garbage bags (any)",
      "qty": 1
    }
  ],
  "trashsitetv": [
    {
      "type": "item",
      "value": "garbage-bags",
      "name": "Garbage bags",
      "qty": 2
    },
    {
      "type": "item",
      "value": "television",
      "name": "Television",
      "qty": 1
    }
  ],
  "treasure-huntingset": [
    {
      "type": "item",
      "value": "adventure-kit",
      "name": "Adventure kit",
      "qty": 1
    },
    {
      "type": "item",
      "value": "map-and-compass",
      "name": "Map and compass",
      "qty": 1
    },
    {
      "type": "item",
      "value": "treasure",
      "name": "Treasure",
      "qty": 1
    }
  ],
  "tree-shadedflowerbed": [
    {
      "type": "item",
      "value": "wildflowers",
      "name": "Wildflowers",
      "qty": 4
    },
    {
      "type": "group",
      "value": "berry tree",
      "name": "Berry tree (any)",
      "qty": 1
    }
  ],
  "tree-shadedfluffyflowerbed": [
    {
      "type": "group",
      "value": "large tree",
      "name": "Large tree (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "skyland-flowers",
      "name": "Skyland flowers",
      "qty": 4
    }
  ],
  "tree-shadedgracefulflowerbed": [
    {
      "type": "item",
      "value": "pointy-tree",
      "name": "Pointy tree",
      "qty": 1
    },
    {
      "type": "item",
      "value": "mountain-flowers",
      "name": "Mountain flowers",
      "qty": 4
    }
  ],
  "tree-shadedpinktallgrass": [
    {
      "type": "item",
      "value": "pink-tall-grass",
      "name": "Pink tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "large tree",
      "name": "Large tree (any)",
      "qty": 1
    }
  ],
  "tree-shadedredtallgrass": [
    {
      "type": "item",
      "value": "red-tall-grass",
      "name": "Red tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "large tree",
      "name": "Large tree (any)",
      "qty": 1
    }
  ],
  "tree-shadedsnoozingsnorlax": [
    {
      "type": "group",
      "value": "large tree",
      "name": "Large tree (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "naptime-bed",
      "name": "Naptime bed",
      "qty": 1
    }
  ],
  "tree-shadedtallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "tree",
      "name": "Tree (any)",
      "qty": 1
    }
  ],
  "tree-shadedyellowtallgrass": [
    {
      "type": "item",
      "value": "yellow-tall-grass",
      "name": "Yellow tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "large tree",
      "name": "Large tree (any)",
      "qty": 1
    }
  ],
  "tropicalseaside": [
    {
      "type": "item",
      "value": "large-palm-tree",
      "name": "Large palm tree",
      "qty": 1
    },
    {
      "type": "group",
      "value": "hedge",
      "name": "Hedge (any)",
      "qty": 4
    },
    {
      "type": "group",
      "value": "ocean water",
      "name": "Ocean Water (any)",
      "qty": 2
    }
  ],
  "tropicalvibes": [
    {
      "type": "item",
      "value": "large-palm-tree",
      "name": "Large palm tree",
      "qty": 1
    },
    {
      "type": "item",
      "value": "seashore-flowers",
      "name": "seashore flowers",
      "qty": 4
    }
  ],
  "tundrafossildisplay": [
    {
      "type": "group",
      "value": "pedestal",
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "tundra-fossil-head",
      "name": "Tundra fossil (head)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "tundra-fossil-body",
      "name": "Tundra fossil (body)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "tundra-fossil-tail",
      "name": "Tundra fossil (tail)",
      "qty": 1
    }
  ],
  "upliftingduckweed": [
    {
      "type": "item",
      "value": "duckweed",
      "name": "Duckweed",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "urgentcare": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "first-aid-kit",
      "name": "First aid kit",
      "qty": 1
    }
  ],
  "vendingmachinebreakarea": [
    {
      "type": "item",
      "value": "vending-machine",
      "name": "Vending machine",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (Wide) (any)",
      "qty": 1
    }
  ],
  "vendingmachineset": [
    {
      "type": "group",
      "value": "waste bin",
      "name": "Waste bin (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "vending-machine",
      "name": "Vending Machine",
      "qty": 1
    }
  ],
  "very-berryspace": [
    {
      "type": "item",
      "value": "berry-chair",
      "name": "Berry chair",
      "qty": 1
    },
    {
      "type": "item",
      "value": "berry-bed",
      "name": "Berry bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": "berry-table",
      "name": "Berry table",
      "qty": 1
    },
    {
      "type": "item",
      "value": "berry-table-lamp",
      "name": "Berry table lamp",
      "qty": 1
    }
  ],
  "watersidedinghy": [
    {
      "type": "item",
      "value": "canoe",
      "name": "Canoe",
      "qty": 1
    },
    {
      "type": "item",
      "value": "duckweed",
      "name": "Duckweed",
      "qty": 2
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "waterwheelspot": [
    {
      "type": "group",
      "value": "waterwheel",
      "name": "Waterwheel (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "waterfall",
      "name": "Waterfall (any)",
      "qty": 1
    }
  ],
  "welcomingresort": [
    {
      "type": "item",
      "value": "resort-sofa",
      "name": "Resort sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": "resort-table",
      "name": "Resort table",
      "qty": 1
    },
    {
      "type": "item",
      "value": "resort-hammock",
      "name": "Resort hammock",
      "qty": 1
    },
    {
      "type": "item",
      "value": "resort-light",
      "name": "Resort light",
      "qty": 1
    }
  ],
  "windyflowerbed": [
    {
      "type": "group",
      "value": "windmill",
      "name": "Windmill (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "seashore-flowers",
      "name": "seashore flowers",
      "qty": 4
    }
  ],
  "wingfossildisplay": [
    {
      "type": "group",
      "value": "pedestal",
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wing-fossil-head",
      "name": "Wing fossil (head)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wing-fossil-body",
      "name": "Wing fossil (body)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wing-fossil-left-wing",
      "name": "Wing fossil (left wing)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wing-fossil-right-wing",
      "name": "Wing fossil (right wing)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "wing-fossil-tail",
      "name": "Wing fossil (tail)",
      "qty": 1
    }
  ],
  "workdesk": [
    {
      "type": "item",
      "value": "office-desk",
      "name": "Office desk",
      "qty": 1
    },
    {
      "type": "item",
      "value": "laptop",
      "name": "Laptop",
      "qty": 1
    },
    {
      "type": "item",
      "value": "mug",
      "name": "Mug",
      "qty": 1
    },
    {
      "type": "item",
      "value": "office-chair",
      "name": "Office chair",
      "qty": 1
    }
  ],
  "workingtheregister": [
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": "cash-register",
      "name": "Cash register",
      "qty": 1
    }
  ],
  "yellowcarpet": [
    {
      "type": "item",
      "value": "dandy-flowers",
      "name": "Dandy flowers",
      "qty": 4
    }
  ],
  "yellowtallgrass": [
    {
      "type": "item",
      "value": "yellow-tall-grass",
      "name": "Yellow tall grass",
      "qty": 4
    }
  ]
} as const;
