// AUTO-GENERATED by scripts/migrate-data.ts — do not edit by hand
import type { HabitatRequirement } from "../types";
import { Item } from "./consts";

export const HABITAT_REQUIREMENTS: Record<string, HabitatRequirement[]> = {
  "absoluteluxury": [
    {
      "type": "item",
      "value": Item.LuxuryLamp,
      "name": "Luxury lamp",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.LuxuryBed,
      "name": "Luxury bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.LuxurySofa,
      "name": "Luxury sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.LuxuryTable,
      "name": "Luxury table",
      "qty": 1
    }
  ],
  "alarmclocksleepzone": [
    {
      "type": "group",
      "value": "bed",
      "name": "Bed (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.AlarmClock,
      "name": "Alarm clock",
      "qty": 1
    }
  ],
  "allpackedup": [
    {
      "type": "item",
      "value": Item.Cart,
      "name": "Cart",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CardboardBoxes,
      "name": "Cardboard boxes",
      "qty": 2
    }
  ],
  "ampedrockstage": [
    {
      "type": "item",
      "value": Item.Speaker,
      "name": "Speaker",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.SmallStage,
      "name": "Small stage",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CoolElectricGuitar,
      "name": "Cool electric guitar",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.StandingMic,
      "name": "Standing mic",
      "qty": 1
    }
  ],
  "armorfossildisplay": [
    {
      "type": "group",
      "value": Item.Pedestal,
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ArmorFossil,
      "name": "Armor Fossil",
      "qty": 1
    }
  ],
  "beachset": [
    {
      "type": "item",
      "value": Item.BeachChair,
      "name": "Beach chair",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.BeachParasol,
      "name": "Beach Parasol",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SideTable,
      "name": "Side table",
      "qty": 1
    }
  ],
  "bedwithaplush": [
    {
      "type": "group",
      "value": "bed",
      "name": "Bed (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "doll",
      "name": "Doll (any)",
      "qty": 1
    }
  ],
  "benchwithgreenery": [
    {
      "type": "group",
      "value": "hedge",
      "name": "Hedge (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    }
  ],
  "berry-feastcampsite": [
    {
      "type": "group",
      "value": "castform weather charm (sun)",
      "name": "Castform weather charm (sun) (any)",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.Bonfire,
      "name": "Bonfire",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.BerryBasket,
      "name": "Berry Basket",
      "qty": 1
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up Location (any)",
      "qty": 1
    }
  ],
  "bestbreadbakery": [
    {
      "type": "item",
      "value": Item.BreadOven,
      "name": "Bread oven",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Counter,
      "name": "Counter",
      "qty": 2
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "birdsonggarden": [
    {
      "type": "item",
      "value": Item.StylishHedge,
      "name": "Stylish hedge",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WoodenBirdhouse,
      "name": "Wooden Birdhouse",
      "qty": 1
    }
  ],
  "boulder-shadedtallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "item",
      "value": Item.LargeBoulder,
      "name": "Large Boulder",
      "qty": 1
    }
  ],
  "boundlessbluebeverage": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SodaFloat,
      "name": "Soda Float",
      "qty": 1
    }
  ],
  "boxtotherhythm": [
    {
      "type": "item",
      "value": Item.PunchingBag,
      "name": "Punching bag",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CDPlayer,
      "name": "CD player",
      "qty": 1
    }
  ],
  "breezyflowerbed": [
    {
      "type": "item",
      "value": Item.SeashoreFlowers,
      "name": "Seashore flowers",
      "qty": 4
    }
  ],
  "bronzelandmark": [
    {
      "type": "group",
      "value": "hedge",
      "name": "Hedge (any)",
      "qty": 4
    },
    {
      "type": "group",
      "value": "moonlight dance statue",
      "name": "Moonlight dance statue (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Sign,
      "name": "Sign",
      "qty": 1
    }
  ],
  "burning-hotspice": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Pizza,
      "name": "Pizza",
      "qty": 1
    }
  ],
  "cafespace": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "potted plant",
      "name": "Potted Plant (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Counter,
      "name": "Counter",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.Mug,
      "name": "Mug",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.MenuBoard,
      "name": "Menu board",
      "qty": 1
    }
  ],
  "campsite": [
    {
      "type": "item",
      "value": Item.Campfire,
      "name": "Campfire",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.StrawTable,
      "name": "Straw Table",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.StrawStool,
      "name": "Straw stool",
      "qty": 1
    }
  ],
  "changingarea": [
    {
      "type": "group",
      "value": "closet",
      "name": "Closet (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "mirror (large)",
      "name": "Mirror (large) (any)",
      "qty": 1
    }
  ],
  "chanseyrestingarea": [
    {
      "type": "group",
      "value": "hedge",
      "name": "Hedge (any)",
      "qty": 6
    },
    {
      "type": "item",
      "value": Item.ChanseyPlant,
      "name": "Chansey plant",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (wide) (any)",
      "qty": 1
    }
  ],
  "chillyshavedice": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ShavedIce,
      "name": "Shaved ice",
      "qty": 1
    }
  ],
  "chirp-chirpmeal": [
    {
      "type": "item",
      "value": Item.WoodenBirdhouse,
      "name": "Wooden birdhouse",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "chirpingrecital": [
    {
      "type": "item",
      "value": Item.Perch,
      "name": "Perch",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.StandingMic,
      "name": "Standing mic",
      "qty": 1
    }
  ],
  "clink-clangironconstruction": [
    {
      "type": "group",
      "value": "iron beam or column",
      "name": "Iron beam or column (any)",
      "qty": 3
    },
    {
      "type": "item",
      "value": Item.Wheelbarrow,
      "name": "Wheelbarrow",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Sandbags,
      "name": "Sandbags",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ExcavationTools,
      "name": "Excavation tools",
      "qty": 1
    }
  ],
  "concretepipesecretbase": [
    {
      "type": "item",
      "value": Item.ConcretePipe,
      "name": "Concrete Pipe",
      "qty": 3
    },
    {
      "type": "group",
      "value": "tall grass",
      "name": "Tall Grass (any)",
      "qty": 4
    }
  ],
  "construction-sitegenerator": [
    {
      "type": "group",
      "value": "furnace",
      "name": "Furnace (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.IronScaffold,
      "name": "Iron scaffold",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.IronPipes,
      "name": "Iron pipes",
      "qty": 1
    }
  ],
  "containersnacking": [
    {
      "type": "item",
      "value": Item.Barrel,
      "name": "Barrel",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WoodenCrate,
      "name": "Wooden crate",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Lantern,
      "name": "Lantern",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "cozyloghandicrafts": [
    {
      "type": "item",
      "value": Item.LogChair,
      "name": "Log chair",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.LogBed,
      "name": "Log bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.LogTable,
      "name": "Log table",
      "qty": 1
    }
  ],
  "creepygraveoffering": [
    {
      "type": "item",
      "value": Item.EerieCandle,
      "name": "Eerie candle",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.Gravestone,
      "name": "Gravestone",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "creepywhiterocks": [
    {
      "type": "item",
      "value": Item.Stalagmites,
      "name": "Stalagmites",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Moss,
      "name": "Moss",
      "qty": 4
    },
    {
      "type": "item",
      "value": Item.WoodenCrate,
      "name": "Wooden crate",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Lantern,
      "name": "Lantern",
      "qty": 1
    }
  ],
  "cutenessoverload": [
    {
      "type": "item",
      "value": Item.CuteSofa,
      "name": "Cute sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CuteTable,
      "name": "Cute table",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CuteLamp,
      "name": "Cute lamp",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CuteBed,
      "name": "Cute bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CuteDresser,
      "name": "Cute dresser",
      "qty": 1
    }
  ],
  "cyclingreststop": [
    {
      "type": "item",
      "value": Item.Bike,
      "name": "Bike",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.VendingMachine,
      "name": "Vending Machine",
      "qty": 1
    }
  ],
  "dandelionlunchtime": [
    {
      "type": "item",
      "value": Item.DandyFlowers,
      "name": "Dandy flowers",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.FlowerCushion,
      "name": "Flower cushion",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.LunchBox,
      "name": "Lunch box",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.FloweryTableSetting,
      "name": "Flowery table setting",
      "qty": 1
    }
  ],
  "dark-chocolatecookies": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ChocolateCookies,
      "name": "Chocolate cookies",
      "qty": 1
    }
  ],
  "despotfossildisplay": [
    {
      "type": "group",
      "value": Item.Pedestal,
      "name": "Pedestal (any)",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.DespotFossilHead,
      "name": "Despot fossil (head)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.DespotFossilBody,
      "name": "Despot fossil (body)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.DespotFossilLegs,
      "name": "Despot fossil (legs)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.DespotFossilTail,
      "name": "Despot fossil(tail)",
      "qty": 1
    }
  ],
  "diggingandburning": [
    {
      "type": "item",
      "value": Item.Wheelbarrow,
      "name": "Wheelbarrow",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SmeltingFurnace,
      "name": "Smelting furnace",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ExcavationTools,
      "name": "Excavation tools",
      "qty": 1
    }
  ],
  "dinnertablesurprise": [
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (wide) (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "table (large)",
      "name": "Table (large) (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PartyPlatter,
      "name": "Party Platter",
      "qty": 4
    }
  ],
  "dock": [
    {
      "type": "item",
      "value": Item.Walkway,
      "name": "Walkway",
      "qty": 4
    },
    {
      "type": "group",
      "value": "streetlight",
      "name": "Streetlight (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "ocean water",
      "name": "Ocean Water (any)",
      "qty": 2
    }
  ],
  "dojotraining": [
    {
      "type": "item",
      "value": Item.HangingScroll,
      "name": "Hanging scroll",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.StrengthRock,
      "name": "Strength rock",
      "qty": 2
    }
  ],
  "electrifyingpotatoes": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.FriedPotatoes,
      "name": "Fried Potatoes",
      "qty": 1
    }
  ],
  "elegantdaytimetreats": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.AfternoonTeaSet,
      "name": "Afternoon tea set",
      "qty": 1
    }
  ],
  "elevatedflowerbed": [
    {
      "type": "item",
      "value": Item.Wildflowers,
      "name": "Wildflowers",
      "qty": 4
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "elevatedpinktallgrass": [
    {
      "type": "item",
      "value": Item.PinkTallGrass,
      "name": "Pink tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "elevatedredtallgrass": [
    {
      "type": "item",
      "value": Item.RedTallGrass,
      "name": "Red tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "elevatedtallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up Location (any)",
      "qty": 1
    }
  ],
  "elevatedyellowtallgrass": [
    {
      "type": "item",
      "value": Item.YellowTallGrass,
      "name": "Yellow tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "evilorganizationhq": [
    {
      "type": "group",
      "value": "potted plant",
      "name": "Potted plant (any)",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.TeamRocketWallHanging,
      "name": "Team Rocket wall hanging",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.LuxurySofa,
      "name": "Luxury sofa",
      "qty": 1
    }
  ],
  "exerciserestingspot": [
    {
      "type": "item",
      "value": Item.PunchingBag,
      "name": "Punching Bag",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    }
  ],
  "experimentspace": [
    {
      "type": "item",
      "value": Item.ScienceExperiment,
      "name": "Science Experiment",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Microscope,
      "name": "Microscope",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Papers,
      "name": "Papers",
      "qty": 1
    }
  ],
  "factorystorage": [
    {
      "type": "group",
      "value": "streetlight",
      "name": "Streetlight (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ControlUnit,
      "name": "Control unit",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.MetalDrum,
      "name": "Metal drum",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.JumbledCords,
      "name": "Jumbled cords",
      "qty": 1
    }
  ],
  "field-tripfriends": [
    {
      "type": "item",
      "value": Item.FlowerBackpack,
      "name": "Flower backpack",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.HoppipWaterBottle,
      "name": "Hoppip water bottle",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.LunchBox,
      "name": "Lunch box",
      "qty": 1
    }
  ],
  "fieldofflowers": [
    {
      "type": "item",
      "value": Item.Wildflowers,
      "name": "Wildflowers",
      "qty": 8
    }
  ],
  "fireplacenapspot": [
    {
      "type": "item",
      "value": Item.StoneFireplace,
      "name": "Stone fireplace",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (wide) (any)",
      "qty": 1
    }
  ],
  "fishingpond": [
    {
      "type": "item",
      "value": Item.FishingRod,
      "name": "Fishing Rod",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 1
    }
  ],
  "floatingintheshade": [
    {
      "type": "item",
      "value": Item.InflatableBoat,
      "name": "Inflatable boat",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.BeachParasol,
      "name": "Beach Parasol",
      "qty": 1
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "flowergarden": [
    {
      "type": "group",
      "value": "hedge",
      "name": "Hedge (any)",
      "qty": 4
    },
    {
      "type": "item",
      "value": Item.Wildflowers,
      "name": "Wildflowers",
      "qty": 4
    }
  ],
  "flowergardenstumpstage": [
    {
      "type": "item",
      "value": Item.MountainFlowers,
      "name": "Mountain flowers",
      "qty": 4
    },
    {
      "type": "group",
      "value": "tree stump",
      "name": "Tree stump (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.MushroomLamp,
      "name": "Mushroom lamp",
      "qty": 2
    }
  ],
  "flowerytable": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SmallVase,
      "name": "Small vase",
      "qty": 1
    }
  ],
  "fluffyflowerbed": [
    {
      "type": "item",
      "value": Item.SkylandFlowers,
      "name": "Skyland flowers",
      "qty": 4
    }
  ],
  "freshveggiefield": [
    {
      "type": "group",
      "value": "vegetables",
      "name": "Vegetables (any)",
      "qty": 8
    }
  ],
  "fullrecovery": [
    {
      "type": "group",
      "value": "bed",
      "name": "Bed (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PlainChest,
      "name": "Plain chest",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.FirstAidKit,
      "name": "First aid kit",
      "qty": 1
    }
  ],
  "furnacespot": [
    {
      "type": "item",
      "value": Item.MetalDrum,
      "name": "Metal drum",
      "qty": 1
    },
    {
      "type": "group",
      "value": "furnace",
      "name": "Furnace (any)",
      "qty": 1
    }
  ],
  "gamecornerbattlezone": [
    {
      "type": "item",
      "value": Item.ArcadeMachine,
      "name": "Arcade Machine",
      "qty": 2
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 2
    }
  ],
  "gardenterrace": [
    {
      "type": "item",
      "value": Item.Wildflowers,
      "name": "Wildflowers",
      "qty": 4
    },
    {
      "type": "item",
      "value": Item.GardenChair,
      "name": "Garden chair",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.GardenLight,
      "name": "Garden light",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.GardenTable,
      "name": "Garden table",
      "qty": 1
    }
  ],
  "gentlylitbed": [
    {
      "type": "group",
      "value": "bed",
      "name": "Bed (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SlenderCandle,
      "name": "Slender Candle",
      "qty": 1
    }
  ],
  "goodold-fashionedantiques": [
    {
      "type": "item",
      "value": Item.AntiqueCloset,
      "name": "Antique closet",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.AntiqueBed,
      "name": "Antique bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.AntiqueDresser,
      "name": "Antique dresser",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.AntiqueChair,
      "name": "Antique chair",
      "qty": 1
    }
  ],
  "gracefulflowerbed": [
    {
      "type": "item",
      "value": Item.MountainFlowers,
      "name": "Mountain flowers",
      "qty": 4
    }
  ],
  "grassytrainingfield": [
    {
      "type": "item",
      "value": Item.Sandbags,
      "name": "Sandbags",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.RedTallGrass,
      "name": "Red tall grass",
      "qty": 4
    }
  ],
  "graveoffering": [
    {
      "type": "item",
      "value": Item.Gravestone,
      "name": "Gravestone",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SlenderCandle,
      "name": "Slender candle",
      "qty": 2
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "gravewithflowers": [
    {
      "type": "item",
      "value": Item.Wildflowers,
      "name": "Wildflowers",
      "qty": 4
    },
    {
      "type": "item",
      "value": Item.Gravestone,
      "name": "Gravestone",
      "qty": 1
    }
  ],
  "gymfirstaid": [
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PunchingBag,
      "name": "Punching bag",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.FirstAidKit,
      "name": "First aid kit",
      "qty": 1
    }
  ],
  "harmonioushotspring": [
    {
      "type": "item",
      "value": Item.HotSpringSpout,
      "name": "Hot-spring spout",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WaterBasin,
      "name": "Water Basin",
      "qty": 1
    },
    {
      "type": "group",
      "value": "hot-spring water",
      "name": "Hot-spring Water (any)",
      "qty": 2
    }
  ],
  "headbuttfossildisplay": [
    {
      "type": "group",
      "value": Item.Pedestal,
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.HeadbuttFossilHead,
      "name": "Headbutt fossil (head)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.HeadbuttFossilBody,
      "name": "Headbutt fossil (body)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.HeadbuttFossilTail,
      "name": "Headbutt fossil (tail)",
      "qty": 1
    }
  ],
  "heart-poundingsurprisebox": [
    {
      "type": "item",
      "value": Item.Spotlight,
      "name": "Spotlight",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.BigDrum,
      "name": "Big drum",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.BooInTheBox,
      "name": "Boo-in-the-box",
      "qty": 1
    }
  ],
  "heavyiron": [
    {
      "type": "item",
      "value": Item.IronBed,
      "name": "Iron bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.IronTable,
      "name": "Iron table",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.IronChair,
      "name": "Iron chair",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Lantern,
      "name": "Lantern",
      "qty": 1
    }
  ],
  "hometheater": [
    {
      "type": "item",
      "value": Item.Speaker,
      "name": "Speaker",
      "qty": 2
    },
    {
      "type": "group",
      "value": "stand",
      "name": "Stand (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Television,
      "name": "Television",
      "qty": 1
    }
  ],
  "hot-springfishingspot": [
    {
      "type": "item",
      "value": Item.FishingRod,
      "name": "Fishing Rod",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "hot-spring water",
      "name": "Hot-spring Water (any)",
      "qty": 1
    }
  ],
  "hot-springshower": [
    {
      "type": "item",
      "value": Item.Shower,
      "name": "Shower",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "hot-spring water",
      "name": "Hot-spring Water (any)",
      "qty": 2
    }
  ],
  "houseparty": [
    {
      "type": "item",
      "value": Item.FoodCounter,
      "name": "Food counter",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PaperPartyCups,
      "name": "Paper party cups",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "hydratedflowerbed": [
    {
      "type": "item",
      "value": Item.Wildflowers,
      "name": "Wildflowers",
      "qty": 4
    }
  ],
  "hydratedfluffyflowerbed": [
    {
      "type": "item",
      "value": Item.SkylandFlowers,
      "name": "Skyland flowers",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "hydratedgracefulflowerbed": [
    {
      "type": "item",
      "value": Item.MountainFlowers,
      "name": "Mountain flowers",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "hydratedpinktallgrass": [
    {
      "type": "item",
      "value": Item.PinkTallGrass,
      "name": "Pink tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "hydratedredtallgrass": [
    {
      "type": "item",
      "value": Item.RedTallGrass,
      "name": "Red tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "hydratedtallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "hydratedyellowtallgrass": [
    {
      "type": "item",
      "value": Item.YellowTallGrass,
      "name": "Yellow tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "illuminatedbench": [
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (wide) (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "streetlight",
      "name": "Streetlight (any)",
      "qty": 1
    }
  ],
  "illuminatedtallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "lighting",
      "name": "Lighting (any)",
      "qty": 10
    }
  ],
  "illuminatedwaterfall": [
    {
      "type": "item",
      "value": Item.SteppingStones,
      "name": "Stepping stones",
      "qty": 3
    },
    {
      "type": "item",
      "value": Item.Torch,
      "name": "Torch",
      "qty": 2
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 3
    },
    {
      "type": "group",
      "value": Item.Waterfall,
      "name": "Waterfall (any)",
      "qty": 1
    }
  ],
  "interrogationdesk": [
    {
      "type": "item",
      "value": Item.ArcanineDoll,
      "name": "Arcanine doll",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.FoldingChair,
      "name": "Folding chair",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.IndustrialDesk,
      "name": "Industrial desk",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.DeskLight,
      "name": "Desk light",
      "qty": 1
    }
  ],
  "irresistiblescentandglow": [
    {
      "type": "item",
      "value": Item.PitcherPlantPot,
      "name": "Pitcher-plant pot",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.MushroomLamp,
      "name": "Mushroom lamp",
      "qty": 1
    }
  ],
  "jawfossildisplay": [
    {
      "type": "group",
      "value": Item.Pedestal,
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.JawFossil,
      "name": "Jaw Fossil",
      "qty": 1
    }
  ],
  "knittingstation": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.KnittingSupplies,
      "name": "Knitting supplies",
      "qty": 1
    }
  ],
  "largeluggagecarrier": [
    {
      "type": "item",
      "value": Item.Cart,
      "name": "Cart",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WoodenCrate,
      "name": "Wooden crate",
      "qty": 2
    }
  ],
  "lazy-photoalbumscrolling": [
    {
      "type": "item",
      "value": Item.Tablet,
      "name": "Tablet",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PaperPartyCups,
      "name": "Paper party cups",
      "qty": 1
    }
  ],
  "leafygreenssandwich": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Sandwiches,
      "name": "Sandwiches",
      "qty": 1
    }
  ],
  "light-upstage": [
    {
      "type": "item",
      "value": Item.Spotlight,
      "name": "Spotlight",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.SmallStage,
      "name": "Small Stage",
      "qty": 1
    }
  ],
  "lovelyribboncake": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.RibbonCake,
      "name": "Ribbon Cake",
      "qty": 1
    }
  ],
  "low-keyrockstage": [
    {
      "type": "item",
      "value": Item.Speaker,
      "name": "Speaker",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.SmallStage,
      "name": "Small stage",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CoolBassGuitar,
      "name": "Cool bass guitar",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.StandingMic,
      "name": "Standing mic",
      "qty": 1
    }
  ],
  "luxurychirp-chirpmeal": [
    {
      "type": "item",
      "value": Item.WoodenBirdhouse,
      "name": "Wooden birdhouse",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.BerryBasket,
      "name": "Berry Basket",
      "qty": 1
    }
  ],
  "magmafishingspot": [
    {
      "type": "item",
      "value": Item.FishingRod,
      "name": "Fishing rod",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": Item.Lava,
      "name": "Lava (any)",
      "qty": 1
    }
  ],
  "marshfishingspot": [
    {
      "type": "item",
      "value": Item.FishingRod,
      "name": "Fishing Rod",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "muddy water",
      "name": "Muddy Water (any)",
      "qty": 1
    }
  ],
  "marshytallgrass": [
    {
      "type": "item",
      "value": Item.YellowTallGrass,
      "name": "Yellow tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "muddy water",
      "name": "Muddy Water (any)",
      "qty": 2
    }
  ],
  "minigamecorner": [
    {
      "type": "item",
      "value": Item.ArcadeMachine,
      "name": "Arcade Machine",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PunchingGame,
      "name": "Punching game",
      "qty": 1
    }
  ],
  "minikitchen": [
    {
      "type": "item",
      "value": Item.KitchenTable,
      "name": "Kitchen table",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CookingStove,
      "name": "Cooking stove",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.FryingPan,
      "name": "Frying pan",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ModernSink,
      "name": "Modern sink",
      "qty": 1
    }
  ],
  "minilibrary": [
    {
      "type": "item",
      "value": Item.Bookcase,
      "name": "Bookcase",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.StepStool,
      "name": "Step stool",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "lighting",
      "name": "Lighting (any)",
      "qty": 1
    }
  ],
  "minimuseum": [
    {
      "type": "group",
      "value": Item.Post,
      "name": "Post (any)",
      "qty": 3
    },
    {
      "type": "group",
      "value": Item.Pedestal,
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "lost relic (large)",
      "name": "Lost relic (large) (any)",
      "qty": 1
    }
  ],
  "modernliving": [
    {
      "type": "item",
      "value": Item.IndustrialBed,
      "name": "Industrial bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.IndustrialDesk,
      "name": "Industrial desk",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.IndustrialChair,
      "name": "Industrial chair",
      "qty": 1
    }
  ],
  "moisturizingmakeupstand": [
    {
      "type": "group",
      "value": "dresser",
      "name": "Dresser (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Humidifier,
      "name": "Humidifier",
      "qty": 1
    }
  ],
  "mossyboulder": [
    {
      "type": "item",
      "value": Item.Moss,
      "name": "Moss",
      "qty": 4
    },
    {
      "type": "item",
      "value": Item.MossyBoulder,
      "name": "Mossy Boulder",
      "qty": 1
    }
  ],
  "mossyhotspring": [
    {
      "type": "item",
      "value": Item.Moss,
      "name": "Moss",
      "qty": 4
    },
    {
      "type": "group",
      "value": "hot-spring water",
      "name": "Hot-spring Water (any)",
      "qty": 2
    }
  ],
  "mossyrestspot": [
    {
      "type": "item",
      "value": Item.Moss,
      "name": "Moss",
      "qty": 4
    }
  ],
  "musicandmagazines": [
    {
      "type": "item",
      "value": Item.CDPlayer,
      "name": "CD Player",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CDRack,
      "name": "CD rack",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.MagazineRack,
      "name": "Magazine rack",
      "qty": 1
    }
  ],
  "nightfestivalvenue": [
    {
      "type": "item",
      "value": Item.Balloons,
      "name": "Balloons",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.RaichuSign,
      "name": "Raichu Sign",
      "qty": 1
    }
  ],
  "nineflames": [
    {
      "type": "item",
      "value": Item.Firepit,
      "name": "Firepit",
      "qty": 9
    }
  ],
  "oceanfishingspot": [
    {
      "type": "item",
      "value": Item.FishingRod,
      "name": "Fishing Rod",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "ocean water",
      "name": "Ocean Water (any)",
      "qty": 1
    }
  ],
  "officestoreroom": [
    {
      "type": "item",
      "value": Item.OfficeShelf,
      "name": "Office shelf",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.StepStool,
      "name": "Step stool",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CardboardBoxes,
      "name": "Cardboard boxes",
      "qty": 1
    }
  ],
  "open-airbath": [
    {
      "type": "item",
      "value": Item.HotSpringSpout,
      "name": "Hot-spring spout",
      "qty": 1
    },
    {
      "type": "group",
      "value": "hot-spring water",
      "name": "Hot-spring Water (any)",
      "qty": 1
    }
  ],
  "overgrowthvendingmachine": [
    {
      "type": "item",
      "value": Item.VendingMachine,
      "name": "Vending machine",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.YellowTallGrass,
      "name": "Yellow tall grass",
      "qty": 4
    }
  ],
  "oversizeddumpingground": [
    {
      "type": "group",
      "value": "iron beam or column",
      "name": "Iron beam or column (any)",
      "qty": 3
    },
    {
      "type": "item",
      "value": Item.Tires,
      "name": "Tires",
      "qty": 1
    },
    {
      "type": "group",
      "value": "waste bin",
      "name": "Waste bin (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.MicrowaveOven,
      "name": "Microwave oven",
      "qty": 1
    }
  ],
  "parkbench": [
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (Wide) (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.GarbageBin,
      "name": "Garbage Bin",
      "qty": 1
    }
  ],
  "perpetualmess": [
    {
      "type": "group",
      "value": "cardboard boxes",
      "name": "Cardboard boxes (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "toy",
      "name": "Toy (any)",
      "qty": 2
    }
  ],
  "picnicset": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PicnicBasket,
      "name": "Picnic basket",
      "qty": 1
    }
  ],
  "picturesquephotocutoutboard": [
    {
      "type": "item",
      "value": Item.PhotoCutoutBoard,
      "name": "Photo cutout board",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Spotlight,
      "name": "Spotlight",
      "qty": 2
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "pikachuspace": [
    {
      "type": "item",
      "value": Item.PikachuSofa,
      "name": "Pikachu sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PikachuDoll,
      "name": "Pikachu doll",
      "qty": 1
    }
  ],
  "pinktallgrass": [
    {
      "type": "item",
      "value": Item.PinkTallGrass,
      "name": "Pink tall grass",
      "qty": 4
    }
  ],
  "piping-hotlava": [
    {
      "type": "item",
      "value": Item.MoltenRock,
      "name": "Molten rock",
      "qty": 1
    },
    {
      "type": "group",
      "value": Item.Lava,
      "name": "Lava (any)",
      "qty": 2
    }
  ],
  "plainlife": [
    {
      "type": "item",
      "value": Item.PlainBed,
      "name": "Plain bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PlainSofa,
      "name": "Plain sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PlainTable,
      "name": "Plain table",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PlainLamp,
      "name": "Plain lamp",
      "qty": 1
    }
  ],
  "playingpirate": [
    {
      "type": "item",
      "value": Item.Barrel,
      "name": "Barrel",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.ShipsWheel,
      "name": "Ship's wheel",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Cannon,
      "name": "Cannon",
      "qty": 2
    }
  ],
  "playland": [
    {
      "type": "item",
      "value": Item.Slide,
      "name": "Slide",
      "qty": 1
    },
    {
      "type": "group",
      "value": "toy",
      "name": "Toy (Any)",
      "qty": 1
    }
  ],
  "plushcentral": [
    {
      "type": "item",
      "value": Item.ArcanineDoll,
      "name": "Arcanine doll",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PikachuDoll,
      "name": "Pikachu doll",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.DragoniteDoll,
      "name": "Dragonite doll",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.EeveeDoll,
      "name": "Eevee Doll",
      "qty": 1
    }
  ],
  "pointytree-shadedrockytallgrass": [
    {
      "type": "item",
      "value": Item.PointyTree,
      "name": "Pointy tree",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.RedTallGrass,
      "name": "Red tall grass",
      "qty": 4
    },
    {
      "type": "item",
      "value": Item.LargeBoulder,
      "name": "Large Boulder",
      "qty": 1
    }
  ],
  "prankbutton": [
    {
      "type": "item",
      "value": Item.FloorSwitch,
      "name": "Floor switch",
      "qty": 1
    },
    {
      "type": "group",
      "value": Item.BooInTheBox,
      "name": "Boo-in-the-box (any)",
      "qty": 1
    }
  ],
  "prettyflowerbed": [
    {
      "type": "item",
      "value": Item.Wildflowers,
      "name": "Wildflowers",
      "qty": 4
    }
  ],
  "privatemakeupstand": [
    {
      "type": "group",
      "value": "partition",
      "name": "Partition (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "closet",
      "name": "Closet (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "dresser",
      "name": "Dresser (any)",
      "qty": 1
    }
  ],
  "publicreadingmaterial": [
    {
      "type": "item",
      "value": Item.MagazineRack,
      "name": "Magazine rack",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Newspaper,
      "name": "Newspaper",
      "qty": 1
    }
  ],
  "railroadcrossing": [
    {
      "type": "item",
      "value": Item.RailwayTrack,
      "name": "Railway track",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CrossingGate,
      "name": "Crossing gate",
      "qty": 1
    }
  ],
  "raindancesite": [
    {
      "type": "group",
      "value": "castform weather charm (rain)",
      "name": "Castform weather charm (rain) (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "recitalstage": [
    {
      "type": "item",
      "value": Item.Speaker,
      "name": "Speaker",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.SmallStage,
      "name": "Small stage",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.StandingMic,
      "name": "Standing mic",
      "qty": 1
    }
  ],
  "redtallgrass": [
    {
      "type": "item",
      "value": Item.RedTallGrass,
      "name": "Red tall grass",
      "qty": 4
    }
  ],
  "refreshinglockerroom": [
    {
      "type": "item",
      "value": Item.OfficeLocker,
      "name": "Office locker",
      "qty": 2
    },
    {
      "type": "group",
      "value": "potted plant",
      "name": "Potted plant (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (wide) (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PunchingGame,
      "name": "Punching game",
      "qty": 1
    }
  ],
  "resortmealprep": [
    {
      "type": "item",
      "value": Item.LargePalmTree,
      "name": "Large palm tree",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Campfire,
      "name": "Campfire",
      "qty": 1
    }
  ],
  "restingspot": [
    {
      "type": "group",
      "value": "cardboard boxes",
      "name": "Cardboard boxes (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.StrawBed,
      "name": "Straw bed",
      "qty": 1
    }
  ],
  "rhythmiclivingroom": [
    {
      "type": "item",
      "value": Item.Speaker,
      "name": "Speaker",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.Television,
      "name": "Television",
      "qty": 1
    },
    {
      "type": "group",
      "value": "music mat",
      "name": "Music mat (any)",
      "qty": 4
    }
  ],
  "ridingwarmupdrafts": [
    {
      "type": "item",
      "value": Item.Campfire,
      "name": "Campfire",
      "qty": 3
    }
  ],
  "roadsign": [
    {
      "type": "item",
      "value": Item.ArrowSign,
      "name": "Arrow sign",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WoodenPath,
      "name": "Wooden path",
      "qty": 3
    }
  ],
  "sailfossildisplay": [
    {
      "type": "group",
      "value": Item.Pedestal,
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SailFossil,
      "name": "Sail Fossil",
      "qty": 1
    }
  ],
  "seasidetallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "ocean water",
      "name": "Ocean Water (any)",
      "qty": 2
    }
  ],
  "sewerholeinspection": [
    {
      "type": "item",
      "value": Item.IronPipes,
      "name": "Iron Pipes",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SewerHoleCover,
      "name": "Sewer-hole cover",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ExcavationTools,
      "name": "Excavation tools",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.TrafficCone,
      "name": "Traffic cone",
      "qty": 1
    }
  ],
  "shadedbeach": [
    {
      "type": "item",
      "value": Item.LargePalmTree,
      "name": "Large palm tree",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.BeachChair,
      "name": "Beach chair",
      "qty": 1
    }
  ],
  "shieldfossildisplay": [
    {
      "type": "group",
      "value": Item.Pedestal,
      "name": "Pedestal (any)",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.ShieldFossilHead,
      "name": "Shield fossil (head)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ShieldFossilBody,
      "name": "Shield fossil (body)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ShieldFossilTail,
      "name": "Shield fossil (tail)",
      "qty": 1
    }
  ],
  "simplebathroom": [
    {
      "type": "item",
      "value": Item.Shower,
      "name": "Shower",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Bathtub,
      "name": "Bathtub",
      "qty": 1
    }
  ],
  "skullfossildisplay": [
    {
      "type": "group",
      "value": Item.Pedestal,
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SkullFossil,
      "name": "Skull Fossil",
      "qty": 1
    }
  ],
  "smoothtallgrass": [
    {
      "type": "item",
      "value": Item.DryTallGrass,
      "name": "Dry tall grass",
      "qty": 4
    },
    {
      "type": "item",
      "value": Item.SmoothRock,
      "name": "Smooth Rock",
      "qty": 1
    }
  ],
  "spookystudy": [
    {
      "type": "item",
      "value": Item.Bookcase,
      "name": "Bookcase",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ChicSofa,
      "name": "Chic sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PlainTable,
      "name": "Plain table",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SlenderCandle,
      "name": "Slender candle",
      "qty": 1
    }
  ],
  "spotlesswashingstation": [
    {
      "type": "item",
      "value": Item.TowelRack,
      "name": "Towel Rack",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WallMirror,
      "name": "Wall mirror",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Sink,
      "name": "Sink",
      "qty": 1
    }
  ],
  "squeakyclean": [
    {
      "type": "item",
      "value": Item.Bathtub,
      "name": "Bathtub",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CleaningSupplies,
      "name": "Cleaning supplies",
      "qty": 1
    }
  ],
  "studyarea": [
    {
      "type": "item",
      "value": Item.Bookcase,
      "name": "Bookcase",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PencilHolder,
      "name": "Pencil holder",
      "qty": 1
    }
  ],
  "sunnydaysite": [
    {
      "type": "group",
      "value": "castform weather charm (sun)",
      "name": "Castform weather charm (sun) (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "surgingpsychicpower": [
    {
      "type": "item",
      "value": Item.SimpleCushion,
      "name": "Simple cushion",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CrystalBall,
      "name": "Crystal Ball",
      "qty": 1
    }
  ],
  "surpriseinstore": [
    {
      "type": "item",
      "value": Item.Balloons,
      "name": "Balloons",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.BooInTheBox,
      "name": "Boo-in-the-box",
      "qty": 1
    }
  ],
  "tablesidedeliverycart": [
    {
      "type": "item",
      "value": Item.ChicChair,
      "name": "Chic chair",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.ChicTable,
      "name": "Chic table",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SmallVase,
      "name": "Small vase",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PushCart,
      "name": "Push cart",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated food (any)",
      "qty": 1
    }
  ],
  "tallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    }
  ],
  "tantalizingdiningset": [
    {
      "type": "item",
      "value": Item.LeppaBerry,
      "name": "Leppa Berry",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WoodenStool,
      "name": "Wooden Stool",
      "qty": 1
    }
  ],
  "tantalizingrestaurant": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.MenuBoard,
      "name": "Menu board",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "plated food",
      "name": "Plated Food (any)",
      "qty": 1
    }
  ],
  "tinyatelier": [
    {
      "type": "group",
      "value": Item.Canvas,
      "name": "Canvas (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    }
  ],
  "tirepark": [
    {
      "type": "item",
      "value": Item.Slide,
      "name": "Slide",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Tires,
      "name": "Tires",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.TireToy,
      "name": "Tire Toy",
      "qty": 2
    }
  ],
  "toilinthesoil": [
    {
      "type": "group",
      "value": "vegetable field",
      "name": "Vegetable field (any)",
      "qty": 4
    },
    {
      "type": "item",
      "value": Item.Wheelbarrow,
      "name": "Wheelbarrow",
      "qty": 1
    }
  ],
  "toppop": [
    {
      "type": "item",
      "value": Item.PopArtBed,
      "name": "Pop art bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PopArtSofa,
      "name": "Pop art sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.PopArtTable,
      "name": "Pop art table",
      "qty": 1
    }
  ],
  "trainingwaterfall": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": Item.Waterfall,
      "name": "Waterfall (any)",
      "qty": 1
    }
  ],
  "trashcancentral": [
    {
      "type": "item",
      "value": Item.GarbageBin,
      "name": "Garbage bin",
      "qty": 4
    }
  ],
  "trashcollectionsite": [
    {
      "type": "item",
      "value": Item.GarbageBin,
      "name": "Garbage bin",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Sign,
      "name": "Sign",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.GarbageBags,
      "name": "Garbage bags",
      "qty": 1
    }
  ],
  "trashdisposalsite": [
    {
      "type": "item",
      "value": Item.UtilityPole,
      "name": "Utility pole",
      "qty": 1
    },
    {
      "type": "group",
      "value": "garbage bags",
      "name": "Garbage bags (any)",
      "qty": 1
    }
  ],
  "trashsitetv": [
    {
      "type": "item",
      "value": Item.GarbageBags,
      "name": "Garbage bags",
      "qty": 2
    },
    {
      "type": "item",
      "value": Item.Television,
      "name": "Television",
      "qty": 1
    }
  ],
  "treasure-huntingset": [
    {
      "type": "item",
      "value": Item.AdventureKit,
      "name": "Adventure kit",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.MapAndCompass,
      "name": "Map and compass",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Treasure,
      "name": "Treasure",
      "qty": 1
    }
  ],
  "tree-shadedflowerbed": [
    {
      "type": "item",
      "value": Item.Wildflowers,
      "name": "Wildflowers",
      "qty": 4
    },
    {
      "type": "group",
      "value": "berry tree",
      "name": "Berry tree (any)",
      "qty": 1
    }
  ],
  "tree-shadedfluffyflowerbed": [
    {
      "type": "group",
      "value": "large tree",
      "name": "Large tree (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SkylandFlowers,
      "name": "Skyland flowers",
      "qty": 4
    }
  ],
  "tree-shadedgracefulflowerbed": [
    {
      "type": "item",
      "value": Item.PointyTree,
      "name": "Pointy tree",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.MountainFlowers,
      "name": "Mountain flowers",
      "qty": 4
    }
  ],
  "tree-shadedpinktallgrass": [
    {
      "type": "item",
      "value": Item.PinkTallGrass,
      "name": "Pink tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "large tree",
      "name": "Large tree (any)",
      "qty": 1
    }
  ],
  "tree-shadedredtallgrass": [
    {
      "type": "item",
      "value": Item.RedTallGrass,
      "name": "Red tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "large tree",
      "name": "Large tree (any)",
      "qty": 1
    }
  ],
  "tree-shadedsnoozingsnorlax": [
    {
      "type": "group",
      "value": "large tree",
      "name": "Large tree (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.NaptimeBed,
      "name": "Naptime bed",
      "qty": 1
    }
  ],
  "tree-shadedtallgrass": [
    {
      "type": "item",
      "value": "tall-grass",
      "name": "Tall Grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "tree",
      "name": "Tree (any)",
      "qty": 1
    }
  ],
  "tree-shadedyellowtallgrass": [
    {
      "type": "item",
      "value": Item.YellowTallGrass,
      "name": "Yellow tall grass",
      "qty": 4
    },
    {
      "type": "group",
      "value": "large tree",
      "name": "Large tree (any)",
      "qty": 1
    }
  ],
  "tropicalseaside": [
    {
      "type": "item",
      "value": Item.LargePalmTree,
      "name": "Large palm tree",
      "qty": 1
    },
    {
      "type": "group",
      "value": "hedge",
      "name": "Hedge (any)",
      "qty": 4
    },
    {
      "type": "group",
      "value": "ocean water",
      "name": "Ocean Water (any)",
      "qty": 2
    }
  ],
  "tropicalvibes": [
    {
      "type": "item",
      "value": Item.LargePalmTree,
      "name": "Large palm tree",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SeashoreFlowers,
      "name": "seashore flowers",
      "qty": 4
    }
  ],
  "tundrafossildisplay": [
    {
      "type": "group",
      "value": Item.Pedestal,
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.TundraFossilHead,
      "name": "Tundra fossil (head)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.TundraFossilBody,
      "name": "Tundra fossil (body)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.TundraFossilTail,
      "name": "Tundra fossil (tail)",
      "qty": 1
    }
  ],
  "upliftingduckweed": [
    {
      "type": "item",
      "value": Item.Duckweed,
      "name": "Duckweed",
      "qty": 4
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    }
  ],
  "urgentcare": [
    {
      "type": "group",
      "value": "seat",
      "name": "Seat (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.FirstAidKit,
      "name": "First aid kit",
      "qty": 1
    }
  ],
  "vendingmachinebreakarea": [
    {
      "type": "item",
      "value": Item.VendingMachine,
      "name": "Vending machine",
      "qty": 1
    },
    {
      "type": "group",
      "value": "seat (wide)",
      "name": "Seat (Wide) (any)",
      "qty": 1
    }
  ],
  "vendingmachineset": [
    {
      "type": "group",
      "value": "waste bin",
      "name": "Waste bin (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.VendingMachine,
      "name": "Vending Machine",
      "qty": 1
    }
  ],
  "very-berryspace": [
    {
      "type": "item",
      "value": Item.BerryChair,
      "name": "Berry chair",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.BerryBed,
      "name": "Berry bed",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.BerryTable,
      "name": "Berry table",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.BerryTableLamp,
      "name": "Berry table lamp",
      "qty": 1
    }
  ],
  "watersidedinghy": [
    {
      "type": "item",
      "value": Item.Canoe,
      "name": "Canoe",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Duckweed,
      "name": "Duckweed",
      "qty": 2
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": "high-up location",
      "name": "High-up location (any)",
      "qty": 1
    }
  ],
  "waterwheelspot": [
    {
      "type": "group",
      "value": Item.Waterwheel,
      "name": "Waterwheel (any)",
      "qty": 1
    },
    {
      "type": "group",
      "value": "water",
      "name": "Water (any)",
      "qty": 2
    },
    {
      "type": "group",
      "value": Item.Waterfall,
      "name": "Waterfall (any)",
      "qty": 1
    }
  ],
  "welcomingresort": [
    {
      "type": "item",
      "value": Item.ResortSofa,
      "name": "Resort sofa",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ResortTable,
      "name": "Resort table",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ResortHammock,
      "name": "Resort hammock",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.ResortLight,
      "name": "Resort light",
      "qty": 1
    }
  ],
  "windyflowerbed": [
    {
      "type": "group",
      "value": "windmill",
      "name": "Windmill (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.SeashoreFlowers,
      "name": "seashore flowers",
      "qty": 4
    }
  ],
  "wingfossildisplay": [
    {
      "type": "group",
      "value": Item.Pedestal,
      "name": "Pedestal (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WingFossilHead,
      "name": "Wing fossil (head)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WingFossilBody,
      "name": "Wing fossil (body)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WingFossilLeftWing,
      "name": "Wing fossil (left wing)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WingFossilRightWing,
      "name": "Wing fossil (right wing)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.WingFossilTail,
      "name": "Wing fossil (tail)",
      "qty": 1
    }
  ],
  "workdesk": [
    {
      "type": "item",
      "value": Item.OfficeDesk,
      "name": "Office desk",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Laptop,
      "name": "Laptop",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.Mug,
      "name": "Mug",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.OfficeChair,
      "name": "Office chair",
      "qty": 1
    }
  ],
  "workingtheregister": [
    {
      "type": "group",
      "value": "table",
      "name": "Table (any)",
      "qty": 1
    },
    {
      "type": "item",
      "value": Item.CashRegister,
      "name": "Cash register",
      "qty": 1
    }
  ],
  "yellowcarpet": [
    {
      "type": "item",
      "value": Item.DandyFlowers,
      "name": "Dandy flowers",
      "qty": 4
    }
  ],
  "yellowtallgrass": [
    {
      "type": "item",
      "value": Item.YellowTallGrass,
      "name": "Yellow tall grass",
      "qty": 4
    }
  ]
} as const;
