// AUTO-GENERATED by scripts/migrate-data.ts — do not edit by hand
export const ITEM_GROUPS: Record<string, string[]> = {
  "seat": [
    "antique-chair",
    "antique-sofa",
    "beach-chair",
    "berry-chair",
    "box-sofa",
    "camping-chair",
    "chic-chair",
    "chic-sofa",
    "cute-chair",
    "cute-sofa",
    "deck-chair",
    "fancy-chair",
    "folding-chair",
    "gaming-chair",
    "garden-bench",
    "garden-chair",
    "industrial-bench",
    "industrial-chair",
    "iron-bench",
    "iron-chair",
    "log-chair",
    "luxury-chair",
    "luxury-sofa",
    "office-chair",
    "pikachu-sofa",
    "plain-chair",
    "plain-sofa",
    "plain-stool",
    "pok-eacute-ball-sofa",
    "pop-art-chair",
    "pop-art-sofa",
    "public-seat",
    "resort-chair",
    "resort-hammock",
    "resort-sofa",
    "resort-stool",
    "soft-seat",
    "spectator-chair",
    "step-stool",
    "stone-bench",
    "straw-stool",
    "stylish-stool",
    "waterproof-seat",
    "wooden-bench",
    "wooden-stool"
  ],
  "seat (wide)": [
    "antique-sofa",
    "box-sofa",
    "chic-sofa",
    "cute-sofa",
    "garden-bench",
    "industrial-bench",
    "iron-bench",
    "luxury-sofa",
    "pikachu-sofa",
    "plain-sofa",
    "pok-eacute-ball-sofa",
    "pop-art-sofa",
    "resort-hammock",
    "resort-sofa",
    "stone-bench",
    "wooden-bench"
  ],
  "bed": [
    "antique-bed",
    "berry-bed",
    "cute-bed",
    "gaming-bed",
    "guest-room-bed",
    "industrial-bed",
    "iron-bed",
    "log-bed",
    "luxury-bed",
    "mini-plain-bed",
    "naptime-bed",
    "plain-bed",
    "pok-eacute-ball-bed",
    "pop-art-bed",
    "resort-bed",
    "straw-bed",
    "wooden-bed"
  ],
  "table": [
    "antique-table",
    "berry-table",
    "chic-table",
    "counter",
    "cute-table",
    "flowery-table-setting",
    "food-counter",
    "garden-table",
    "industrial-desk",
    "iron-table",
    "kitchen-table",
    "log-table",
    "luxury-table",
    "office-desk",
    "plain-table",
    "pop-art-table",
    "resort-table",
    "side-table",
    "stone-table",
    "straw-table",
    "study-desk",
    "table-setting"
  ],
  "table (large)": [
    "antique-table",
    "garden-table",
    "iron-table",
    "kitchen-table",
    "log-table",
    "luxury-table",
    "plain-table",
    "pop-art-table",
    "resort-table",
    "stone-table",
    "straw-table"
  ],
  "lighting": [
    "antique-chandelier",
    "berry-hanging-lamp",
    "berry-table-lamp",
    "blue-meteor-lamp",
    "chic-streetlight",
    "cube-light",
    "cute-lamp",
    "desk-light",
    "double-streetlight",
    "eerie-candle",
    "fluorescent-light",
    "gaming-light",
    "garden-light",
    "green-meteor-lamp",
    "harbor-streetlight",
    "indigo-meteor-lamp",
    "lantern",
    "luxury-lamp",
    "mushroom-lamp",
    "mushroom-streetlight",
    "neon-flooring",
    "oil-lantern",
    "orange-meteor-lamp",
    "plain-lamp",
    "pok-eacute-ball-lamp",
    "pok-eacute-ball-light",
    "pop-art-lamp",
    "red-meteor-lamp",
    "resort-light",
    "seedot-lamp",
    "shell-lamp",
    "slender-candle",
    "spotlight",
    "string-lights",
    "surface-light",
    "torch",
    "town-streetlight",
    "violet-meteor-lamp",
    "wall-light",
    "wall-torch",
    "yellow-meteor-lamp"
  ],
  "streetlight": [
    "broken-streetlight",
    "chic-streetlight",
    "double-streetlight",
    "harbor-streetlight",
    "mushroom-streetlight",
    "town-streetlight"
  ],
  "dresser": [
    "antique-closet",
    "antique-dresser",
    "bookcase",
    "cute-dresser",
    "decorative-bookshelf",
    "decorative-storage-shelf",
    "dining-cabinet",
    "luxury-dresser",
    "mini-bookcase",
    "office-cabinet",
    "office-shelf",
    "plain-closet",
    "polygonal-shelf"
  ],
  "closet": [
    "antique-closet",
    "cute-dresser",
    "luxury-dresser",
    "plain-closet"
  ],
  "hedge": [
    "adorable-hedge",
    "adorable-hedge-blue",
    "adorable-hedge-orange",
    "adorable-hedge-purple",
    "adorable-hedge-red",
    "damp-hedge",
    "damp-hedge-blue",
    "damp-hedge-pink",
    "damp-hedge-red",
    "damp-hedge-white",
    "healthy-hedge",
    "healthy-hedge-orange",
    "healthy-hedge-pink",
    "healthy-hedge-purple",
    "healthy-hedge-red",
    "stylish-hedge",
    "stylish-hedge-blue",
    "stylish-hedge-orange",
    "stylish-hedge-purple",
    "stylish-hedge-white"
  ],
  "potted plant": [
    "tall-potted-plant",
    "twisted-potted-plant"
  ],
  "tall grass": [
    "dry-tall-grass",
    "pink-tall-grass",
    "red-tall-grass",
    "yellow-tall-grass"
  ],
  "tree": [
    "aspear-tree",
    "chesto-tree",
    "dry-leppa-tree",
    "large-palm-tree",
    "large-tree",
    "leppa-tree",
    "lum-tree",
    "pecha-tree",
    "pointy-tree",
    "rawst-tree"
  ],
  "large tree": [
    "large-palm-tree",
    "large-tree"
  ],
  "berry tree": [
    "aspear-tree",
    "chesto-tree",
    "leppa-tree",
    "lum-tree",
    "pecha-tree",
    "rawst-tree"
  ],
  "tree stump": [
    "tree-stump"
  ],
  "water": [
    "hot-spring-water",
    "hot-spring-spout",
    "muddy-water",
    "mystic-water",
    "ocean-water",
    "water-basin",
    "water-pillar-quarter"
  ],
  "hot-spring water": [
    "hot-spring-water",
    "hot-spring-spout"
  ],
  "ocean water": [
    "ocean-water"
  ],
  "muddy water": [
    "muddy-water"
  ],
  "lava": [
    "lava"
  ],
  "waterfall": [
    "waterfall"
  ],
  "waterwheel": [
    "waterwheel"
  ],
  "windmill": [
    "windmill"
  ],
  "pedestal": [
    "mysterious-pedestal",
    "pedestal"
  ],
  "stand": [
    "iron-stand",
    "plain-stand"
  ],
  "mirror (large)": [
    "large-mirror",
    "wall-mirror",
    "wiggly-mirror"
  ],
  "post": [
    "post",
    "signpost"
  ],
  "iron beam or column": [
    "iron-beam",
    "iron-column",
    "iron-scaffold"
  ],
  "furnace": [
    "bread-oven",
    "metallic-smelting-furnace",
    "smelting-furnace"
  ],
  "waste bin": [
    "garbage-bin",
    "nonburnable-garbage",
    "nonburnable-garbage-outdoor",
    "recycling-bin",
    "small-garbage-can"
  ],
  "garbage bags": [
    "garbage-bags"
  ],
  "cardboard boxes": [
    "cardboard-boxes"
  ],
  "doll": [
    "arcanine-doll",
    "clefairy-doll",
    "ditto-doll",
    "dragonite-doll",
    "eevee-doll",
    "pikachu-doll",
    "substitute-doll"
  ],
  "toy": [
    "arcanine-doll",
    "clefairy-doll",
    "ditto-doll",
    "dragonite-doll",
    "eevee-doll",
    "pikachu-doll",
    "substitute-doll",
    "tire-toy",
    "toy-blocks"
  ],
  "plated food": [
    "party-platter",
    "plated-food"
  ],
  "vegetables": [
    "fresh-carrot",
    "tomato"
  ],
  "vegetable field": [
    "fresh-carrot",
    "tomato"
  ],
  "canvas": [
    "blank-canvas",
    "canvas",
    "painting-landscape",
    "painting-portrait",
    "painting-still-life"
  ],
  "music mat": [
    "music-mat-fa",
    "music-mat-high-do",
    "music-mat-la",
    "music-mat-mi",
    "music-mat-re",
    "music-mat-sol",
    "music-mat-ti",
    "music-mat-low-do"
  ],
  "boo-in-the-box": [
    "boo-in-the-box"
  ],
  "castform weather charm (rain)": [
    "castform-weather-charm-rain"
  ],
  "castform weather charm (sun)": [
    "castform-weather-charm-sun"
  ]
} as const;
