import { Item } from "./consts";

// AUTO-GENERATED by scripts/migrate-data.ts — do not edit by hand
export const ITEM_GROUPS: Record<string, string[]> = {
  "seat": [
    Item.AntiqueChair,
    Item.AntiqueSofa,
    Item.BeachChair,
    Item.BerryChair,
    Item.BoxSofa,
    Item.CampingChair,
    Item.ChicChair,
    Item.ChicSofa,
    Item.CuteChair,
    Item.CuteSofa,
    Item.DeckChair,
    Item.FancyChair,
    Item.FoldingChair,
    Item.GamingChair,
    Item.GardenBench,
    Item.GardenChair,
    Item.IndustrialBench,
    Item.IndustrialChair,
    Item.IronBench,
    Item.IronChair,
    Item.LogChair,
    Item.LuxuryChair,
    Item.LuxurySofa,
    Item.OfficeChair,
    Item.PikachuSofa,
    Item.PlainChair,
    Item.PlainSofa,
    Item.PlainStool,
    Item.PokeBallSofa,
    Item.PopArtChair,
    Item.PopArtSofa,
    Item.PublicSeat,
    Item.ResortChair,
    Item.ResortHammock,
    Item.ResortSofa,
    Item.ResortStool,
    Item.SoftSeat,
    Item.SpectatorChair,
    Item.StepStool,
    Item.StoneBench,
    Item.StrawStool,
    Item.StylishStool,
    Item.WaterproofSeat,
    Item.WoodenBench,
    Item.WoodenStool
  ],
  "seat (wide)": [
    Item.AntiqueSofa,
    Item.BoxSofa,
    Item.ChicSofa,
    Item.CuteSofa,
    Item.GardenBench,
    Item.IndustrialBench,
    Item.IronBench,
    Item.LuxurySofa,
    Item.PikachuSofa,
    Item.PlainSofa,
    Item.PokeBallSofa,
    Item.PopArtSofa,
    Item.ResortHammock,
    Item.ResortSofa,
    Item.StoneBench,
    Item.WoodenBench
  ],
  "bed": [
    Item.AntiqueBed,
    Item.BerryBed,
    Item.CuteBed,
    Item.GamingBed,
    Item.GuestRoomBed,
    Item.IndustrialBed,
    Item.IronBed,
    Item.LogBed,
    Item.LuxuryBed,
    Item.MiniPlainBed,
    Item.NaptimeBed,
    Item.PlainBed,
    Item.PokeBallBed,
    Item.PopArtBed,
    Item.ResortBed,
    Item.StrawBed,
    Item.WoodenBed
  ],
  "table": [
    Item.AntiqueTable,
    Item.BerryTable,
    Item.ChicTable,
    Item.Counter,
    Item.CuteTable,
    Item.FloweryTableSetting,
    Item.FoodCounter,
    Item.GardenTable,
    Item.IndustrialDesk,
    Item.IronTable,
    Item.KitchenTable,
    Item.LogTable,
    Item.LuxuryTable,
    Item.OfficeDesk,
    Item.PlainTable,
    Item.PopArtTable,
    Item.ResortTable,
    Item.SideTable,
    Item.StoneTable,
    Item.StrawTable,
    Item.StudyDesk,
    Item.TableSetting
  ],
  "table (large)": [
    Item.AntiqueTable,
    Item.GardenTable,
    Item.IronTable,
    Item.KitchenTable,
    Item.LogTable,
    Item.LuxuryTable,
    Item.PlainTable,
    Item.PopArtTable,
    Item.ResortTable,
    Item.StoneTable,
    Item.StrawTable
  ],
  "lighting": [
    Item.AntiqueChandelier,
    Item.BerryHangingLamp,
    Item.BerryTableLamp,
    Item.BlueMeteorLamp,
    Item.ChicStreetlight,
    Item.CubeLight,
    Item.CuteLamp,
    Item.DeskLight,
    Item.DoubleStreetlight,
    Item.EerieCandle,
    Item.FluorescentLight,
    Item.GamingLight,
    Item.GardenLight,
    Item.GreenMeteorLamp,
    Item.HarborStreetlight,
    Item.IndigoMeteorLamp,
    Item.Lantern,
    Item.LuxuryLamp,
    Item.MushroomLamp,
    Item.MushroomStreetlight,
    Item.NeonFlooring,
    Item.OilLantern,
    Item.OrangeMeteorLamp,
    Item.PlainLamp,
    Item.PokeBallLamp,
    Item.PokeBallLight,
    Item.PopArtLamp,
    Item.RedMeteorLamp,
    Item.ResortLight,
    Item.SeedotLamp,
    Item.ShellLamp,
    Item.SlenderCandle,
    Item.Spotlight,
    Item.StringLights,
    Item.SurfaceLight,
    Item.Torch,
    Item.TownStreetlight,
    Item.VioletMeteorLamp,
    Item.WallLight,
    Item.WallTorch,
    Item.YellowMeteorLamp
  ],
  "streetlight": [
    Item.BrokenStreetlight,
    Item.ChicStreetlight,
    Item.DoubleStreetlight,
    Item.HarborStreetlight,
    Item.MushroomStreetlight,
    Item.TownStreetlight
  ],
  "dresser": [
    Item.AntiqueCloset,
    Item.AntiqueDresser,
    Item.Bookcase,
    Item.CuteDresser,
    Item.DecorativeBookshelf,
    Item.DecorativeStorageShelf,
    Item.DiningCabinet,
    Item.LuxuryDresser,
    Item.MiniBookcase,
    Item.OfficeCabinet,
    Item.OfficeShelf,
    Item.PlainCloset,
    Item.PolygonalShelf
  ],
  "closet": [
    Item.AntiqueCloset,
    Item.CuteDresser,
    Item.LuxuryDresser,
    Item.PlainCloset
  ],
  "hedge": [
    Item.AdorableHedge,
    Item.AdorableHedgeBlue,
    Item.AdorableHedgeOrange,
    Item.AdorableHedgePurple,
    Item.AdorableHedgeRed,
    Item.DampHedge,
    Item.DampHedgeBlue,
    Item.DampHedgePink,
    Item.DampHedgeRed,
    Item.DampHedgeWhite,
    Item.HealthyHedge,
    Item.HealthyHedgeOrange,
    Item.HealthyHedgePink,
    Item.HealthyHedgePurple,
    Item.HealthyHedgeRed,
    Item.StylishHedge,
    Item.StylishHedgeBlue,
    Item.StylishHedgeOrange,
    Item.StylishHedgePurple,
    Item.StylishHedgeWhite
  ],
  "potted plant": [
    Item.TallPottedPlant,
    Item.TwistedPottedPlant
  ],
  "tall grass": [
    Item.DryTallGrass,
    Item.PinkTallGrass,
    Item.RedTallGrass,
    Item.YellowTallGrass
  ],
  "tree": [
    Item.AspearTree,
    Item.ChestoTree,
    Item.DryLeppaTree,
    Item.LargePalmTree,
    Item.LargeTree,
    Item.LeppaTree,
    Item.LumTree,
    Item.PechaTree,
    Item.PointyTree,
    Item.RawstTree
  ],
  "large tree": [
    Item.LargePalmTree,
    Item.LargeTree
  ],
  "berry tree": [
    Item.AspearTree,
    Item.ChestoTree,
    Item.LeppaTree,
    Item.LumTree,
    Item.PechaTree,
    Item.RawstTree
  ],
  "tree stump": [
    "tree-stump"
  ],
  "water": [
    Item.HotSpringWater,
    Item.HotSpringSpout,
    Item.MuddyWater,
    Item.MysticWater,
    Item.OceanWater,
    Item.WaterBasin,
    Item.WaterPillarQuarter
  ],
  "hot-spring water": [
    Item.HotSpringWater,
    Item.HotSpringSpout
  ],
  "ocean water": [
    Item.OceanWater
  ],
  "muddy water": [
    Item.MuddyWater
  ],
  "lava": [
    Item.Lava
  ],
  "waterfall": [
    Item.Waterfall
  ],
  "waterwheel": [
    Item.Waterwheel
  ],
  "windmill": [
    "windmill"
  ],
  "pedestal": [
    Item.MysteriousPedestal,
    Item.Pedestal
  ],
  "stand": [
    Item.IronStand,
    Item.PlainStand
  ],
  "mirror (large)": [
    Item.LargeMirror,
    Item.WallMirror,
    Item.WigglyMirror
  ],
  "post": [
    Item.Post,
    Item.Signpost
  ],
  "iron beam or column": [
    Item.IronBeam,
    Item.IronColumn,
    Item.IronScaffold
  ],
  "furnace": [
    Item.BreadOven,
    Item.MetallicSmeltingFurnace,
    Item.SmeltingFurnace
  ],
  "waste bin": [
    Item.GarbageBin,
    Item.NonburnableGarbage,
    Item.NonburnableGarbageOutdoor,
    Item.RecyclingBin,
    Item.SmallGarbageCan
  ],
  "garbage bags": [
    Item.GarbageBags
  ],
  "cardboard boxes": [
    Item.CardboardBoxes
  ],
  "doll": [
    Item.ArcanineDoll,
    Item.ClefairyDoll,
    Item.DittoDoll,
    Item.DragoniteDoll,
    Item.EeveeDoll,
    Item.PikachuDoll,
    Item.SubstituteDoll
  ],
  "toy": [
    Item.ArcanineDoll,
    Item.ClefairyDoll,
    Item.DittoDoll,
    Item.DragoniteDoll,
    Item.EeveeDoll,
    Item.PikachuDoll,
    Item.SubstituteDoll,
    Item.TireToy,
    Item.ToyBlocks
  ],
  "plated food": [
    Item.PartyPlatter,
    Item.PlatedFood
  ],
  "vegetables": [
    Item.FreshCarrot,
    Item.Tomato
  ],
  "vegetable field": [
    Item.FreshCarrot,
    Item.Tomato
  ],
  "canvas": [
    Item.BlankCanvas,
    Item.Canvas,
    Item.PaintingLandscape,
    Item.PaintingPortrait,
    Item.PaintingStillLife
  ],
  "music mat": [
    Item.MusicMatFa,
    Item.MusicMatHighDo,
    Item.MusicMatLa,
    Item.MusicMatMi,
    Item.MusicMatRe,
    Item.MusicMatSol,
    Item.MusicMatTi,
    Item.MusicMatLowDo
  ],
  "boo-in-the-box": [
    Item.BooInTheBox
  ],
  "castform weather charm (rain)": [
    Item.CastformWeatherCharmRain
  ],
  "castform weather charm (sun)": [
    Item.CastformWeatherCharmSun
  ]
} as const;
