// AUTO-GENERATED by scripts/migrate-data.ts — do not edit by hand
import type { LocationEntry } from "../types";
import { Item } from "./consts";

export const LOCATIONS: Record<string, LocationEntry> = {
  "witheredwastelands": {
    "slug": "witheredwastelands",
    "name": "Withered Wastelands",
    "description": "The Withered Wastelands are a collection of grassy areas and caves alongside a coast that make up what used to be Fuchsia City and its surrounding area. Your task here is to get the area to rain, as rain hasn't fallen here for some time",
    "objective": "",
    "materials": [
      Item.SturdyStick,
      Item.Stone,
      Item.Leaf,
      Item.FreshCarrot,
      Item.SmallLog,
      Item.LeppaBerry,
      Item.ChestoBerry,
      Item.RawstBerry,
      Item.LumBerry,
      Item.PechaBerry,
      Item.AspearBerry,
      Item.Honey,
      Item.Vine,
      Item.DryVine,
      Item.VineRope,
      Item.MossyStone,
      Item.GlowingMushrooms,
      Item.SquishyClay,
      Item.CopperOre,
      Item.GoldOre,
      Item.PokemetalFragment
    ],
    "blocksAndPlants": [
      "tall-grass",
      Item.Moss,
      Item.Wildflowers,
      Item.WildflowersOrange,
      Item.WildflowersPurple,
      Item.WildflowersRed,
      Item.WildflowersBlue,
      Item.BeautifulFlower,
      Item.BeautifulFlowerPink,
      Item.BeautifulFlowerPurple,
      Item.BeautifulFlowerWhite,
      Item.BeautifulFlowerYellow,
      Item.AdorableHedge,
      Item.AdorableHedgeBlue,
      Item.AdorableHedgeOrange,
      Item.AdorableHedgePurple,
      Item.AdorableHedgeRed,
      Item.GreenShoots,
      Item.DryGreenShoots,
      Item.LeppaTree,
      Item.ChestoTree,
      Item.RawstTree,
      Item.LumTree,
      Item.AspearTree,
      Item.PechaTree,
      Item.FieldGrass,
      Item.OrdinarySoil,
      Item.DryTallGrass,
      Item.DryLeppaTree,
      Item.DryFieldGrass,
      Item.BarrenOrdinarySoil,
      Item.DryWildflowers,
      Item.CliffRock,
      Item.SpottedCliffRock,
      Item.WhiteRock,
      Item.OrdinarySand,
      Item.OceanRock,
      Item.CaveRock,
      Item.Sandstone,
      Item.Gravel,
      Item.MossySoil,
      Item.HayPile,
      Item.WoodenWall,
      Item.AgedStoneWall,
      Item.PatternedAgedStoneWall,
      Item.GoldWall,
      Item.StylishGoldWall,
      Item.WarningWall,
      Item.StoneFlooring,
      Item.StonePillarLower,
      Item.StonePillarMiddle,
      Item.StonePillarUpper,
      Item.IronPlateFlooring,
      Item.CobblestoneWall,
      Item.PlasterWall,
      Item.WoodenPillarLower,
      Item.WoodenPillarMiddle,
      Item.WoodenPillarUpper,
      Item.StylishStoneFlooring,
      Item.Levee,
      Item.DamagedStoneFlooring,
      Item.RustedIronPlateFlooring,
      Item.RustedWall,
      Item.IronTiling,
      Item.NeonFlooring,
      Item.CyberFlooring,
      Item.HexagonalFlooring,
      Item.WoodenFlooring,
      Item.ConcreteWall,
      Item.ArchedTiling,
      Item.CrackedSandstone,
      Item.CopperDepositWasteland,
      Item.GoldDeposit,
      Item.PokemetalDeposit
    ],
    "itemsInArea": [
      "workbench",
      "professor-s-treasure-trove",
      Item.StrawBed,
      Item.StorageBox,
      "wooden-steps",
      "wooden-fencing",
      Item.HorseaFountain,
      Item.WoodenBench,
      Item.Gravestone,
      "wooden-table",
      Item.BrokenStreetlight,
      "sloped-tile-roof",
      "tiled-hipped-roof",
      "flat-tiled-roof",
      "hatch-window",
      Item.PlainBed,
      Item.PlainChair,
      Item.LargeMirror,
      "wooden-siding-panel",
      Item.StoneSteps,
      Item.IronSteps,
      Item.IronScaffold,
      Item.WallTorch,
      Item.WornWoodenCrate,
      Item.Sandbags,
      Item.MetalDrum,
      "grate-fencing",
      Item.RailwayTrack,
      Item.Lantern,
      Item.ExcavationTools,
      Item.IronLadder,
      "wooden-ladder",
      Item.Counter,
      Item.PlainChest,
      Item.CDRack,
      Item.GlassWindow,
      Item.Sign,
      Item.VendingMachine,
      Item.TownStreetlight,
      Item.PunchingBag,
      Item.Walkway,
      "bridge-planks",
      "harbor-pole",
      Item.TeamRocketWallHanging,
      Item.WallMonitor,
      Item.JumbledCords,
      Item.ControlUnit,
      "iron-pipe-upward-curve",
      "iron-pipe-downward-curve",
      "iron-pipe-horizontal",
      Item.PokeBallLamp,
      "stylish-door",
      Item.IronChair,
      Item.IronTable,
      Item.OfficeDesk,
      Item.CardboardBoxes,
      Item.IronRack,
      Item.IronBed,
      Item.GarbageBags,
      Item.TallPottedPlant,
      Item.OfficeCabinet,
      "poke-ball-doormat",
      Item.TownMap
    ],
    "itemsInPokeballs": [
      "adorable-hedge-seeds",
      Item.ArchedTiling,
      "bridge-planks-recipe",
      "community-box",
      Item.DowsingMachine,
      Item.FirstAidKit,
      Item.HayPile,
      "mushroom-streetlight-recipe",
      "pink-hut-kit",
      Item.Pokemetal,
      Item.RowletClock,
      "rustic-door-recipe",
      Item.SecurityCamera,
      Item.SmoothRock,
      Item.StorageBox,
      "straw-bed-recipe",
      "straw-table-recipe",
      Item.Torch,
      Item.VineRope,
      "water-basin-recipe",
      "wooden-bed-recipe"
    ],
    "treasure": [
      Item.LargeLostRelic,
      Item.SmallLostRelic,
      Item.PikachuDoll,
      Item.EeveeDoll,
      Item.DittoDoll,
      Item.SubstituteDoll,
      Item.ShieldFossilHead,
      Item.ShieldFossilBody,
      Item.ShieldFossilTail,
      Item.ArmorFossil,
      Item.WingFossilHead,
      Item.WingFossilRightWing,
      Item.WingFossilLeftWing,
      Item.WingFossilBody,
      Item.WingFossilTail,
      Item.StrangeStrings,
      Item.ArmorFragment
    ],
    "shopItems": [
      {
        "slug": Item.GardenBench,
        "name": "Garden bench",
        "level": 2
      },
      {
        "slug": "leaf-hut-kit",
        "name": "Leaf hut kit",
        "level": 2
      },
      {
        "slug": Item.LogBed,
        "name": "Log bed",
        "level": 2
      },
      {
        "slug": Item.Mug,
        "name": "Mug",
        "level": 2
      },
      {
        "slug": "mysterious-goggles",
        "name": "Mysterious goggles",
        "level": 2
      },
      {
        "slug": Item.SlenderCandle,
        "name": "Slender candle",
        "level": 2
      },
      {
        "slug": "wooden-chair",
        "name": "Wooden chair",
        "level": 2
      },
      {
        "slug": "workbench-recipe",
        "name": "Workbench Recipe",
        "level": 2
      },
      {
        "slug": Item.CastformWeatherCharm,
        "name": "Castform weather charm",
        "level": 3
      },
      {
        "slug": "handy-bag",
        "name": "Handy bag",
        "level": 3
      },
      {
        "slug": Item.HorseaFountain,
        "name": "Horsea fountain",
        "level": 3
      },
      {
        "slug": "leaf-den-kit",
        "name": "Leaf den kit",
        "level": 3
      },
      {
        "slug": Item.SecurityCamera,
        "name": "Security camera",
        "level": 3
      },
      {
        "slug": Item.ToyBlocks,
        "name": "Toy blocks",
        "level": 3
      },
      {
        "slug": "tripod",
        "name": "Tripod",
        "level": 3
      },
      {
        "slug": Item.TwistedPottedPlant,
        "name": "Twisted potted plant",
        "level": 3
      },
      {
        "slug": Item.WaterBasin,
        "name": "Water basin",
        "level": 3
      },
      {
        "slug": Item.WoodenBed,
        "name": "Wooden bed",
        "level": 3
      },
      {
        "slug": "arched-tiling-recipe",
        "name": "Arched tiling Recipe",
        "level": 3
      },
      {
        "slug": "hay-pile-recipe",
        "name": "Hay pile Recipe",
        "level": 3
      },
      {
        "slug": "wooden-fencing-recipe",
        "name": "Wooden fencing Recipe",
        "level": 3
      },
      {
        "slug": "wooden-gate-recipe",
        "name": "Wooden gate Recipe",
        "level": 3
      },
      {
        "slug": Item.Cart,
        "name": "Cart",
        "level": 4
      },
      {
        "slug": "leaf-cottage-kit",
        "name": "Leaf cottage kit",
        "level": 4
      },
      {
        "slug": Item.MushroomStreetlight,
        "name": "Mushroom streetlight",
        "level": 4
      },
      {
        "slug": "pp-up",
        "name": "PP Up",
        "level": 4
      },
      {
        "slug": "berry-basket-recipe",
        "name": "Berry basket Recipe",
        "level": 4
      },
      {
        "slug": "community-box-recipe",
        "name": "Community box Recipe",
        "level": 4
      },
      {
        "slug": "house-partition-recipe",
        "name": "House partition Recipe",
        "level": 4
      },
      {
        "slug": "wooden-ladder-recipe",
        "name": "Wooden ladder Recipe",
        "level": 4
      },
      {
        "slug": Item.Bonfire,
        "name": "Bonfire",
        "level": 5
      },
      {
        "slug": "leaf-house-kit",
        "name": "Leaf house kit",
        "level": 5
      },
      {
        "slug": "pink-hut-kit",
        "name": "Pink hut kit",
        "level": 5
      },
      {
        "slug": "flat-tiled-roof-recipe",
        "name": "Flat tiled roof Recipe",
        "level": 5
      },
      {
        "slug": "hatch-window-recipe",
        "name": "Hatch window Recipe",
        "level": 5
      },
      {
        "slug": "magikarp-decoration-recipe",
        "name": "Magikarp decoration Recipe",
        "level": 5
      },
      {
        "slug": "party-popper-recipe",
        "name": "Party popper Recipe",
        "level": 5
      },
      {
        "slug": "sloped-tiled-roof-recipe",
        "name": "Sloped tiled roof Recipe",
        "level": 5
      },
      {
        "slug": "tiled-hipped-roof-recipe",
        "name": "Tiled hipped roof Recipe",
        "level": 5
      },
      {
        "slug": "tiled-roof-decoration-recipe",
        "name": "Tiled roof decoration Recipe",
        "level": 5
      },
      {
        "slug": "tiled-roof-valley-recipe",
        "name": "Tiled roof valley Recipe",
        "level": 5
      },
      {
        "slug": "underground-hatch-recipe",
        "name": "Underground hatch Recipe",
        "level": 5
      },
      {
        "slug": Item.Pokemetal,
        "name": "Pokemetal",
        "level": 6
      },
      {
        "slug": Item.WallMirror,
        "name": "Wall mirror",
        "level": 6
      },
      {
        "slug": "diagonal-wooden-flooring-recipe",
        "name": "Diagonal wooden flooring Recipe",
        "level": 6
      },
      {
        "slug": "floor-switch-recipe",
        "name": "Floor switch Recipe",
        "level": 6
      },
      {
        "slug": "garden-light-recipe",
        "name": "Garden light Recipe",
        "level": 6
      },
      {
        "slug": "wall-mirror-recipe",
        "name": "Wall Mirror Recipe",
        "level": 6
      },
      {
        "slug": Item.RarePokemetal,
        "name": "Rare Pokemetal",
        "level": 7
      },
      {
        "slug": "ditto-rug-recipe",
        "name": "Ditto rug Recipe",
        "level": 7
      },
      {
        "slug": "garden-bench-recipe",
        "name": "Garden bench Recipe",
        "level": 7
      },
      {
        "slug": "garden-chair-recipe",
        "name": "Garden chair Recipe",
        "level": 7
      },
      {
        "slug": "painted-wall-recipe",
        "name": "Painted wall Recipe",
        "level": 7
      },
      {
        "slug": "relaxing-park-kit",
        "name": "Relaxing park kit",
        "level": 8
      },
      {
        "slug": "garden-flowers-recipe",
        "name": "Garden flowers Recipe",
        "level": 8
      },
      {
        "slug": "garden-table-recipe",
        "name": "Garden table Recipe",
        "level": 8
      },
      {
        "slug": "simple-flooring-recipe",
        "name": "Simple flooring Recipe",
        "level": 8
      },
      {
        "slug": "berry-chair-recipe",
        "name": "Berry chair Recipe",
        "level": 9
      },
      {
        "slug": "berry-table-lamp-recipe",
        "name": "Berry table lamp Recipe",
        "level": 9
      },
      {
        "slug": "modern-wall-recipe",
        "name": "Modern wall Recipe",
        "level": 9
      },
      {
        "slug": "berry-bed-recipe",
        "name": "Berry bed Recipe",
        "level": 10
      },
      {
        "slug": "berry-hanging-lamp-recipe",
        "name": "Berry hanging lamp Recipe",
        "level": 10
      },
      {
        "slug": "berry-table-recipe",
        "name": "Berry table Recipe",
        "level": 10
      },
      {
        "slug": "berry-wall-decoration-recipe",
        "name": "Berry wall decoration Recipe",
        "level": 10
      },
      {
        "slug": "polka-dot-print-recipe",
        "name": "Polka-dot print Recipe",
        "level": 10
      }
    ]
  },
  "bleakbeach": {
    "slug": "bleakbeach",
    "name": "Bleak Beach",
    "description": "Bleak Beach is the area that used to be Vermilion City. Here, the land is overcome in darkness no matter the time of day and you have to find a way to bring light to the area.In addition to Vermilion City, it also includes the SS Anne",
    "objective": "",
    "materials": [
      Item.SturdyStick,
      Item.Stone,
      Item.Leaf,
      Item.SquishyClay,
      Item.NonburnableGarbage,
      Item.SmallLog,
      Item.Seashell,
      Item.Twine,
      Item.SeaGlassFragments,
      Item.Vine,
      Item.VineRope,
      Item.Honey,
      Item.Seaweed,
      Item.LeppaBerry
    ],
    "blocksAndPlants": [
      Item.YellowTallGrass,
      Item.Moss,
      Item.SeashoreFlowers,
      Item.SeashoreFlowersBlue,
      Item.SeashoreFlowersOrange,
      Item.SeashoreFlowersWhite,
      Item.SeashoreFlowersYellow,
      Item.CuteFlower,
      Item.YellowGreenShoots,
      Item.DryYellowGreenShoots,
      Item.HealthyHedge,
      Item.HealthyHedgeOrange,
      Item.HealthyHedgePink,
      Item.HealthyHedgePurple,
      Item.HealthyHedgeRed,
      Item.Driftwood,
      Item.LargePalmTree,
      Item.LeppaTree,
      Item.ChestoTree,
      Item.RawstTree,
      Item.LumTree,
      Item.AspearTree,
      Item.PechaTree,
      Item.SeashoreGrass,
      Item.SeashellSoil,
      Item.BeachSand,
      Item.BumpyBeachSand,
      Item.RedCliffRock,
      Item.RedSpottedCliffRock,
      Item.LightBrownRock,
      Item.OceanRock,
      Item.CaveRock,
      Item.WhiteRock,
      Item.Clay,
      Item.SquareTiling,
      Item.DamagedSquareTiling,
      Item.MosaicTiling,
      Item.Mud,
      Item.MuddyTiling,
      Item.MuddySand,
      Item.MuddySeashellSoil,
      Item.BrickWall,
      Item.Foundation,
      Item.SimpleSquareTiling,
      Item.UprightLog,
      Item.SidewaysLog,
      Item.DiagonalWoodenFlooring,
      Item.CrisscrossWoodenFlooring,
      Item.Levee,
      Item.RustedWall,
      Item.RustedIronPlateFlooring,
      Item.IronPlateFlooring,
      Item.IronPlating,
      Item.IronBeam,
      Item.IronColumn,
      Item.GrayCircleFlooring,
      Item.StonePillarLower,
      Item.StylishBrickWallLower,
      Item.StylishBrickWallMiddle,
      Item.StylishBrickWallUpper,
      Item.StoneFlooring,
      Item.LargeBoulder,
      Item.PlasterWall,
      Item.MossySoil,
      Item.ArchBridge,
      Item.StoneBrickWall,
      Item.IronTiling,
      Item.MossyBoulder,
      Item.WoodenFlooring,
      Item.DamagedWoodenFlooring,
      Item.SoftCarpeting,
      Item.ExtravagantCarpeting,
      Item.Marble,
      Item.ClothWall,
      Item.GuestRoomWall,
      Item.ModernCarpeting,
      Item.LightWoodenWall,
      Item.WoodenPillarUpper,
      Item.WoodenPillarLower,
      Item.CubeLight,
      Item.DamagedStoneFlooring,
      Item.CrackedSandstone,
      Item.CopperDepositBeach
    ],
    "itemsInArea": [
      "workbench",
      Item.GarbageBin,
      Item.GarbageBags,
      Item.MetalDrum,
      "harbor-pole",
      Item.HarborStreetlight,
      Item.BrokenStreetlight,
      "wooden-fencing",
      Item.Walkway,
      "bridge-planks",
      "grate-flooring",
      Item.WallTorch,
      Item.Torch,
      Item.UtilityPole,
      "pitched-brick-roof",
      "brick-hipped-roof",
      Item.GlassWindow,
      Item.StoneSteps,
      "dormered-brick-roof",
      "flat-brick-roof",
      Item.PikachuDoll,
      Item.EeveeDoll,
      Item.PlainStool,
      Item.PlainTable,
      Item.KnittingSupplies,
      "arched-barrier",
      "wooden-enclosure",
      Item.WornWoodenCrate,
      Item.VendingMachine,
      Item.HorseaFountain,
      Item.Shower,
      "wooden-siding-panel",
      Item.Sign,
      Item.WoodenBench,
      "large-wooden-door",
      Item.BerryHangingLamp,
      Item.StylishStool,
      Item.ResortSofa,
      Item.ResortTable,
      Item.PaintingLandscape,
      Item.LargeMirror,
      Item.PlainCloset,
      Item.SideTable,
      Item.Campfire,
      Item.BeachParasol,
      Item.BeachChair,
      Item.CashRegister,
      Item.Counter,
      Item.WoodenStool,
      "wooden-table",
      "plate",
      Item.CookingStove,
      Item.ModernSink,
      Item.WallCalendar,
      Item.CDRack,
      "wooden-steps",
      Item.DeckChair,
      Item.Sandbags,
      Item.TownStreetlight,
      Item.WoodenPath,
      "wooden-gate",
      Item.WallLight,
      Item.Barrel,
      Item.ShipsWheel,
      Item.Mug,
      Item.WoodenCrate,
      "handrail",
      Item.AntiqueChest,
      Item.Sink,
      Item.TowelRack,
      Item.PlainBed,
      "boat-door",
      "wall-mounted-table",
      "simple-curtain-left",
      "simple-curtain-right",
      Item.Bathtub,
      Item.ChicSofa,
      Item.WallMonitor,
      Item.Television,
      Item.SmallGarbageCan,
      Item.GuestRoomBed,
      Item.PlainChest,
      Item.TwistedPottedPlant,
      Item.ShellLamp,
      Item.Balloons,
      Item.AntiqueChandelier,
      Item.LuxuryLamp,
      "boat-railing",
      Item.IronLadder,
      Item.OfficeShelf,
      Item.OfficeDesk,
      Item.OfficeChair,
      Item.IronBed,
      Item.MirrorBall,
      Item.RecyclingBin,
      Item.LuxurySofa,
      Item.LuxuryTable,
      Item.CardboardBoxes,
      Item.IronDoor,
      Item.SmallVase,
      Item.PushCart,
      Item.ChicChair,
      Item.ChicTable,
      Item.IronRack,
      "iron-pipe-upward-curve",
      "iron-pipe-vertical",
      "iron-pipe-downward-curve",
      "iron-pipe-vertical-t",
      "iron-pipe-horizontal",
      Item.MenuBoard,
      Item.IronSteps,
      Item.Spotlight,
      "poke-ball-doormat",
      Item.TownMap
    ],
    "itemsInPokeballs": [
      "alarm-clock-recipe",
      Item.BrickWall,
      "bridge-planks-recipe",
      Item.CashRegister,
      Item.CeilingFan,
      "chestoseeds",
      Item.Fan,
      "garbage-bin-recipe",
      "healthy-hedge-seeds",
      Item.MunnaBank,
      Item.PikachuSofa,
      "plain-bed-recipe",
      "plain-chair-recipe",
      Item.PlainCloset,
      "plain-table-recipe",
      Item.Pokemetal,
      "resort-light-recipe",
      Item.ResortTable,
      "rustic-door",
      "sandbox-recipe",
      "ship-s-wheel-recipe",
      "slowpoke-rug",
      Item.SmallStage,
      "spotlight-recipe",
      "square-tiling-recipe",
      Item.UtilityPole,
      "utility-pole-recipe",
      "walkway-recipe"
    ],
    "treasure": [
      Item.LargeLostRelic,
      Item.SmallLostRelic,
      Item.ClefairyDoll,
      Item.DittoDoll,
      Item.SubstituteDoll,
      Item.TundraFossilHead,
      Item.TundraFossilBody,
      Item.TundraFossilTail,
      Item.SailFossil,
      Item.WingFossilHead,
      Item.WingFossilRightWing,
      Item.WingFossilLeftWing,
      Item.WingFossilBody,
      Item.WingFossilTail,
      Item.StrangeStrings,
      Item.ArmorFragment
    ],
    "shopItems": [
      {
        "slug": Item.BeachChair,
        "name": "Beach chair",
        "level": 2
      },
      {
        "slug": Item.BeachParasol,
        "name": "Beach parasol",
        "level": 2
      },
      {
        "slug": Item.DeskLight,
        "name": "Desk light",
        "level": 2
      },
      {
        "slug": "sand-den-kit",
        "name": "Sand den kit",
        "level": 2
      },
      {
        "slug": Item.TireToy,
        "name": "Tire toy",
        "level": 2
      },
      {
        "slug": Item.WoodenBirdhouse,
        "name": "Wooden birdhouse",
        "level": 2
      },
      {
        "slug": "brick-steps-recipe",
        "name": "Brick steps Recipe",
        "level": 2
      },
      {
        "slug": "cash-register-recipe",
        "name": "Cash register Recipe",
        "level": 2
      },
      {
        "slug": "plate-recipe",
        "name": "Plate Recipe",
        "level": 2
      },
      {
        "slug": Item.FirstAidKit,
        "name": "First aid kit",
        "level": 3
      },
      {
        "slug": Item.KnittingSupplies,
        "name": "Knitting supplies",
        "level": 3
      },
      {
        "slug": "sand-hut-kit",
        "name": "Sand hut kit",
        "level": 3
      },
      {
        "slug": "harbor-streetlight-recipe",
        "name": "Harbor streetlight Recipe",
        "level": 3
      },
      {
        "slug": "plain-sofa-recipe",
        "name": "Plain sofa Recipe",
        "level": 3
      },
      {
        "slug": "pikachu-fountain-kit",
        "name": "Pikachu fountain kit",
        "level": 4
      },
      {
        "slug": Item.PlainCloset,
        "name": "Plain closet",
        "level": 4
      },
      {
        "slug": Item.PlainStand,
        "name": "Plain stand",
        "level": 4
      },
      {
        "slug": "sand-cottage-kit",
        "name": "Sand cottage kit",
        "level": 4
      },
      {
        "slug": "boat-railing-recipe",
        "name": "Boat railing Recipe",
        "level": 4
      },
      {
        "slug": "brick-wall-recipe",
        "name": "Brick wall Recipe",
        "level": 4
      },
      {
        "slug": "grate-flooring-recipe",
        "name": "Grate flooring Recipe",
        "level": 4
      },
      {
        "slug": "plain-lamp-recipe",
        "name": "Plain lamp Recipe",
        "level": 4
      },
      {
        "slug": "mini-floodgate",
        "name": "Mini floodgate",
        "level": 5
      },
      {
        "slug": "orange-hut-kit",
        "name": "Orange hut kit",
        "level": 5
      },
      {
        "slug": "sand-house-kit",
        "name": "Sand house kit",
        "level": 5
      },
      {
        "slug": Item.SashWindow,
        "name": "Sash window",
        "level": 5
      },
      {
        "slug": Item.WashingMachine,
        "name": "Washing Machine",
        "level": 5
      },
      {
        "slug": "brick-hipped-roof-recipe",
        "name": "Brick hipped roof Recipe",
        "level": 5
      },
      {
        "slug": "brick-roof-decoration-recipe",
        "name": "Brick roof decoration Recipe",
        "level": 5
      },
      {
        "slug": "brick-roof-valley-recipe",
        "name": "Brick roof valley Recipe",
        "level": 5
      },
      {
        "slug": "dormered-brick-roof-recipe",
        "name": "Dormered brick roof Recipe",
        "level": 5
      },
      {
        "slug": "flat-brick-roof-recipe",
        "name": "Flat brick roof Recipe",
        "level": 5
      },
      {
        "slug": "modern-door-recipe",
        "name": "Modern door Recipe",
        "level": 5
      },
      {
        "slug": "pitched-brick-roof-recipe",
        "name": "Pitched brick roof Recipe",
        "level": 5
      },
      {
        "slug": "plaster-wall-recipe",
        "name": "Plaster wall Recipe",
        "level": 5
      },
      {
        "slug": "sash-window-recipe",
        "name": "Sash window Recipe",
        "level": 5
      },
      {
        "slug": "washing-machine-recipe",
        "name": "Washing Machine Recipe",
        "level": 5
      },
      {
        "slug": Item.Pokemetal,
        "name": "Pokemetal",
        "level": 6
      },
      {
        "slug": "brick-border-line-recipe",
        "name": "Brick border (line) Recipe",
        "level": 6
      },
      {
        "slug": "resort-hammock-recipe",
        "name": "Resort hammock Recipe",
        "level": 6
      },
      {
        "slug": "resort-stool-recipe",
        "name": "Resort stool Recipe",
        "level": 6
      },
      {
        "slug": "soft-carpeting-recipe",
        "name": "Soft carpeting Recipe",
        "level": 6
      },
      {
        "slug": "wall-switch-recipe",
        "name": "Wall switch Recipe",
        "level": 6
      },
      {
        "slug": Item.RarePokemetal,
        "name": "Rare Pokemetal",
        "level": 7
      },
      {
        "slug": "brick-border-single-recipe",
        "name": "Brick border (single) Recipe",
        "level": 7
      },
      {
        "slug": "cloth-wall-recipe",
        "name": "Cloth wall Recipe",
        "level": 7
      },
      {
        "slug": "poke-ball-mat-recipe",
        "name": "Poke Ball mat Recipe",
        "level": 7
      },
      {
        "slug": "resort-chair-recipe",
        "name": "Resort chair Recipe",
        "level": 7
      },
      {
        "slug": "resort-sofa-recipe",
        "name": "Resort sofa Recipe",
        "level": 7
      },
      {
        "slug": "stylish-cafe-kit",
        "name": "Stylish cafe kit",
        "level": 8
      },
      {
        "slug": "brick-border-corner-recipe",
        "name": "Brick border (corner) Recipe",
        "level": 8
      },
      {
        "slug": "levee-recipe",
        "name": "Levee Recipe",
        "level": 8
      },
      {
        "slug": "resort-bed-recipe",
        "name": "Resort bed Recipe",
        "level": 8
      },
      {
        "slug": "resort-table-recipe",
        "name": "Resort table Recipe",
        "level": 8
      },
      {
        "slug": Item.InflatableBoat,
        "name": "Inflatable boat",
        "level": 9
      },
      {
        "slug": Item.PikachuSofa,
        "name": "Pikachu sofa",
        "level": 9
      },
      {
        "slug": "cute-chair-recipe",
        "name": "Cute chair Recipe",
        "level": 9
      },
      {
        "slug": "cute-lamp-recipe",
        "name": "Cute lamp Recipe",
        "level": 9
      },
      {
        "slug": "starry-sky-wall-recipe",
        "name": "Starry-sky wall Recipe",
        "level": 9
      },
      {
        "slug": "beach-pokemon-center-kit",
        "name": "Beach Pokemon Center Kit",
        "level": 10
      },
      {
        "slug": "wasteland-pokemon-center-kit",
        "name": "Wasteland Pokemon Center kit",
        "level": 10
      },
      {
        "slug": "cute-bed-recipe",
        "name": "Cute bed Recipe",
        "level": 10
      },
      {
        "slug": "cute-dresser-recipe",
        "name": "Cute dresser Recipe",
        "level": 10
      },
      {
        "slug": "cute-sofa-recipe",
        "name": "Cute sofa Recipe",
        "level": 10
      },
      {
        "slug": "cute-table-recipe",
        "name": "Cute table Recipe",
        "level": 10
      },
      {
        "slug": "gingham-print-recipe",
        "name": "Gingham print Recipe",
        "level": 10
      }
    ]
  },
  "rockyridges": {
    "slug": "rockyridges",
    "name": "Rocky Ridges",
    "description": "Rocky Ridges makees up the area that used to be Pewter City and Mt. Moon, and includes a mine going deep underground into the muntain. Within the mountains is what used to be Pewter Museum including the exhibits.This area featurs a focus on ore for you to find",
    "objective": "",
    "materials": [
      Item.SturdyStick,
      Item.Stone,
      Item.Leaf,
      Item.CopperOre,
      Item.IronOre,
      Item.GoldOre,
      Item.PokemetalFragment,
      Item.RarePokemetalFragment,
      Item.LeppaBerry,
      Item.Wheat,
      Item.Bean,
      Item.CaveMushrooms,
      Item.GlowingMushrooms,
      Item.Lumber,
      Item.MossyStone,
      Item.Vine,
      Item.VineRope
    ],
    "blocksAndPlants": [
      Item.RedTallGrass,
      Item.MountainFlowers,
      Item.MountainFlowersPink,
      Item.MountainFlowersPurple,
      Item.MountainFlowersRed,
      Item.MountainFlowersWhite,
      Item.ElegantFlower,
      Item.ElegantFlowerOrange,
      Item.ElegantFlowerPink,
      Item.ElegantFlowerRed,
      Item.ElegantFlowerYellow,
      Item.VerdantShoots,
      Item.DryVerdantShoots,
      Item.Fern,
      Item.LeppaTree,
      Item.ChestoTree,
      Item.RawstTree,
      Item.LumTree,
      Item.AspearTree,
      Item.PechaTree,
      Item.RipeBeanPlant,
      Item.RipeWheat,
      Item.PointyTree,
      Item.DampHedge,
      Item.DampHedgeBlue,
      Item.DampHedgePink,
      Item.DampHedgeRed,
      Item.DampHedgeWhite,
      Item.SquarePlant,
      Item.LargeBoulder,
      Item.MossyBoulder,
      Item.MoltenRock,
      Item.CooledMoltenRock,
      Item.Stalagmites,
      Item.Stalactites,
      Item.CrystalCluster,
      Item.StickyWeb,
      Item.StrengthRock,
      Item.Vine,
      Item.StoneDebris,
      Item.AlpineGrass,
      Item.StripedSoil,
      Item.BlackRock,
      Item.LavaRock,
      Item.CaveRock,
      Item.BlackCliffRock,
      Item.BlackSpottedCliffRock,
      Item.VolcanicAsh,
      Item.BarrenStripedSoil,
      Item.YellowRock,
      Item.CarvedRedRock,
      Item.CarvedYellowRock,
      Item.VolcanicRock,
      Item.CobblestoneWall,
      Item.GlowingStone,
      Item.MossySoil,
      Item.StylishStoneFlooring,
      Item.FishScaleTiling,
      Item.LinedStoneFlooring,
      Item.StoneFlooring,
      Item.DamagedStoneFlooring,
      Item.StonePillarLower,
      Item.StonePillarMiddle,
      Item.StonePillarUpper,
      Item.StylishBrickWallLower,
      Item.StylishBrickWallUpper,
      Item.Marble,
      Item.WoodenWall,
      Item.WoodenPillarMiddle,
      Item.WoodenFlooring,
      Item.DamagedWoodenFlooring,
      Item.WarningWall,
      Item.IronTiling,
      Item.IronPlateFlooring,
      Item.StoneTiling,
      Item.DamagedStoneTiling,
      Item.ProtrudingWall,
      Item.DarkMarbleFlooring,
      Item.ExtravagantPillarLower,
      Item.ExtravagantPillarMiddle,
      Item.ExtravagantPillarUpper,
      Item.StarrySkyWall,
      Item.SimpleFlooring,
      Item.ExtravagantCarpeting,
      Item.WovenCarpeting,
      Item.CyberFlooring,
      Item.ClothWall,
      Item.LightAntiqueWallUpper,
      Item.AntiqueWallLower,
      Item.AntiqueWallMiddle,
      Item.AntiqueWallUpper,
      Item.PlasterWall,
      Item.PaintedWall,
      Item.CrystalWall,
      Item.CrackedSandstone,
      Item.CopperDepositRidge,
      Item.IronDeposit,
      Item.GoldDeposit,
      Item.PokemetalDeposit,
      Item.ReddishBrownCaveRock
    ],
    "itemsInArea": [
      "workbench",
      Item.StoneSteps,
      Item.IronScaffold,
      Item.Lantern,
      Item.WoodenCrate,
      "broken-window-pane",
      "sloped-stone-roof",
      "skylight",
      "flat-stone-roof",
      Item.ModernDoor,
      Item.GlassWindow,
      Item.PlainCloset,
      Item.IndustrialChair,
      Item.StorageBox,
      "wooden-fencing",
      Item.ChicStreetlight,
      Item.StoneTable,
      Item.StoneBench,
      Item.CDRack,
      "grate-flooring",
      Item.CookingStove,
      Item.ModernSink,
      Item.Counter,
      Item.MenuBoard,
      "swinging-doors",
      "large-wooden-door",
      Item.BreadOven,
      Item.KitchenTable,
      Item.CuttingBoard,
      Item.FryingPan,
      Item.Mug,
      Item.Barrel,
      Item.WornWoodenCrate,
      "pulley",
      Item.Cart,
      Item.Bookcase,
      Item.MetalDrum,
      Item.Rope,
      Item.TrafficCone,
      Item.Sandbags,
      Item.ExcavationTools,
      Item.Handcar,
      Item.RailwayTrack,
      Item.Sprinkler,
      Item.CrossingGate,
      Item.IronPipes,
      "grate-fencing",
      Item.SmeltingFurnace,
      Item.FieryMagbyStatue,
      Item.FloorSwitch,
      Item.MushroomStreetlight,
      Item.Wheelbarrow,
      Item.ConstructionSupplies,
      Item.PopArtLamp,
      Item.Campfire,
      Item.IndustrialBench,
      Item.IndustrialDesk,
      Item.Balloons,
      Item.FoldingChair,
      Item.WoodenPlate,
      "glossy-awning",
      "wooden-handrail",
      "exhibition-stand",
      Item.DespotFossilLegs,
      Item.ExtravagantFlowers,
      Item.PopArtSofa,
      Item.TwistedPottedPlant,
      "book-pile",
      Item.OfficeChair,
      "office-table",
      Item.BerryChair,
      "stylish-door",
      Item.IronDoor,
      Item.TallPottedPlant,
      Item.Speaker,
      Item.BerryClock,
      Item.StandingMic,
      Item.BooInTheBox,
      Item.TabletopMic,
      Item.IronTable,
      Item.MusicMatLowDo,
      Item.MusicMatMi,
      Item.MusicMatSol,
      Item.MusicMatHighDo,
      Item.OfficeDesk,
      Item.OfficeShelf,
      Item.ScienceExperiment,
      Item.CardboardBoxes,
      Item.HangingBanner,
      Item.AntiqueTable,
      Item.AntiqueSofa,
      Item.AntiqueClock,
      Item.AntiqueChandelier,
      Item.AntiqueChair,
      Item.ChicChair,
      Item.ModelSpaceShuttle,
      Item.Spaceship,
      Item.ModelPlanet,
      Item.Spacesuit,
      Item.Wire,
      Item.ChicSofa,
      Item.MagazineRack,
      "stone-fencing",
      "pitched-brick-roof",
      "dormered-brick-roof",
      "brick-hipped-roof",
      "flat-brick-roof",
      "brick-roof-valley",
      "wooden-steps",
      "poke-ball-doormat",
      Item.TownMap,
      "broken-bookcase"
    ],
    "itemsInPokeballs": [
      "aged-stone-wall-recipe",
      Item.Balloons,
      "bean-seeds",
      "cooking-pot-recipe",
      "damp-hedge-seeds",
      "elegant-flower-seed",
      Item.FirstAidKit,
      "fresh-water",
      Item.HotSpringSpout,
      "industrial-bed-recipe",
      Item.IndustrialBed,
      Item.IndustrialChair,
      "iron-chair-recipe",
      "iron-table-recipe",
      "pecha-tree-seed",
      "perch-recipe",
      Item.Pokemetal,
      Item.RailwayTrack,
      "railway-track-recipe",
      Item.SmallStage,
      "stone-house-kit",
      "stone-steps-recipe"
    ],
    "treasure": [
      Item.LargeLostRelic,
      Item.SmallLostRelic,
      Item.ArcanineDoll,
      Item.DittoDoll,
      Item.SubstituteDoll,
      Item.DespotFossilHead,
      Item.DespotFossilBody,
      Item.DespotFossilLegs,
      Item.DespotFossilTail,
      Item.JawFossil,
      Item.WingFossilHead,
      Item.WingFossilRightWing,
      Item.WingFossilLeftWing,
      Item.WingFossilBody,
      Item.WingFossilTail,
      Item.StrangeStrings,
      Item.ArmorFragment
    ],
    "shopItems": [
      {
        "slug": Item.StandingMic,
        "name": "Standing mic",
        "level": 2
      },
      {
        "slug": Item.StoneBench,
        "name": "Stone bench",
        "level": 2
      },
      {
        "slug": "stone-hut-kit",
        "name": "Stone hut kit",
        "level": 2
      },
      {
        "slug": Item.Twine,
        "name": "Twine",
        "level": 2
      },
      {
        "slug": "stepping-stones-recipe",
        "name": "Stepping stones Recipe",
        "level": 2
      },
      {
        "slug": Item.Balloons,
        "name": "Balloons",
        "level": 3
      },
      {
        "slug": Item.Fluff,
        "name": "Fluff",
        "level": 3
      },
      {
        "slug": "fresh-water",
        "name": "Fresh water",
        "level": 3
      },
      {
        "slug": "moonlight-dance-statue-kit",
        "name": "Moonlight dance statue kit",
        "level": 3
      },
      {
        "slug": Item.SmallStage,
        "name": "Small stage",
        "level": 3
      },
      {
        "slug": "stone-den-kit",
        "name": "Stone den kit",
        "level": 3
      },
      {
        "slug": "iron-bed-recipe",
        "name": "Iron bed Recipe",
        "level": 3
      },
      {
        "slug": "party-bunting-recipe",
        "name": "Party bunting Recipe",
        "level": 3
      },
      {
        "slug": Item.PaperPartyCups,
        "name": "Paper party cups",
        "level": 4
      },
      {
        "slug": "speakers",
        "name": "Speakers",
        "level": 4
      },
      {
        "slug": "stone-cottage-kit",
        "name": "Stone cottage kit",
        "level": 4
      },
      {
        "slug": "dark-marble-flooring-recipe",
        "name": "Dark marble flooring Recipe",
        "level": 4
      },
      {
        "slug": "iron-tiling-recipe",
        "name": "Iron tiling Recipe",
        "level": 4
      },
      {
        "slug": "gray-hut-kit",
        "name": "Gray hut kit",
        "level": 5
      },
      {
        "slug": Item.Refrigerator,
        "name": "Refrigerator",
        "level": 5
      },
      {
        "slug": "stone-house-kit",
        "name": "Stone house kit",
        "level": 5
      },
      {
        "slug": Item.Tablet,
        "name": "Tablet",
        "level": 5
      },
      {
        "slug": "iron-door-recipe",
        "name": "Iron door Recipe",
        "level": 5
      },
      {
        "slug": "iron-ladder-recipe",
        "name": "Iron ladder Recipe",
        "level": 5
      },
      {
        "slug": "iron-steps-recipe",
        "name": "Iron steps Recipe",
        "level": 5
      },
      {
        "slug": "refrigerator-recipe",
        "name": "Refrigerator Recipe",
        "level": 5
      },
      {
        "slug": "small-stage-recipe",
        "name": "Small stage Recipe",
        "level": 5
      },
      {
        "slug": Item.LaserSensor,
        "name": "Laser sensor",
        "level": 6
      },
      {
        "slug": Item.Pokemetal,
        "name": "Pokemetal",
        "level": 6
      },
      {
        "slug": "industrial-chair-recipe",
        "name": "Industrial chair Recipe",
        "level": 6
      },
      {
        "slug": "lantern-recipe",
        "name": "Lantern Recipe",
        "level": 6
      },
      {
        "slug": "laser-sensor-recipe",
        "name": "Laser sensor Recipe",
        "level": 6
      },
      {
        "slug": "stylish-stone-flooring-recipe",
        "name": "Stylish stone flooring Recipe",
        "level": 6
      },
      {
        "slug": Item.RarePokemetal,
        "name": "Rare Pokemetal",
        "level": 7
      },
      {
        "slug": "industrial-bench-recipe",
        "name": "Industrial bench Recipe",
        "level": 7
      },
      {
        "slug": "industrial-desk-recipe",
        "name": "Industrial desk Recipe",
        "level": 7
      },
      {
        "slug": "iron-wall-recipe",
        "name": "Iron wall Recipe",
        "level": 7
      },
      {
        "slug": "poke-ball-doormat-recipe",
        "name": "Poke Ball doormat Recipe",
        "level": 7
      },
      {
        "slug": "concert-stage-kit",
        "name": "Concert stage kit",
        "level": 8
      },
      {
        "slug": "cube-light-recipe",
        "name": "Cube light Recipe",
        "level": 8
      },
      {
        "slug": "luxury-sofa-recipe",
        "name": "Luxury sofa Recipe",
        "level": 8
      },
      {
        "slug": "luxury-table-recipe",
        "name": "Luxury table Recipe",
        "level": 8
      },
      {
        "slug": "cushy-wall-recipe",
        "name": "Cushy wall Recipe",
        "level": 9
      },
      {
        "slug": Item.PunchingGame,
        "name": "Punching game",
        "level": 9
      },
      {
        "slug": "luxury-chair-recipe",
        "name": "Luxury chair Recipe",
        "level": 9
      },
      {
        "slug": "luxury-lamp-recipe",
        "name": "Luxury lamp Recipe",
        "level": 9
      },
      {
        "slug": "ridge-pokemon-center-kit",
        "name": "Ridge Pokemon Center kit",
        "level": 10
      },
      {
        "slug": "luxury-dresser-recipe",
        "name": "Luxury dresser Recipe",
        "level": 10
      },
      {
        "slug": "luxury-bed-recipe",
        "name": "Luxury bed Recipe",
        "level": 10
      },
      {
        "slug": "stylish-poke-ball-print-recipe",
        "name": "Stylish Poke Ball Print Recipe",
        "level": 10
      }
    ]
  },
  "sparklingskylands": {
    "slug": "sparklingskylands",
    "name": "Sparkling Skylands",
    "description": "The Sparkling Skylands are a giant area that focused around what used to be Celadon and Saffron Cities. The catastrophe caused the ground to shoot up into the sky.With the Pokemon you find here, your task is to rebuild Silph Co. into a new building to bring back humans and Pokemon",
    "objective": "",
    "materials": [
      Item.SturdyStick,
      Item.Stone,
      Item.Vine,
      Item.VineRope,
      Item.GlowingMushrooms,
      Item.IronOre,
      Item.PokemetalFragment,
      Item.Tomato,
      Item.Wheat,
      Item.Bean,
      Item.Twine,
      Item.NonburnableGarbage,
      Item.Wastepaper,
      Item.SmallLog,
      Item.Lumber,
      Item.LeppaBerry,
      Item.RarePokemetalFragment
    ],
    "blocksAndPlants": [
      Item.RedTallGrass,
      Item.YellowTallGrass,
      Item.PinkTallGrass,
      Item.Moss,
      Item.LeppaTree,
      Item.PointyTree,
      Item.SkylandFlowers,
      Item.SkylandFlowersBlue,
      Item.SkylandFlowersOrange,
      Item.SkylandFlowersPink,
      Item.SkylandFlowersYellow,
      Item.SeashoreFlowers,
      Item.SeashoreFlowersBlue,
      Item.SeashoreFlowersOrange,
      Item.SeashoreFlowersWhite,
      Item.SeashoreFlowersYellow,
      Item.MountainFlowers,
      Item.MountainFlowersPink,
      Item.MountainFlowersPurple,
      Item.MountainFlowersRed,
      Item.MountainFlowersWhite,
      Item.YellowGreenShoots,
      Item.DryYellowGreenShoots,
      Item.VerdantShoots,
      Item.DryVerdantShoots,
      Item.BlueGreenShoots,
      Item.DryBlueGreenShoots,
      Item.RobustFlower,
      Item.RobustFlowerBlue,
      Item.RobustFlowerOrange,
      Item.RobustFlowerPurple,
      Item.RobustFlowerWhite,
      Item.StylishHedge,
      Item.StylishHedgeBlue,
      Item.StylishHedgeOrange,
      Item.StylishHedgePurple,
      Item.StylishHedgeWhite,
      Item.SeashoreGrass,
      Item.AlpineGrass,
      Item.SkyHighGrass,
      Item.SeashellSoil,
      Item.StripedSoil,
      Item.PureWhiteSoil,
      Item.BarrenPureWhiteSoil,
      Item.OrdinarySand,
      Item.SkylandSand,
      Item.SkylandSandstone,
      Item.CrackedSandstone,
      Item.RedCliffRock,
      Item.RedSpottedCliffRock,
      Item.BlackCliffRock,
      Item.BlackSpottedCliffRock,
      Item.SkylandCliffRock,
      Item.SkylandSpottedCliffRock,
      Item.LargeBoulder,
      Item.MossyBoulder,
      Item.MysteriousStone,
      Item.LightBrownRock,
      Item.MetalDebris,
      Item.StoneDebris,
      Item.WornLumber,
      Item.ScrapCube,
      Item.CoarseRock,
      Item.CaveRock,
      Item.MossySoil,
      Item.StoneBrickWall,
      Item.StoneFragments,
      Item.MetalFragments,
      Item.Stalagmites,
      Item.Limestone,
      Item.Levee,
      Item.RoughWall,
      Item.StonePillarMiddle,
      Item.StylishBrickWallLower,
      Item.BrickWall,
      Item.StylishBrickWallUpper,
      Item.ConcreteWall,
      Item.StripedWall,
      Item.NeonFlooring,
      Item.SquareTiling,
      Item.DamagedSquareTiling,
      Item.IronPlateFlooring,
      Item.RustedIronPlateFlooring,
      Item.WarningWall,
      Item.AsphaltRoad,
      Item.DamagedAsphaltRoad,
      Item.MarkedRoadHorizontal,
      Item.MuddyTiling,
      Item.CyberFlooring,
      Item.DamagedWoodenFlooring,
      Item.Foundation,
      Item.IronTiling,
      Item.ProtrudingWall,
      Item.GrayCircleFlooring,
      Item.MosaicTiling,
      Item.DamagedMosaicTiling,
      Item.WovenCarpeting,
      Item.PopArtWallUpper,
      Item.PopArtWallMiddle,
      Item.PopArtWallLower,
      Item.StrengthRock,
      Item.IronBeam,
      Item.IronColumn,
      Item.IronPlating,
      Item.ExtravagantCarpeting,
      Item.LightMarbleFlooring,
      Item.WoodenWall,
      Item.ModernCarpeting,
      Item.GrassFlooring,
      Item.CubeLight,
      Item.WoodenFlooring,
      Item.CrisscrossWoodenFlooring,
      Item.AntiqueWallLower,
      Item.AntiqueWallMiddle,
      Item.AntiqueWallUpper,
      Item.PlasterWall,
      Item.StylishTiling,
      Item.SimpleSquareTiling,
      Item.BrokenTilingWall,
      Item.CushyWall,
      Item.LightWoodenWall,
      Item.WoodenPillarUpper,
      Item.WoodenPillarMiddle,
      Item.WoodenPillarLower,
      Item.HardwoodFlooring,
      Item.ClothWall,
      Item.GrubbyRags,
      Item.CopperDepositSkyland,
      Item.IronDeposit,
      Item.PokemetalDeposit
    ],
    "itemsInArea": [
      "workbench",
      Item.StorageBox,
      Item.StoneSteps,
      "harbor-pole",
      Item.IronSteps,
      "broken-iron-steps",
      "grate-flooring",
      Item.DoubleStreetlight,
      Item.MetalDrum,
      Item.UtilityPole,
      Item.Spotlight,
      Item.GamingLight,
      Item.RaichuSign,
      Item.FireHydrant,
      "lift-platform",
      "metal-fencing",
      "wooden-fencing",
      Item.WoodenPath,
      Item.IndustrialBench,
      Item.CardboardBoxes,
      Item.TowelRack,
      Item.KitchenTable,
      Item.CookingStove,
      Item.CuttingBoard,
      Item.TwistedPottedPlant,
      Item.IndustrialChair,
      Item.IndustrialDesk,
      Item.ScienceExperiment,
      Item.Microscope,
      Item.Papers,
      Item.OfficeLocker,
      Item.Computer,
      Item.Rope,
      Item.GarbageBin,
      Item.RailwayTrack,
      Item.BeachParasol,
      Item.IronPipes,
      Item.IronScaffold,
      Item.ExcavationTools,
      Item.FoldingChair,
      Item.Balloons,
      Item.Lantern,
      Item.MirrorBall,
      Item.StringLights,
      Item.WornWoodenCrate,
      Item.OfficeChair,
      "office-table",
      Item.PlainSofa,
      Item.OfficeShelf,
      Item.OfficeDesk,
      Item.Laptop,
      "planter",
      Item.VendingMachine,
      Item.CDPlayer,
      Item.PopArtSofa,
      Item.JumbledCords,
      Item.TeaSet,
      Item.OfficeCabinet,
      Item.Humidifier,
      "stylish-cooking-pot",
      Item.ModernSink,
      Item.PlainTable,
      Item.GardenChair,
      Item.GardenTable,
      Item.SpectatorChair,
      Item.PokeBallLamp,
      Item.TeamRocketWallHanging,
      Item.CDRack,
      Item.FluorescentLight,
      "grate-fencing",
      Item.IronLadder,
      "elevator-platform",
      Item.MetallicSmeltingFurnace,
      Item.SimpleCushion,
      "simple-curtain-left",
      "simple-curtain-right",
      Item.EerieCandle,
      Item.WindowPane,
      "broken-window-pane",
      Item.HangingScroll,
      "sloped-tile-roof",
      "wooden-partition",
      Item.PunchingBag,
      Item.HorseaFountain,
      Item.Whiteboard,
      Item.SewerHoleCover,
      Item.GarbageBags,
      Item.ChicSofa,
      Item.RecyclingBin,
      Item.SurfaceLight,
      Item.TallPottedPlant,
      Item.CorrugatedMetal,
      "concrete-mixer",
      Item.GlassWindow,
      Item.FirstAidKit,
      Item.Slide,
      Item.BerryClock,
      "wooden-posts",
      Item.PokeBallBed,
      Item.TireToy,
      Item.PopArtTable,
      Item.ToyBlocks,
      Item.PopArtChair,
      Item.FlatLeafPlant,
      "simple-door",
      Item.PopArtLamp,
      Item.MenuBoard,
      "swinging-doors",
      Item.Corkboard,
      Item.AirConditioner,
      Item.CashRegister,
      "wall-mounted-table",
      Item.PitcherPlantPot,
      Item.Bookcase,
      Item.ControlUnit,
      Item.StepStool,
      Item.DecorativeStorageShelf,
      Item.MagazineRack,
      Item.ChicChair,
      Item.SeedotLamp,
      "glossy-awning",
      Item.AntiqueChair,
      Item.StainedGlassWindowMiddle,
      Item.StainedGlassWindowUpper,
      Item.LuxuryLamp,
      Item.AntiqueTable,
      Item.AntiqueSofa,
      Item.AntiqueCloset,
      Item.PushCart,
      Item.MiniBookcase,
      Item.StoneFireplace,
      Item.ShellLamp,
      Item.CleaningSupplies,
      Item.Toilet,
      Item.Sink,
      Item.Bathtub,
      Item.Shower,
      Item.AntiqueDresser,
      Item.FancyPen,
      Item.AntiqueChest,
      Item.AntiqueChandelier,
      Item.GardenLight,
      Item.GardenBench,
      Item.LargeVentilationFan,
      Item.NaptimeBed,
      "public-chair",
      "pokeball-table",
      Item.Counter,
      Item.WoodenPlate,
      Item.BrokenStreetlight,
      Item.MushroomStreetlight,
      Item.ConstructionSupplies,
      Item.WallMirror,
      Item.Torch,
      Item.SteppingStones,
      "arched-barrier",
      Item.CardReader,
      "shutter",
      Item.Printer,
      Item.WallCalendar,
      Item.ClefairyDoll,
      "iron-pipe-downward-t",
      "iron-pipe-downward-curve",
      "iron-pipe-vertical",
      "iron-pipe-horizontal",
      "iron-pipe-vertical-t",
      "iron-pipe-upward-curve",
      "iron-pipe-upward-t",
      "iron-pipe-vertical-cross"
    ],
    "itemsInPokeballs": [
      "beautiful-flower-seeds",
      Item.CleaningSupplies,
      Item.Fluff,
      Item.GoldIngot,
      Item.Limestone,
      Item.Microscope,
      "office-cabinet-recipe",
      "office-chair-recipe",
      "office-desk-recipe",
      "office-table-recipe",
      Item.PopArtBed,
      Item.RarePokemetal,
      Item.ScienceExperiment,
      "scrap-cube-recipe",
      Item.SewerHoleCover,
      Item.SmeltingFurnace,
      "stylish-hedge-seeds",
      Item.WallSwitch,
      "wooden-ladder",
      "yellow-hut-kit"
    ],
    "treasure": [
      Item.LargeLostRelic,
      Item.SmallLostRelic,
      Item.DragoniteDoll,
      Item.DittoDoll,
      Item.SubstituteDoll,
      Item.HeadbuttFossilHead,
      Item.HeadbuttFossilBody,
      Item.HeadbuttFossilTail,
      Item.SkullFossil,
      Item.WingFossilHead,
      Item.WingFossilRightWing,
      Item.WingFossilLeftWing,
      Item.WingFossilBody,
      Item.WingFossilTail,
      Item.StrangeStrings,
      Item.ArmorFragment
    ],
    "shopItems": [
      {
        "slug": Item.Mailbox,
        "name": "Mailbox",
        "level": 2
      },
      {
        "slug": Item.OfficeChair,
        "name": "Office chair",
        "level": 2
      },
      {
        "slug": Item.Slide,
        "name": "Slide",
        "level": 2
      },
      {
        "slug": "asphalt-road-recipe",
        "name": "Asphalt road Recipe",
        "level": 2
      },
      {
        "slug": "cd-rack-recipe",
        "name": "CD rack Recipe",
        "level": 2
      },
      {
        "slug": "concrete-steps-recipe",
        "name": "Concrete steps Recipe",
        "level": 2
      },
      {
        "slug": "metal-fencing-recipe",
        "name": "Metal fencing Recipe",
        "level": 2
      },
      {
        "slug": "mosaic-tiling-recipe",
        "name": "Mosaic tiling Recipe",
        "level": 2
      },
      {
        "slug": Item.Bathtub,
        "name": "Bathtub",
        "level": 3
      },
      {
        "slug": Item.MagazineRack,
        "name": "Magazine rack",
        "level": 3
      },
      {
        "slug": Item.OfficeCabinet,
        "name": "Office cabinet",
        "level": 3
      },
      {
        "slug": "pokemart-kit",
        "name": "Pokemart kit",
        "level": 3
      },
      {
        "slug": Item.PopArtSofa,
        "name": "Pop art sofa",
        "level": 3
      },
      {
        "slug": "cd-player-recipe",
        "name": "CD player Recipe",
        "level": 3
      },
      {
        "slug": Item.Newspaper,
        "name": "Newspaper",
        "level": 4
      },
      {
        "slug": Item.OfficeLocker,
        "name": "Office locker",
        "level": 4
      },
      {
        "slug": "concrete-slab-recipe",
        "name": "Concrete slab Recipe",
        "level": 4
      },
      {
        "slug": "corrugated-metal-recipe",
        "name": "Corrugated metal Recipe",
        "level": 4
      },
      {
        "slug": "metallic-smelting-furnace-recipe",
        "name": "Metallic smelting furnace Recipe",
        "level": 4
      },
      {
        "slug": "protruding-wall-recipe",
        "name": "Protruding wall Recipe",
        "level": 4
      },
      {
        "slug": "stone-fencing-recipe",
        "name": "Stone fencing Recipe",
        "level": 4
      },
      {
        "slug": "window-pane-recipe",
        "name": "Window pane Recipe",
        "level": 4
      },
      {
        "slug": Item.GameBoySystem,
        "name": "Game Boy system",
        "level": 5
      },
      {
        "slug": Item.StoneFireplace,
        "name": "Stone fireplace",
        "level": 5
      },
      {
        "slug": "yellow-hut-kit",
        "name": "Yellow hut kit",
        "level": 5
      },
      {
        "slug": "game-boy-system-recipe",
        "name": "Game Boy system Recipe",
        "level": 5
      },
      {
        "slug": "glass-window-recipe",
        "name": "Glass window Recipe",
        "level": 5
      },
      {
        "slug": "simple-door-recipe",
        "name": "Simple door Recipe",
        "level": 5
      },
      {
        "slug": Item.Pokemetal,
        "name": "Pokemetal",
        "level": 6
      },
      {
        "slug": "concrete-border-corner-recipe",
        "name": "Concrete border (corner) Recipe",
        "level": 6
      },
      {
        "slug": "concrete-border-line-recipe",
        "name": "Concrete border (line) Recipe",
        "level": 6
      },
      {
        "slug": "concrete-border-single-recipe",
        "name": "Concrete border (single) Recipe",
        "level": 6
      },
      {
        "slug": "mini-generator-recipe",
        "name": "Mini generator Recipe",
        "level": 6
      },
      {
        "slug": "pop-art-bed-recipe",
        "name": "Pop art bed Recipe",
        "level": 6
      },
      {
        "slug": "pop-art-chair-recipe",
        "name": "Pop art chair Recipe",
        "level": 6
      },
      {
        "slug": Item.RarePokemetal,
        "name": "Rare Pokemetal",
        "level": 7
      },
      {
        "slug": "pop-art-sofa-recipe",
        "name": "Pop art sofa Recipe",
        "level": 7
      },
      {
        "slug": "pop-art-table-recipe",
        "name": "Pop art table Recipe",
        "level": 7
      },
      {
        "slug": "rough-wall-recipe",
        "name": "Rough wall Recipe",
        "level": 7
      },
      {
        "slug": "small-office-kit",
        "name": "Small office kit",
        "level": 8
      },
      {
        "slug": "pop-art-lamp-recipe",
        "name": "Pop art lamp Recipe",
        "level": 8
      },
      {
        "slug": "shop-flooring-recipe",
        "name": "Shop flooring Recipe",
        "level": 8
      },
      {
        "slug": Item.BigDrum,
        "name": "Big drum",
        "level": 9
      },
      {
        "slug": "gaming-chair-recipe",
        "name": "Gaming chair Recipe",
        "level": 9
      },
      {
        "slug": "gaming-light-recipe",
        "name": "Gaming light Recipe",
        "level": 9
      },
      {
        "slug": "pokemon-center-wall-lower-recipe",
        "name": "Pokemon Center wall (lower) Recipe",
        "level": 9
      },
      {
        "slug": "pokemon-center-wall-middle-recipe",
        "name": "Pokemon Center wall (middle) Recipe",
        "level": 9
      },
      {
        "slug": "pokemon-center-wall-trim-recipe",
        "name": "Pokemon Center wall (trim) Recipe",
        "level": 9
      },
      {
        "slug": "pokemon-center-wall-upper-recipe",
        "name": "Pokemon Center wall (upper) Recipe",
        "level": 9
      },
      {
        "slug": "skyland-pokemon-center-kit",
        "name": "Skyland Pokemon Center kit",
        "level": 10
      },
      {
        "slug": "berry-print-recipe",
        "name": "Berry print Recipe",
        "level": 10
      },
      {
        "slug": "gaming-fridge-recipe",
        "name": "Gaming fridge Recipe",
        "level": 10
      },
      {
        "slug": "gaming-pc-recipe",
        "name": "Gaming PC Recipe",
        "level": 10
      }
    ]
  },
  "palettetown": {
    "slug": "palettetown",
    "name": "Palette Town",
    "description": "Palette Town is an area found over the bridge from Withered Wastelands. This area is a free open space for you to do with as you please.This map is the one you use in multiplayer on both Cloud Islands and in modes where you can play and build along with your friends",
    "objective": "",
    "materials": [
      Item.SturdyStick,
      Item.Stone,
      Item.GlowingMushrooms,
      Item.SeaGlassFragments,
      Item.Seaweed,
      Item.VineRope,
      Item.Wastepaper,
      Item.Leaf,
      Item.FreshCarrot,
      Item.CopperOre,
      Item.IronOre,
      Item.GoldOre
    ],
    "blocksAndPlants": [
      "tall-grass",
      Item.DryTallGrass,
      Item.Wildflowers,
      Item.WildflowersOrange,
      Item.WildflowersPurple,
      Item.WildflowersRed,
      Item.WildflowersBlue,
      Item.DryWildflowers,
      Item.FieldGrass,
      Item.DryFieldGrass,
      Item.OrdinarySoil,
      Item.BarrenOrdinarySoil,
      Item.GreenShoots,
      Item.DryGreenShoots,
      Item.LeppaTree,
      Item.DryLeppaTree,
      Item.ChestoTree,
      Item.RawstTree,
      Item.LumTree,
      Item.AspearTree,
      Item.PechaTree,
      Item.LargePalmTree,
      Item.WhiteRock,
      Item.MossySoil,
      Item.LargeBoulder,
      Item.MossyBoulder,
      Item.Ice,
      Item.CrystalCluster,
      Item.OrdinarySand,
      Item.BeachSand,
      Item.BumpyBeachSand,
      Item.WornLumber,
      Item.CliffRock,
      Item.SpottedCliffRock,
      Item.CaveRock,
      Item.BlackRock,
      Item.Vine,
      Item.DryVine,
      Item.MysteriousPedestal,
      Item.AgedStoneWall,
      Item.PatternedAgedStoneWall,
      Item.WoodFragments,
      Item.StoneFragments,
      Item.MetalFragments,
      Item.MetalDebris,
      "grubby-rag",
      Item.Driftwood,
      Item.CopperDeposit,
      Item.IronDeposit,
      Item.GoldDeposit,
      Item.IronOre,
      Item.GoldOre
    ],
    "itemsInArea": [
      "workbench",
      Item.StoneSteps,
      Item.MysteriousPedestal,
      "poke-ball-doormat",
      Item.TownMap
    ],
    "itemsInPokeballs": [
      "abandoned-power-plant-kit",
      "altar-of-the-flame-kit",
      "freezing-chambers-kit"
    ],
    "treasure": [
      Item.LargeLostRelic,
      Item.SmallLostRelic,
      Item.DittoDoll,
      Item.SubstituteDoll,
      Item.SkullFossil,
      Item.ArmorFossil,
      Item.JawFossil,
      Item.SailFossil,
      Item.WingFossilHead,
      Item.WingFossilRightWing,
      Item.WingFossilLeftWing,
      Item.WingFossilBody,
      Item.WingFossilTail,
      Item.HeadbuttFossilHead,
      Item.HeadbuttFossilBody,
      Item.HeadbuttFossilTail,
      Item.ShieldFossilHead,
      Item.ShieldFossilBody,
      Item.ShieldFossilTail,
      Item.DespotFossilHead,
      Item.DespotFossilBody,
      Item.DespotFossilLegs,
      Item.DespotFossilTail,
      Item.TundraFossilHead,
      Item.TundraFossilBody,
      Item.TundraFossilTail,
      Item.StrangeStrings,
      Item.ArmorFragment
    ],
    "shopItems": [
      {
        "slug": Item.BigStorageBox,
        "name": "Big storage box",
        "level": 2
      },
      {
        "slug": Item.EeveeDoll,
        "name": "Eevee doll",
        "level": 2
      },
      {
        "slug": "dowsing-machine-recipe",
        "name": "Dowsing Machine Recipe",
        "level": 2
      },
      {
        "slug": Item.CDPlayer,
        "name": "CD player",
        "level": 3
      },
      {
        "slug": Item.FishingRod,
        "name": "Fishing rod",
        "level": 3
      },
      {
        "slug": Item.PikachuDoll,
        "name": "Pikachu doll",
        "level": 3
      },
      {
        "slug": "counter-recipe",
        "name": "Counter Recipe",
        "level": 3
      },
      {
        "slug": "town-streetlight-recipe",
        "name": "Town streetlight Recipe",
        "level": 3
      },
      {
        "slug": Item.Fan,
        "name": "Fan",
        "level": 4
      },
      {
        "slug": "light-wooden-wall-recipe",
        "name": "Light wooden wall Recipe",
        "level": 4
      },
      {
        "slug": Item.ArcanineDoll,
        "name": "Arcanine doll",
        "level": 5
      },
      {
        "slug": Item.BlackPaint,
        "name": "Black paint",
        "level": 5
      },
      {
        "slug": Item.BluePaint,
        "name": "Blue paint",
        "level": 5
      },
      {
        "slug": Item.CyanPaint,
        "name": "Cyan paint",
        "level": 5
      },
      {
        "slug": Item.GreenPaint,
        "name": "Green paint",
        "level": 5
      },
      {
        "slug": Item.JumbledCords,
        "name": "Jumbled cords",
        "level": 5
      },
      {
        "slug": Item.PinkPaint,
        "name": "Pink paint",
        "level": 5
      },
      {
        "slug": Item.RedPaint,
        "name": "Red paint",
        "level": 5
      },
      {
        "slug": Item.Television,
        "name": "Television",
        "level": 5
      },
      {
        "slug": Item.WhitePaint,
        "name": "White paint",
        "level": 5
      },
      {
        "slug": Item.YellowPaint,
        "name": "Yellow paint",
        "level": 5
      },
      {
        "slug": "antique-bed-recipe",
        "name": "Antique bed Recipe",
        "level": 5
      },
      {
        "slug": "antique-chair-recipe",
        "name": "Antique chair Recipe",
        "level": 5
      },
      {
        "slug": "antique-table-recipe",
        "name": "Antique table Recipe",
        "level": 5
      },
      {
        "slug": Item.DragoniteDoll,
        "name": "Dragonite doll",
        "level": 6
      },
      {
        "slug": Item.Pokemetal,
        "name": "Pokemetal",
        "level": 6
      },
      {
        "slug": "antique-chest-recipe",
        "name": "Antique chest Recipe",
        "level": 6
      },
      {
        "slug": "antique-sofa-recipe",
        "name": "Antique sofa Recipe",
        "level": 6
      },
      {
        "slug": Item.RarePokemetal,
        "name": "Rare Pokemetal",
        "level": 7
      },
      {
        "slug": Item.SubstituteDoll,
        "name": "Substitute doll",
        "level": 7
      },
      {
        "slug": "antique-chandelier-recipe",
        "name": "Antique chandelier Recipe",
        "level": 7
      },
      {
        "slug": "antique-dresser-recipe",
        "name": "Antique dresser Recipe",
        "level": 7
      },
      {
        "slug": "antique-wall-lower-recipe",
        "name": "Antique wall (lower) Recipe",
        "level": 7
      },
      {
        "slug": "antique-wall-middle-recipe",
        "name": "Antique wall (middle) Recipe",
        "level": 7
      },
      {
        "slug": "antique-wall-upper-recipe",
        "name": "Antique wall (upper) Recipe",
        "level": 7
      },
      {
        "slug": Item.DittoDoll,
        "name": "Ditto doll",
        "level": 8
      },
      {
        "slug": "fountain-plaza-kit",
        "name": "Fountain plaza kit",
        "level": 8
      },
      {
        "slug": "antique-clock-recipe",
        "name": "Antique clock Recipe",
        "level": 8
      },
      {
        "slug": "antique-closet-recipe",
        "name": "Antique closet Recipe",
        "level": 8
      },
      {
        "slug": "cracked-sandstone-recipe",
        "name": "Cracked sandstone Recipe",
        "level": 8
      },
      {
        "slug": "light-antique-wall-lower-recipe",
        "name": "Light antique wall (lower) Recipe",
        "level": 8
      },
      {
        "slug": "light-antique-wall-middle-recipe",
        "name": "Light antique wall (middle) Recipe",
        "level": 8
      },
      {
        "slug": "light-antique-wall-upper-recipe",
        "name": "Light antique wall (upper) Recipe",
        "level": 8
      },
      {
        "slug": Item.PhotoCutoutBoard,
        "name": "Photo cutout board",
        "level": 9
      },
      {
        "slug": "carved-coarse-rock-recipe",
        "name": "Carved coarse rock Recipe",
        "level": 9
      },
      {
        "slug": "carved-light-brown-rock-recipe",
        "name": "Carved light-brown rock Recipe",
        "level": 9
      },
      {
        "slug": "carved-red-rock-recipe",
        "name": "Carved red rock Recipe",
        "level": 9
      },
      {
        "slug": "carved-white-rock-recipe",
        "name": "Carved white rock Recipe",
        "level": 9
      },
      {
        "slug": "carved-yellow-rock-recipe",
        "name": "Carved yellow rock Recipe",
        "level": 9
      },
      {
        "slug": "poke-ball-light-recipe",
        "name": "Poke Ball light Recipe",
        "level": 9
      },
      {
        "slug": "poke-ball-sofa-recipe",
        "name": "Poke Ball sofa Recipe",
        "level": 9
      },
      {
        "slug": "poke-ball-bed-recipe",
        "name": "Poke Ball bed Recipe",
        "level": 10
      },
      {
        "slug": "poke-ball-chest-recipe",
        "name": "Poke Ball Chest Recipe",
        "level": 10
      },
      {
        "slug": "poke-ball-print-recipe",
        "name": "Poke Ball Print Recipe",
        "level": 10
      },
      {
        "slug": "poke-ball-table-recipe",
        "name": "Poke Ball table Recipe",
        "level": 10
      }
    ]
  },
  "cloudisland": {
    "slug": "cloudisland",
    "name": "Cloud Island",
    "description": "Cloud Islands are unique islands stored on the server that allow for you to start fresh. It contains all main materials and terrain blocks, as well as its own Mysterious Slate board",
    "objective": "",
    "materials": [],
    "blocksAndPlants": [],
    "itemsInArea": [],
    "itemsInPokeballs": [],
    "treasure": [],
    "shopItems": [
      {
        "slug": Item.WallMirror,
        "name": "Wall mirror",
        "level": 1
      },
      {
        "slug": Item.WoodenPlate,
        "name": "Wooden plate",
        "level": 1
      },
      {
        "slug": "offering-dish",
        "name": "Offering dish",
        "level": 1
      },
      {
        "slug": Item.Pinwheels,
        "name": "Pinwheels",
        "level": 1
      },
      {
        "slug": Item.EeveeDoll,
        "name": "Eevee doll",
        "level": 1
      },
      {
        "slug": Item.PikachuDoll,
        "name": "Pikachu doll",
        "level": 1
      },
      {
        "slug": Item.ClefairyDoll,
        "name": "Clefairy doll",
        "level": 1
      },
      {
        "slug": Item.ArcanineDoll,
        "name": "Arcanine doll",
        "level": 1
      },
      {
        "slug": Item.DragoniteDoll,
        "name": "Dragonite doll",
        "level": 1
      },
      {
        "slug": "workbench",
        "name": "Workbench",
        "level": 1
      },
      {
        "slug": Item.SmeltingFurnace,
        "name": "Smelting furnace",
        "level": 1
      },
      {
        "slug": "concrete-mixer",
        "name": "Concrete mixer",
        "level": 1
      },
      {
        "slug": Item.SecurityCamera,
        "name": "Security camera",
        "level": 1
      },
      {
        "slug": "relocation-kit-prepare",
        "name": "Relocation kit (prepare)",
        "level": 1
      },
      {
        "slug": "demolition-kit",
        "name": "Demolition kit",
        "level": 1
      },
      {
        "slug": "wildflower-seeds",
        "name": "Wildflower seeds",
        "level": 1
      },
      {
        "slug": Item.DowsingMachine,
        "name": "Dowsing machine",
        "level": 1
      },
      {
        "slug": Item.BigStorageBox,
        "name": "Big storage box",
        "level": 2
      },
      {
        "slug": Item.UtilityPole,
        "name": "Utility pole",
        "level": 2
      },
      {
        "slug": Item.IronBeam,
        "name": "Iron beam",
        "level": 2
      },
      {
        "slug": Item.IronColumn,
        "name": "Iron column",
        "level": 2
      },
      {
        "slug": "leaf-den-kit",
        "name": "Leaf den kit",
        "level": 2
      },
      {
        "slug": "windmill-kit",
        "name": "Windmill kit",
        "level": 2
      },
      {
        "slug": "waterwheel-kit",
        "name": "Waterwheel kit",
        "level": 2
      },
      {
        "slug": "wooden-table",
        "name": "Wooden table",
        "level": 2
      },
      {
        "slug": Item.GardenBench,
        "name": "Garden bench",
        "level": 2
      },
      {
        "slug": Item.LogBed,
        "name": "Log bed",
        "level": 2
      },
      {
        "slug": Item.Mug,
        "name": "Mug",
        "level": 2
      },
      {
        "slug": Item.TwistedPottedPlant,
        "name": "Twisted potted plant",
        "level": 2
      },
      {
        "slug": Item.SlenderCandle,
        "name": "Slender candle",
        "level": 2
      },
      {
        "slug": Item.StoneBench,
        "name": "Stone bench",
        "level": 3
      },
      {
        "slug": Item.BeachChair,
        "name": "Beach chair",
        "level": 3
      },
      {
        "slug": Item.WoodenBed,
        "name": "Wooden bed",
        "level": 3
      },
      {
        "slug": Item.Pizza,
        "name": "Pizza",
        "level": 3
      },
      {
        "slug": Item.FriedPotatoes,
        "name": "Fried potatoes",
        "level": 3
      },
      {
        "slug": Item.SodaFloat,
        "name": "Soda float",
        "level": 3
      },
      {
        "slug": Item.ToyBlocks,
        "name": "Toy blocks",
        "level": 3
      },
      {
        "slug": Item.CDPlayer,
        "name": "CD player",
        "level": 3
      },
      {
        "slug": Item.StandingMic,
        "name": "Standing mic",
        "level": 3
      },
      {
        "slug": Item.WoodenBirdhouse,
        "name": "Wooden birdhouse",
        "level": 3
      },
      {
        "slug": Item.TireToy,
        "name": "Tire toy",
        "level": 3
      },
      {
        "slug": Item.BlankCanvas,
        "name": "Blank canvas",
        "level": 3
      },
      {
        "slug": Item.WaterBasin,
        "name": "Water basin",
        "level": 3
      },
      {
        "slug": Item.BeachParasol,
        "name": "Beach parasol",
        "level": 3
      },
      {
        "slug": Item.HorseaFountain,
        "name": "Horsea fountain",
        "level": 3
      },
      {
        "slug": Item.FishingRod,
        "name": "Fishing rod",
        "level": 3
      },
      {
        "slug": Item.GarbageBin,
        "name": "Garbage bin",
        "level": 3
      },
      {
        "slug": Item.CuttingBoard,
        "name": "Cutting board",
        "level": 3
      },
      {
        "slug": Item.DeskLight,
        "name": "Desk light",
        "level": 3
      },
      {
        "slug": Item.Twine,
        "name": "Twine",
        "level": 3
      },
      {
        "slug": "leaf-hut-kit",
        "name": "Leaf hut kit",
        "level": 3
      },
      {
        "slug": "sand-den-kit",
        "name": "Sand den kit",
        "level": 3
      },
      {
        "slug": "stone-den-kit",
        "name": "Stone den kit",
        "level": 3
      },
      {
        "slug": "pokemon-center-rebuilding-kit",
        "name": "Pokemon Center rebuilding kit",
        "level": 3
      },
      {
        "slug": "furnace-kit",
        "name": "Furnace kit",
        "level": 3
      },
      {
        "slug": "seashore-flower-seeds",
        "name": "Seashore-flower seeds",
        "level": 3
      },
      {
        "slug": "mountain-flower-seeds",
        "name": "Mountain-flower seeds",
        "level": 3
      },
      {
        "slug": "bean-seeds",
        "name": "Bean seeds",
        "level": 3
      },
      {
        "slug": Item.PlainCloset,
        "name": "Plain closet",
        "level": 4
      },
      {
        "slug": Item.PlainStand,
        "name": "Plain stand",
        "level": 4
      },
      {
        "slug": Item.IronRack,
        "name": "Iron rack",
        "level": 4
      },
      {
        "slug": Item.BoxSofa,
        "name": "Box sofa",
        "level": 4
      },
      {
        "slug": Item.OfficeChair,
        "name": "Office chair",
        "level": 4
      },
      {
        "slug": Item.PaperPartyCups,
        "name": "Paper party cups",
        "level": 4
      },
      {
        "slug": Item.AfternoonTeaSet,
        "name": "Afternoon tea set",
        "level": 4
      },
      {
        "slug": Item.ChocolateCookies,
        "name": "Chocolate cookies",
        "level": 4
      },
      {
        "slug": Item.Corkboard,
        "name": "Corkboard",
        "level": 4
      },
      {
        "slug": Item.Fan,
        "name": "Fan",
        "level": 4
      },
      {
        "slug": Item.KnittingSupplies,
        "name": "Knitting supplies",
        "level": 4
      },
      {
        "slug": Item.FirstAidKit,
        "name": "First aid kit",
        "level": 4
      },
      {
        "slug": Item.Speaker,
        "name": "Speaker",
        "level": 4
      },
      {
        "slug": Item.Balloons,
        "name": "Balloons",
        "level": 4
      },
      {
        "slug": Item.Slide,
        "name": "Slide",
        "level": 4
      },
      {
        "slug": Item.Cart,
        "name": "Cart",
        "level": 4
      },
      {
        "slug": Item.Mailbox,
        "name": "Mailbox",
        "level": 4
      },
      {
        "slug": Item.SmallStage,
        "name": "Small stage",
        "level": 4
      },
      {
        "slug": Item.Tires,
        "name": "Tires",
        "level": 4
      },
      {
        "slug": "stylish-frying-pan",
        "name": "Stylish frying pan",
        "level": 4
      },
      {
        "slug": "stylish-cooking-pot",
        "name": "Stylish cooking pot",
        "level": 4
      },
      {
        "slug": Item.MushroomStreetlight,
        "name": "Mushroom streetlight",
        "level": 4
      },
      {
        "slug": "fresh-water",
        "name": "Fresh water",
        "level": 4
      },
      {
        "slug": Item.Fluff,
        "name": "Fluff",
        "level": 4
      },
      {
        "slug": "leaf-cottage-kit",
        "name": "Leaf cottage kit",
        "level": 4
      },
      {
        "slug": "sand-hut-kit",
        "name": "Sand hut kit",
        "level": 4
      },
      {
        "slug": "sand-cottage-kit",
        "name": "Sand cottage kit",
        "level": 4
      },
      {
        "slug": "stone-hut-kit",
        "name": "Stone hut kit",
        "level": 4
      },
      {
        "slug": "stone-cottage-kit",
        "name": "Stone cottage kit",
        "level": 4
      },
      {
        "slug": "city-den-kit",
        "name": "City den kit",
        "level": 4
      },
      {
        "slug": "poke-ball-house-kit",
        "name": "Poke Ball House kit",
        "level": 4
      },
      {
        "slug": "pikachu-fountain-kit",
        "name": "Pikachu fountain kit",
        "level": 4
      },
      {
        "slug": "moonlight-dance-statue-kit",
        "name": "Moonlight dance statue kit",
        "level": 4
      },
      {
        "slug": "gray-hut-kit",
        "name": "Gray hut kit",
        "level": 4
      },
      {
        "slug": "log-cabin-kit",
        "name": "Log cabin kit",
        "level": 4
      },
      {
        "slug": "fountain-plaza-kit",
        "name": "Fountain plaza kit",
        "level": 4
      },
      {
        "slug": "skyland-flower-seeds",
        "name": "Skyland-flower seeds",
        "level": 4
      },
      {
        "slug": "tomato-seeds",
        "name": "Tomato seeds",
        "level": 4
      },
      {
        "slug": "wheat-seeds",
        "name": "Wheat seeds",
        "level": 4
      },
      {
        "slug": "small-square-rug",
        "name": "Small square rug",
        "level": 4
      },
      {
        "slug": Item.OfficeLocker,
        "name": "Office locker",
        "level": 5
      },
      {
        "slug": Item.OfficeShelf,
        "name": "Office shelf",
        "level": 5
      },
      {
        "slug": Item.PopArtSofa,
        "name": "Pop art sofa",
        "level": 5
      },
      {
        "slug": Item.Sandwiches,
        "name": "Sandwiches",
        "level": 5
      },
      {
        "slug": Item.ShavedIce,
        "name": "Shaved ice",
        "level": 5
      },
      {
        "slug": Item.RibbonCake,
        "name": "Ribbon cake",
        "level": 5
      },
      {
        "slug": Item.Newspaper,
        "name": "Newspaper",
        "level": 5
      },
      {
        "slug": Item.MagazineRack,
        "name": "Magazine rack",
        "level": 5
      },
      {
        "slug": Item.ModernSink,
        "name": "Modern sink",
        "level": 5
      },
      {
        "slug": Item.CookingStove,
        "name": "Cooking stove",
        "level": 5
      },
      {
        "slug": Item.MicrowaveOven,
        "name": "Microwave oven",
        "level": 5
      },
      {
        "slug": Item.Bathtub,
        "name": "Bathtub",
        "level": 5
      },
      {
        "slug": Item.Tablet,
        "name": "Tablet",
        "level": 5
      },
      {
        "slug": Item.Television,
        "name": "Television",
        "level": 5
      },
      {
        "slug": Item.JumbledCords,
        "name": "Jumbled cords",
        "level": 5
      },
      {
        "slug": Item.Bonfire,
        "name": "Bonfire",
        "level": 5
      },
      {
        "slug": "mini-floodgate",
        "name": "Mini floodgate",
        "level": 5
      },
      {
        "slug": Item.RedPaint,
        "name": "Red paint",
        "level": 5
      },
      {
        "slug": Item.BluePaint,
        "name": "Blue paint",
        "level": 5
      },
      {
        "slug": Item.GreenPaint,
        "name": "Green paint",
        "level": 5
      },
      {
        "slug": Item.YellowPaint,
        "name": "Yellow paint",
        "level": 5
      },
      {
        "slug": Item.PinkPaint,
        "name": "Pink paint",
        "level": 5
      },
      {
        "slug": Item.CyanPaint,
        "name": "Cyan paint",
        "level": 5
      },
      {
        "slug": Item.WhitePaint,
        "name": "White paint",
        "level": 5
      },
      {
        "slug": Item.BlackPaint,
        "name": "Black paint",
        "level": 5
      },
      {
        "slug": "leaf-house-kit",
        "name": "Leaf house kit",
        "level": 5
      },
      {
        "slug": "sand-house-kit",
        "name": "Sand house kit",
        "level": 5
      },
      {
        "slug": "stone-house-kit",
        "name": "Stone house kit",
        "level": 5
      },
      {
        "slug": "city-hut-kit",
        "name": "City hut kit",
        "level": 5
      },
      {
        "slug": "city-cottage-kit",
        "name": "City cottage kit",
        "level": 5
      },
      {
        "slug": "pokemart-kit",
        "name": "PokeMart kit",
        "level": 5
      },
      {
        "slug": "charging-station-kit",
        "name": "Charging station kit",
        "level": 5
      },
      {
        "slug": "pink-hut-kit",
        "name": "Pink hut kit",
        "level": 5
      },
      {
        "slug": "yellow-hut-kit",
        "name": "Yellow hut kit",
        "level": 5
      },
      {
        "slug": "potato-seeds",
        "name": "Potato seeds",
        "level": 5
      },
      {
        "slug": "wooden-flooring-wallpaper",
        "name": "Wooden flooring (wallpaper)",
        "level": 5
      },
      {
        "slug": "plaster-wall-wallpaper",
        "name": "Plaster wall (wallpaper)",
        "level": 5
      },
      {
        "slug": "hardwood-flooring-wallpaper",
        "name": "Hardwood flooring (wallpaper)",
        "level": 5
      },
      {
        "slug": "party-cooking-pot",
        "name": "Party cooking pot",
        "level": 5
      },
      {
        "slug": Item.StoneFireplace,
        "name": "Stone fireplace",
        "level": 6
      },
      {
        "slug": Item.VendingMachine,
        "name": "Vending machine",
        "level": 6
      },
      {
        "slug": Item.Pokemetal,
        "name": "Pokemetal",
        "level": 6
      },
      {
        "slug": "city-house-kit",
        "name": "City house kit",
        "level": 6
      },
      {
        "slug": "freezing-chambers-kit",
        "name": "Freezing chambers kit",
        "level": 6
      },
      {
        "slug": Item.TidalBell,
        "name": "Tidal Bell",
        "level": 6
      },
      {
        "slug": Item.ClearBell,
        "name": "Clear Bell",
        "level": 6
      },
      {
        "slug": "abandoned-power-plant-kit",
        "name": "Abandoned Power Plant kit",
        "level": 7
      },
      {
        "slug": "small-office-kit",
        "name": "Small office kit",
        "level": 8
      },
      {
        "slug": "relaxing-park-kit",
        "name": "Relaxing park kit",
        "level": 8
      },
      {
        "slug": "stylish-cafe-kit",
        "name": "Stylish cafe kit",
        "level": 8
      },
      {
        "slug": "concert-stage-kit",
        "name": "Concert stage kit",
        "level": 8
      },
      {
        "slug": "altar-of-flame-kit",
        "name": "Altar of Flame kit",
        "level": 8
      },
      {
        "slug": Item.PikachuSofa,
        "name": "Pikachu sofa",
        "level": 9
      },
      {
        "slug": Item.BigDrum,
        "name": "Big drum",
        "level": 9
      },
      {
        "slug": Item.PunchingGame,
        "name": "Punching game",
        "level": 9
      },
      {
        "slug": Item.InflatableBoat,
        "name": "Inflatable boat",
        "level": 9
      },
      {
        "slug": Item.PhotoCutoutBoard,
        "name": "Photo cutout board",
        "level": 9
      },
      {
        "slug": "wasteland-pokemon-center-kit",
        "name": "Wasteland Pokemon Center kit",
        "level": 10
      },
      {
        "slug": "beach-pokemon-center-kit",
        "name": "Beach Pokemon Center kit",
        "level": 10
      },
      {
        "slug": "ridge-pokemon-center-kit",
        "name": "Ridge Pokemon Center kit",
        "level": 10
      },
      {
        "slug": "skyland-pokemon-center-kit",
        "name": "Skyland Pokemon Center kit",
        "level": 10
      }
    ]
  }
} as const;
