// scripts/gen-const-files.ts
// Run: npx tsx scripts/gen-const-files.ts
// Generates app/lib/const/*.ts — rich self-contained object constants.

import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { POKEMON } from "../app/lib/data/pokemon";
import { CATEGORIES } from "../app/lib/data/categories";
import { ITEMS } from "../app/lib/data/items";
import { HABITATS } from "../app/lib/data/habitats";
import { LOCATIONS } from "../app/lib/data/locations";
import { SPECIALTIES } from "../app/lib/data/specialties";
import { HABITAT_REQUIREMENTS } from "../app/lib/data/habitat-requirements";
import { ITEM_GROUPS } from "../app/lib/data/item-groups";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toPascalCase(name: string): string {
  return name
    .split(/[\s\-_/()\[\]]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("")
    .replace(/[^A-Za-z0-9]/g, "");
}

function dedup(entries: { key: string }[]): void {
  const seen = new Map<string, number>();
  for (const e of entries) {
    const n = seen.get(e.key) ?? 0;
    seen.set(e.key, n + 1);
    if (n > 0) e.key = `${e.key}${n + 1}`;
  }
}

const banner = `// AUTO-GENERATED by scripts/gen-const-files.ts — do not edit by hand\n\n`;
const OUT_DIR = join(__dirname, "../app/lib/const");

// ---------------------------------------------------------------------------
// Build lookup maps (slug → PascalCase key)
// ---------------------------------------------------------------------------

// Items: use all ITEMS keys
const itemEntries = Object.values(ITEMS).map((item) => ({
  slug: item.slug,
  key: toPascalCase(item.name),
}));
dedup(itemEntries);
const itemKeyMap = new Map(itemEntries.map((e) => [e.slug, e.key]));

// Categories
const catEntries = Object.values(CATEGORIES).map((cat) => ({
  slug: cat.slug,
  key: toPascalCase(cat.name),
}));
dedup(catEntries);
const catKeyMap = new Map(catEntries.map((e) => [e.slug, e.key]));

// Habitat configs
const habEntries = Object.values(HABITATS).map((hab) => ({
  slug: hab.slug,
  key: toPascalCase(hab.name),
}));
dedup(habEntries);
const habKeyMap = new Map(habEntries.map((e) => [e.slug, e.key]));

// Locations
const locEntries = Object.values(LOCATIONS).map((loc) => ({
  slug: loc.slug,
  key: toPascalCase(loc.name),
}));
dedup(locEntries);
const locKeyMap = new Map(locEntries.map((e) => [e.slug, e.key]));

// Specialties
const spEntries = Object.values(SPECIALTIES).map((sp) => ({
  slug: sp.slug,
  key: toPascalCase(sp.name),
}));
dedup(spEntries);
const spKeyMap = new Map(spEntries.map((e) => [e.slug, e.key]));

// Pokemon
const pokEntries = Object.values(POKEMON).map((p) => ({
  slug: p.slug,
  key: toPascalCase(p.name),
}));
dedup(pokEntries);
const pokKeyMap = new Map(pokEntries.map((e) => [e.slug, e.key]));

// Enum-like values: collect distinct slugs from seed data
const weatherValues = [...new Set(
  Object.values(POKEMON).flatMap((p) =>
    (p.habitatList ?? []).flatMap((h) => h.weather ?? [])
  )
)].sort();
const weatherEntries = weatherValues.map((v) => ({ slug: v, key: toPascalCase(v) }));
dedup(weatherEntries);
const weatherKeyMap = new Map(weatherEntries.map((e) => [e.slug, e.key]));

const timeValues = [...new Set(
  Object.values(POKEMON).flatMap((p) =>
    (p.habitatList ?? []).flatMap((h) => h.time ?? [])
  )
)].sort();
const timeEntries = timeValues.map((v) => ({ slug: v, key: toPascalCase(v) }));
dedup(timeEntries);
const timeKeyMap = new Map(timeEntries.map((e) => [e.slug, e.key]));

const rarityValues = [...new Set(
  Object.values(POKEMON).flatMap((p) =>
    (p.habitatList ?? []).map((h) => h.rarity).filter(Boolean)
  )
)].sort() as string[];
const rarityEntries = rarityValues.map((v) => ({ slug: v, key: toPascalCase(v) }));
dedup(rarityEntries);
const rarityKeyMap = new Map(rarityEntries.map((e) => [e.slug, e.key]));

const flavorValues = [...new Set(
  Object.values(POKEMON).map((p) => p.flavor).filter(Boolean)
)].sort() as string[];
const flavorEntries = flavorValues.map((v) => ({ slug: v, key: toPascalCase(v) }));
dedup(flavorEntries);
const flavorKeyMap = new Map(flavorEntries.map((e) => [e.slug, e.key]));

const phValues = [...new Set(
  Object.values(POKEMON).map((p) => p.habitat).filter(Boolean)
)].sort() as string[];
const phEntries = phValues.map((v) => ({ slug: v, key: toPascalCase(v) }));
dedup(phEntries);
const phKeyMap = new Map(phEntries.map((e) => [e.slug, e.key]));

// ---------------------------------------------------------------------------
// Utility: generate a label from a slug value
// ---------------------------------------------------------------------------
function slugToLabel(slug: string): string {
  return slug.charAt(0).toUpperCase() + slug.slice(1);
}

// ---------------------------------------------------------------------------
// 1. Generate enum.ts
// ---------------------------------------------------------------------------

function genEnumTs(): string {
  let out = banner;

  // Weather
  out += `/** Weather conditions */\nexport const Weather = {\n`;
  for (const e of weatherEntries) {
    out += `  ${e.key}:    { slug: "${e.slug}", label: "${slugToLabel(e.slug)}" },\n`;
  }
  out += `} as const;\nexport type WeatherConst = typeof Weather[keyof typeof Weather];\n\n`;

  // Time
  out += `/** Time of day */\nexport const Time = {\n`;
  for (const e of timeEntries) {
    out += `  ${e.key}:      { slug: "${e.slug}", label: "${slugToLabel(e.slug)}" },\n`;
  }
  out += `} as const;\nexport type TimeConst = typeof Time[keyof typeof Time];\n\n`;

  // Rarity
  out += `/** Spawn rarity */\nexport const Rarity = {\n`;
  for (const e of rarityEntries) {
    out += `  ${e.key}:   { slug: "${e.slug}", label: "${slugToLabel(e.slug)}" },\n`;
  }
  out += `} as const;\nexport type RarityConst = typeof Rarity[keyof typeof Rarity];\n\n`;

  // Flavor
  out += `/** Berry flavor preferences */\nexport const Flavor = {\n`;
  for (const e of flavorEntries) {
    out += `  ${e.key}:   { slug: "${e.slug}", label: "${slugToLabel(e.slug)}" },\n`;
  }
  out += `} as const;\nexport type FlavorConst = typeof Flavor[keyof typeof Flavor];\n\n`;

  // PokemonHabitat
  out += `/** Pokemon top-level habitat types */\nexport const PokemonHabitat = {\n`;
  for (const e of phEntries) {
    out += `  ${e.key}: { slug: "${e.slug}", label: "${slugToLabel(e.slug)}" },\n`;
  }
  out += `} as const;\nexport type PokemonHabitatConst = typeof PokemonHabitat[keyof typeof PokemonHabitat];\n`;

  return out;
}

// ---------------------------------------------------------------------------
// 2. Generate items.ts
// ---------------------------------------------------------------------------

function genItemsTs(): string {
  let out = banner;
  out += `export const Item = {\n`;
  for (const e of itemEntries) {
    const item = ITEMS[e.slug];
    const iconVal = item?.icon ? `"${item.icon}"` : "null";
    const label = item?.name ?? e.slug;
    out += `  ${e.key}: { slug: "${e.slug}", label: "${label.replace(/"/g, '\\"')}", icon: ${iconVal} },\n`;
  }
  out += `} as const;\nexport type ItemConst = typeof Item[keyof typeof Item];\nexport type ItemKey = keyof typeof Item;\n`;
  return out;
}

// ---------------------------------------------------------------------------
// 3. Generate categories.ts
// ---------------------------------------------------------------------------

function genCategoriesTs(): string {
  let out = banner;
  out += `import { Item, type ItemConst } from "./items";\n\n`;
  out += `export const Category = {\n`;
  let unresolved = 0;
  for (const e of catEntries) {
    const cat = CATEGORIES[e.slug];
    out += `  ${e.key}: {\n`;
    out += `    slug: "${e.slug}",\n`;
    out += `    label: "${(cat?.name ?? e.slug).replace(/"/g, '\\"')}",\n`;
    out += `    items: [\n`;
    for (const itemSlug of (cat?.items ?? [])) {
      const ik = itemKeyMap.get(itemSlug);
      if (!ik) {
        console.warn(`[categories] Unresolved item slug: ${itemSlug} in category ${e.slug}`);
        unresolved++;
        continue;
      }
      out += `      Item.${ik},\n`;
    }
    out += `    ] as ItemConst[],\n`;
    out += `  },\n`;
  }
  out += `} as const;\nexport type CategoryConst = typeof Category[keyof typeof Category];\nexport type CategoryKey = keyof typeof Category;\n`;
  if (unresolved > 0) console.warn(`[categories] Total unresolved items: ${unresolved}`);
  return out;
}

// ---------------------------------------------------------------------------
// 4. Generate specialties.ts
// ---------------------------------------------------------------------------

function genSpecialtiesTs(): string {
  let out = banner;
  out += `export const Specialty = {\n`;
  for (const e of spEntries) {
    const sp = SPECIALTIES[e.slug];
    const label = sp?.name ?? e.slug;
    const desc = (sp?.description ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    out += `  ${e.key}: { slug: "${e.slug}", label: "${label.replace(/"/g, '\\"')}", description: "${desc}" },\n`;
  }
  out += `} as const;\nexport type SpecialtyConst = typeof Specialty[keyof typeof Specialty];\nexport type SpecialtyKey = keyof typeof Specialty;\n`;
  return out;
}

// ---------------------------------------------------------------------------
// 5. Generate habitat-config.ts
// ---------------------------------------------------------------------------

function genHabitatConfigTs(): string {
  let out = banner;
  out += `import { Item, type ItemConst } from "./items";\n\n`;

  out += `export type HabitatRequirementItem = {\n`;
  out += `  type: "item";\n`;
  out += `  item: ItemConst;\n`;
  out += `  label: string;\n`;
  out += `  qty: number;\n`;
  out += `};\n\n`;
  out += `export type HabitatRequirementGroup = {\n`;
  out += `  type: "group";\n`;
  out += `  groupKey: string;\n`;
  out += `  label: string;\n`;
  out += `  qty: number;\n`;
  out += `};\n\n`;
  out += `export type HabitatRequirementConst = HabitatRequirementItem | HabitatRequirementGroup;\n\n`;

  out += `export const HabitatConfig = {\n`;
  let unresolved = 0;
  for (const e of habEntries) {
    const hab = HABITATS[e.slug];
    const desc = (hab?.description ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    out += `  ${e.key}: {\n`;
    out += `    slug: "${e.slug}",\n`;
    out += `    label: "${(hab?.name ?? e.slug).replace(/"/g, '\\"')}",\n`;
    out += `    description: "${desc}",\n`;
    out += `    requirements: [\n`;
    const reqs = HABITAT_REQUIREMENTS[e.slug] ?? [];
    for (const req of reqs) {
      const label = req.name.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      if (req.type === "item") {
        const ik = itemKeyMap.get(req.value);
        if (!ik) {
          console.warn(`[habitat-config] Unresolved item slug: ${req.value} in ${e.slug}`);
          unresolved++;
          continue;
        }
        out += `      { type: "item" as const, item: Item.${ik}, label: "${label}", qty: ${req.qty} },\n`;
      } else {
        // group type: req.value is the group key
        out += `      { type: "group" as const, groupKey: "${req.value}", label: "${label}", qty: ${req.qty} },\n`;
      }
    }
    out += `    ] as HabitatRequirementConst[],\n`;
    out += `  },\n`;
  }
  out += `} as const;\nexport type HabitatConfigConst = typeof HabitatConfig[keyof typeof HabitatConfig];\nexport type HabitatConfigKey = keyof typeof HabitatConfig;\n`;
  if (unresolved > 0) console.warn(`[habitat-config] Total unresolved items: ${unresolved}`);
  return out;
}

// ---------------------------------------------------------------------------
// 6. Generate locations.ts
// ---------------------------------------------------------------------------

function genLocationsTs(): string {
  let out = banner;
  out += `import { Item, type ItemConst } from "./items";\n\n`;

  out += `export type ShopItemConst = {\n`;
  out += `  readonly item: ItemConst;\n`;
  out += `  readonly level: number;\n`;
  out += `};\n\n`;

  out += `export const Location = {\n`;
  let unresolved = 0;
  for (const e of locEntries) {
    const loc = LOCATIONS[e.slug];
    const desc = (loc?.description ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    const obj = (loc?.objective ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');

    const resolveItems = (slugs: readonly string[], context: string): string[] => {
      const resolved: string[] = [];
      for (const s of slugs) {
        const ik = itemKeyMap.get(s);
        if (!ik) {
          // Only warn for non-known unresolved slugs
          console.warn(`[locations:${context}] Unresolved item slug: ${s}`);
          unresolved++;
          continue;
        }
        resolved.push(`Item.${ik}`);
      }
      return resolved;
    };

    out += `  ${e.key}: {\n`;
    out += `    slug: "${e.slug}",\n`;
    out += `    label: "${(loc?.name ?? e.slug).replace(/"/g, '\\"')}",\n`;
    out += `    description: "${desc}",\n`;
    out += `    objective: "${obj}",\n`;

    const materials = resolveItems(loc?.materials ?? [], `${e.slug}/materials`);
    out += `    materials: [${materials.length ? "\n      " + materials.join(",\n      ") + ",\n    " : ""}] as ItemConst[],\n`;

    const blocksAndPlants = resolveItems(loc?.blocksAndPlants ?? [], `${e.slug}/blocksAndPlants`);
    out += `    blocksAndPlants: [${blocksAndPlants.length ? "\n      " + blocksAndPlants.join(",\n      ") + ",\n    " : ""}] as ItemConst[],\n`;

    const itemsInArea = resolveItems(loc?.itemsInArea ?? [], `${e.slug}/itemsInArea`);
    out += `    itemsInArea: [${itemsInArea.length ? "\n      " + itemsInArea.join(",\n      ") + ",\n    " : ""}] as ItemConst[],\n`;

    const itemsInPokeballs = resolveItems(loc?.itemsInPokeballs ?? [], `${e.slug}/itemsInPokeballs`);
    out += `    itemsInPokeballs: [${itemsInPokeballs.length ? "\n      " + itemsInPokeballs.join(",\n      ") + ",\n    " : ""}] as ItemConst[],\n`;

    const treasure = resolveItems(loc?.treasure ?? [], `${e.slug}/treasure`);
    out += `    treasure: [${treasure.length ? "\n      " + treasure.join(",\n      ") + ",\n    " : ""}] as ItemConst[],\n`;

    out += `    shopItems: [\n`;
    for (const si of (loc?.shopItems ?? [])) {
      const ik = itemKeyMap.get(si.slug);
      if (!ik) {
        console.warn(`[locations:${e.slug}/shopItems] Unresolved item slug: ${si.slug}`);
        unresolved++;
        continue;
      }
      out += `      { item: Item.${ik}, level: ${si.level} },\n`;
    }
    out += `    ] as ShopItemConst[],\n`;
    out += `  },\n`;
  }
  out += `} as const;\nexport type LocationConst = typeof Location[keyof typeof Location];\nexport type LocationKey = keyof typeof Location;\n`;
  if (unresolved > 0) console.warn(`[locations] Total unresolved items: ${unresolved}`);
  return out;
}

// ---------------------------------------------------------------------------
// 7. Generate pokemon.ts
// ---------------------------------------------------------------------------

function genPokemonTs(): string {
  let out = banner;
  out += `import { Category, type CategoryConst } from "./categories";\n`;
  out += `import { HabitatConfig, type HabitatConfigConst } from "./habitat-config";\n`;
  out += `import { Location, type LocationConst } from "./locations";\n`;
  out += `import { Specialty, type SpecialtyConst } from "./specialties";\n`;
  out += `import {\n`;
  out += `  PokemonHabitat, Flavor, Rarity, Time, Weather,\n`;
  out += `  type PokemonHabitatConst, type FlavorConst, type RarityConst,\n`;
  out += `  type TimeConst, type WeatherConst,\n`;
  out += `} from "./enum";\n\n`;

  out += `export type HabitatListConst = {\n`;
  out += `  readonly habitat: HabitatConfigConst;\n`;
  out += `  readonly locations: readonly LocationConst[];\n`;
  out += `  readonly rarity: RarityConst | null;\n`;
  out += `  readonly time: readonly TimeConst[];\n`;
  out += `  readonly weather: readonly WeatherConst[];\n`;
  out += `  readonly isCloudIsland: boolean;\n`;
  out += `};\n\n`;

  out += `/** Explicit interface — avoids TypeScript union-intersection complexity with large \`as const\` objects */\n`;
  out += `export type PokemonConst = {\n`;
  out += `  readonly slug: string;\n`;
  out += `  readonly label: string;\n`;
  out += `  readonly num: number;\n`;
  out += `  readonly nationalDexNum: number | null;\n`;
  out += `  readonly icon: string;\n`;
  out += `  readonly spriteHq: string | null;\n`;
  out += `  readonly types: string[];\n`;
  out += `  readonly habitat: PokemonHabitatConst;\n`;
  out += `  readonly flavor: FlavorConst | null;\n`;
  out += `  readonly categories: readonly CategoryConst[];\n`;
  out += `  readonly specialties: readonly SpecialtyConst[];\n`;
  out += `  readonly primaryLocation: LocationConst | null;\n`;
  out += `  readonly habitatList: readonly HabitatListConst[];\n`;
  out += `};\n`;
  out += `export type PokemonKey = string;\n\n`;

  out += `export const Pokemon: Record<string, PokemonConst> = {\n`;
  let warnings = 0;

  for (const e of pokEntries) {
    const p = POKEMON[e.slug];
    if (!p) continue;

    out += `  ${e.key}: {\n`;
    out += `    slug: "${p.slug}",\n`;
    out += `    label: "${p.name.replace(/"/g, '\\"')}",\n`;
    out += `    num: ${p.num},\n`;
    out += `    nationalDexNum: ${p.nationalDexNum ?? "null"},\n`;
    out += `    icon: "${p.icon}",\n`;
    out += `    spriteHq: ${p.spriteHq ? `"${p.spriteHq}"` : "null"},\n`;

    const types = p.types ?? [];
    out += `    types: [${types.map((t) => `"${t}"`).join(", ")}] as string[],\n`;

    // habitat
    const phKey = phKeyMap.get(p.habitat);
    if (!phKey) {
      console.warn(`[pokemon] ${e.slug}: Unresolved habitat: ${p.habitat}`);
      warnings++;
      out += `    habitat: PokemonHabitat.Dry, // WARN: unresolved ${p.habitat}\n`;
    } else {
      out += `    habitat: PokemonHabitat.${phKey},\n`;
    }

    // flavor
    if (p.flavor) {
      const fKey = flavorKeyMap.get(p.flavor);
      if (!fKey) {
        console.warn(`[pokemon] ${e.slug}: Unresolved flavor: ${p.flavor}`);
        warnings++;
        out += `    flavor: null,\n`;
      } else {
        out += `    flavor: Flavor.${fKey},\n`;
      }
    } else {
      out += `    flavor: null,\n`;
    }

    // categories
    out += `    categories: [\n`;
    for (const catSlug of (p.categories ?? [])) {
      const ck = catKeyMap.get(catSlug);
      if (!ck) {
        console.warn(`[pokemon] ${e.slug}: Unresolved category slug: ${catSlug}`);
        warnings++;
        continue;
      }
      out += `      Category.${ck},\n`;
    }
    out += `    ] as CategoryConst[],\n`;

    // specialties
    out += `    specialties: [\n`;
    for (const spSlug of (p.specialties ?? [])) {
      const sk = spKeyMap.get(spSlug);
      if (!sk) {
        console.warn(`[pokemon] ${e.slug}: Unresolved specialty slug: ${spSlug}`);
        warnings++;
        continue;
      }
      out += `      Specialty.${sk},\n`;
    }
    out += `    ] as SpecialtyConst[],\n`;

    // primaryLocation
    if (p.primaryLocation) {
      const lk = locKeyMap.get(p.primaryLocation);
      if (!lk) {
        console.warn(`[pokemon] ${e.slug}: Unresolved primaryLocation: ${p.primaryLocation}`);
        warnings++;
        out += `    primaryLocation: null,\n`;
      } else {
        out += `    primaryLocation: Location.${lk},\n`;
      }
    } else {
      out += `    primaryLocation: null,\n`;
    }

    // habitatList
    out += `    habitatList: [\n`;
    for (const h of (p.habitatList ?? [])) {
      const hk = habKeyMap.get(h.habitatSlug);
      if (!hk) {
        console.warn(`[pokemon] ${e.slug}: Unresolved habitatSlug: ${h.habitatSlug}`);
        warnings++;
        continue;
      }

      out += `      {\n`;
      out += `        habitat: HabitatConfig.${hk},\n`;
      out += `        locations: [\n`;
      for (const locSlug of (h.locations ?? [])) {
        const lk = locKeyMap.get(locSlug);
        if (!lk) {
          console.warn(`[pokemon] ${e.slug}: Unresolved location slug: ${locSlug}`);
          warnings++;
          continue;
        }
        out += `          Location.${lk},\n`;
      }
      out += `        ] as LocationConst[],\n`;

      // rarity
      if (h.rarity) {
        const rk = rarityKeyMap.get(h.rarity);
        if (!rk) {
          console.warn(`[pokemon] ${e.slug}: Unresolved rarity: ${h.rarity}`);
          warnings++;
          out += `        rarity: null,\n`;
        } else {
          out += `        rarity: Rarity.${rk},\n`;
        }
      } else {
        out += `        rarity: null,\n`;
      }

      // time
      out += `        time: [\n`;
      for (const t of (h.time ?? [])) {
        const tk = timeKeyMap.get(t);
        if (!tk) {
          console.warn(`[pokemon] ${e.slug}: Unresolved time: ${t}`);
          warnings++;
          continue;
        }
        out += `          Time.${tk},\n`;
      }
      out += `        ] as TimeConst[],\n`;

      // weather
      out += `        weather: [\n`;
      for (const w of (h.weather ?? [])) {
        const wk = weatherKeyMap.get(w);
        if (!wk) {
          console.warn(`[pokemon] ${e.slug}: Unresolved weather: ${w}`);
          warnings++;
          continue;
        }
        out += `          Weather.${wk},\n`;
      }
      out += `        ] as WeatherConst[],\n`;

      out += `        isCloudIsland: ${h.isCloudIsland},\n`;
      out += `      } as HabitatListConst,\n`;
    }
    out += `    ],\n`;

    out += `  },\n`;
  }

  out += `};\n`;
  if (warnings > 0) console.warn(`[pokemon] Total warnings: ${warnings}`);
  return out;
}

// ---------------------------------------------------------------------------
// 8. Generate derived.ts
// ---------------------------------------------------------------------------

function genDerivedTs(): string {
  return `${banner}import { Pokemon, type PokemonConst } from "./pokemon";
import { type SpecialtyConst } from "./specialties";
import { type HabitatConfigConst } from "./habitat-config";
import { type CategoryConst } from "./categories";
import { type PokemonHabitatConst } from "./enum";

/** All pokemon sorted by national dex number (game-exclusives last) */
export const POKEMON_LIST: PokemonConst[] = Object.values(Pokemon)
  .sort((a, b) => {
    const na = a.nationalDexNum ?? 99999;
    const nb = b.nationalDexNum ?? 99999;
    return na !== nb ? na - nb : a.num - b.num;
  });

/** Pokemon keyed by slug for O(1) lookup */
export const POKEMON_BY_SLUG: Record<string, PokemonConst> = Object.fromEntries(
  Object.values(Pokemon).map((p) => [p.slug, p])
);

/** Pokemon grouped by specialty slug */
export const POKEMON_BY_SPECIALTY: Record<string, PokemonConst[]> = {};
for (const p of POKEMON_LIST) {
  for (const s of p.specialties) {
    (POKEMON_BY_SPECIALTY[s.slug] ??= []).push(p);
  }
}

/** Pokemon grouped by habitat config slug */
export const POKEMON_BY_HABITAT_CONFIG: Record<string, PokemonConst[]> = {};
for (const p of POKEMON_LIST) {
  for (const h of p.habitatList) {
    (POKEMON_BY_HABITAT_CONFIG[h.habitat.slug] ??= []).push(p);
  }
}

/** Zero-padded dex number for display */
export function dexNum(p: PokemonConst): string {
  return String(p.nationalDexNum ?? p.num).padStart(3, "0");
}

/** Icon URL for a pokemon */
export function pkmnIconUrl(p: PokemonConst): string {
  return \`/icons/pokemon/\${p.icon}\`;
}
`;
}

// ---------------------------------------------------------------------------
// 9. Generate index.ts
// ---------------------------------------------------------------------------

function genIndexTs(): string {
  return `${banner}export * from "./enum";
export * from "./items";
export * from "./categories";
export * from "./habitat-config";
export * from "./locations";
export * from "./specialties";
export * from "./pokemon";
export * from "./derived";
`;
}

// ---------------------------------------------------------------------------
// Write all files
// ---------------------------------------------------------------------------

mkdirSync(OUT_DIR, { recursive: true });

const files: Array<{ name: string; content: string }> = [
  { name: "enum.ts", content: genEnumTs() },
  { name: "items.ts", content: genItemsTs() },
  { name: "categories.ts", content: genCategoriesTs() },
  { name: "specialties.ts", content: genSpecialtiesTs() },
  { name: "habitat-config.ts", content: genHabitatConfigTs() },
  { name: "locations.ts", content: genLocationsTs() },
  { name: "pokemon.ts", content: genPokemonTs() },
  { name: "derived.ts", content: genDerivedTs() },
  { name: "index.ts", content: genIndexTs() },
];

console.log("\n=== gen-const-files.ts ===\n");
for (const f of files) {
  const path = join(OUT_DIR, f.name);
  writeFileSync(path, f.content, "utf8");
  const lines = f.content.split("\n").length;
  console.log(`  Wrote ${path} (${lines} lines)`);
}

// Print summary counts
console.log("\nSummary:");
console.log(`  Items:           ${itemEntries.length}`);
console.log(`  Categories:      ${catEntries.length}`);
console.log(`  HabitatConfigs:  ${habEntries.length}`);
console.log(`  Locations:       ${locEntries.length}`);
console.log(`  Specialties:     ${spEntries.length}`);
console.log(`  Pokemon:         ${pokEntries.length}`);
console.log(`  Weather values:  ${weatherEntries.length}`);
console.log(`  Time values:     ${timeEntries.length}`);
console.log(`  Rarity values:   ${rarityEntries.length}`);
console.log(`  Flavor values:   ${flavorEntries.length}`);
console.log(`  PokemonHabitat:  ${phEntries.length}`);
console.log("\nDone.\n");
