/**
 * scripts/rewrite-data-files.ts
 * Rewrites all app/lib/data/*.ts files to replace raw slug strings
 * with typed constant references from app/lib/data/consts.ts.
 *
 * Uses scripts/consts-map.json (generated by gen-consts.ts) as the slug lookup.
 *
 * Run AFTER gen-consts.ts:
 *   npx tsx scripts/rewrite-data-files.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const root = join(__dirname, "..");

// ---------------------------------------------------------------------------
// Load the consts map
// ---------------------------------------------------------------------------
const mapPath = join(root, "scripts", "consts-map.json");
const constsMap: Record<string, string> = JSON.parse(
  readFileSync(mapPath, "utf-8")
);

// Build per-type slug -> constant-ref maps
const categoryMap = new Map<string, string>();
const habitatConfigMap = new Map<string, string>();
const locationMap = new Map<string, string>();
const specialtyMap = new Map<string, string>();
const pokemonHabitatMap = new Map<string, string>(); // display name → ref
const weatherMap = new Map<string, string>();
const timeMap = new Map<string, string>();
const rarityMap = new Map<string, string>();
const flavorMap = new Map<string, string>();
const itemMap = new Map<string, string>();
const pokemonRefMap = new Map<string, string>();

for (const [key, ref] of Object.entries(constsMap)) {
  const parts = key.split("::");
  const type = parts[0]!;
  const slug = parts[1]!;
  switch (type) {
    case "Category":       categoryMap.set(slug, ref); break;
    case "HabitatConfig":  habitatConfigMap.set(slug, ref); break;
    case "Location":       locationMap.set(slug, ref); break;
    case "Specialty":      specialtyMap.set(slug, ref); break;
    case "PokemonHabitat": pokemonHabitatMap.set(slug, ref); break; // slug = display name e.g. "Dry"
    case "Weather":        weatherMap.set(slug, ref); break;
    case "Time":           timeMap.set(slug, ref); break;
    case "Rarity":         rarityMap.set(slug, ref); break;
    case "Flavor":         flavorMap.set(slug, ref); break;
    case "Item":           itemMap.set(slug, ref); break;
    case "Pokemon":        pokemonRefMap.set(slug, ref); break;
  }
}

let replacementCount = 0;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Replace all quoted slug values inside a named array field.
 *  Handles both quoted keys ("fieldName": [...]) and unquoted keys (fieldName: [...]).
 */
function replaceInArrayField(
  text: string,
  fieldName: string,
  map: Map<string, string>
): string {
  const startPattern = new RegExp(`"?${fieldName}"?:\\s*\\[`, "g");
  let result = "";
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = startPattern.exec(text)) !== null) {
    const startIdx = match.index + match[0].length;
    // Find the matching closing bracket
    let depth = 1;
    let i = startIdx;
    while (i < text.length && depth > 0) {
      if (text[i] === "[") depth++;
      else if (text[i] === "]") depth--;
      i++;
    }
    const beforeAndStart = text.slice(lastIndex, match.index + match[0].length);
    let arrayContent = text.slice(startIdx, i - 1);
    const closingBracket = text[i - 1];

    for (const [slug, ref] of map) {
      const escaped = slug.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const re = new RegExp(`"${escaped}"`, "g");
      const prevLen = arrayContent.length;
      const newContent = arrayContent.replace(re, ref);
      if (newContent !== arrayContent) {
        const delta = Math.floor(
          (newContent.length - prevLen) / (ref.length - slug.length - 2)
        );
        replacementCount += Math.max(1, delta);
      }
      arrayContent = newContent;
    }

    result += beforeAndStart + arrayContent + closingBracket;
    lastIndex = i;
  }

  result += text.slice(lastIndex);
  return result;
}

/** Replace "fieldName": "slug" single-value fields. */
function replaceSingleField(
  text: string,
  fieldName: string,
  map: Map<string, string>
): string {
  return text.replace(
    new RegExp(`"${fieldName}":\\s*"([^"]+)"`, "g"),
    (match, slug) => {
      const ref = map.get(slug);
      if (ref) { replacementCount++; return `"${fieldName}": ${ref}`; }
      return match;
    }
  );
}

/** Ensure import line is present in a file, inserting after the last import. */
function ensureImport(text: string, importLine: string): string {
  if (text.includes(importLine)) return text;
  // Insert after last import statement
  const importBlockEnd = text.lastIndexOf("\nimport ");
  if (importBlockEnd === -1) {
    // No imports found — prepend
    return importLine + "\n\n" + text;
  }
  // Find end of that import line
  const lineEnd = text.indexOf("\n", importBlockEnd + 1);
  if (lineEnd === -1) return text + "\n" + importLine;
  return text.slice(0, lineEnd + 1) + importLine + "\n" + text.slice(lineEnd + 1);
}

// ---------------------------------------------------------------------------
// 1. pokemon.ts
// ---------------------------------------------------------------------------
{
  const pokemonPath = join(root, "app", "lib", "data", "pokemon.ts");
  let src = readFileSync(pokemonPath, "utf-8");

  // Array fields
  src = replaceInArrayField(src, "categories", categoryMap);
  src = replaceInArrayField(src, "specialties", specialtyMap);
  src = replaceInArrayField(src, "locations", locationMap);
  src = replaceInArrayField(src, "weather", weatherMap);
  src = replaceInArrayField(src, "time", timeMap);

  // Single-value fields
  src = replaceSingleField(src, "primaryLocation", locationMap);
  src = replaceSingleField(src, "rarity", rarityMap);
  src = replaceSingleField(src, "flavor", flavorMap);

  // Replace "habitat": "DisplayName" (top-level field) -> PokemonHabitat.X
  src = src.replace(/"habitat":\s*"([^"]+)"/g, (match, val) => {
    const ref = pokemonHabitatMap.get(val);
    if (ref) { replacementCount++; return `"habitat": ${ref}`; }
    return match;
  });

  // FIRST: Remove top-level pokemon "habitatSlug" field (4-space indent)
  // Handles both raw strings ("dry") and already-converted refs (PokemonHabitat.Dry)
  // Pattern: line with <=4 spaces of indent, "habitatSlug": <anything>
  src = src.replace(/^([ \t]{0,4})"habitatSlug":[^\n]+\n?/gm, (match, indent) => {
    const indentLen = indent.replace(/\t/g, "  ").length;
    if (indentLen <= 4) {
      replacementCount++;
      return ""; // remove the line
    }
    return match;
  });

  // THEN: Replace "habitatSlug": "slug" inside habitatList objects (indented > 4) -> HabitatConfig
  src = src.replace(
    /([ \t]*)"habitatSlug":\s*"([^"]+)"/g,
    (match, indent, slug) => {
      const ref = habitatConfigMap.get(slug);
      if (ref) {
        replacementCount++;
        return `${indent}"habitatSlug": ${ref}`;
      }
      return match;
    }
  );

  // Ensure import is correct
  const pokemonImport = `import { Category, HabitatConfig, Location, Specialty, PokemonHabitat, Weather, Time, Rarity, Flavor } from "./consts";`;
  src = ensureImport(src, pokemonImport);

  writeFileSync(pokemonPath, src, "utf-8");
  console.log(`Rewrote ${pokemonPath}`);
}

// ---------------------------------------------------------------------------
// 2. categories.ts — items arrays -> Item constants
// ---------------------------------------------------------------------------
{
  const filePath = join(root, "app", "lib", "data", "categories.ts");
  let src = readFileSync(filePath, "utf-8");

  src = replaceInArrayField(src, "items", itemMap);

  src = ensureImport(src, `import { Item } from "./consts";`);

  writeFileSync(filePath, src, "utf-8");
  console.log(`Rewrote ${filePath}`);
}

// ---------------------------------------------------------------------------
// 3. habitats.ts — pokemon arrays -> Pokemon constants
// ---------------------------------------------------------------------------
{
  const filePath = join(root, "app", "lib", "data", "habitats.ts");
  let src = readFileSync(filePath, "utf-8");

  src = replaceInArrayField(src, "pokemon", pokemonRefMap);

  src = ensureImport(src, `import { Pokemon } from "./consts";`);

  writeFileSync(filePath, src, "utf-8");
  console.log(`Rewrote ${filePath}`);
}

// ---------------------------------------------------------------------------
// 4. specialties.ts — pokemon arrays -> Pokemon constants
// ---------------------------------------------------------------------------
{
  const filePath = join(root, "app", "lib", "data", "specialties.ts");
  let src = readFileSync(filePath, "utf-8");

  src = replaceInArrayField(src, "pokemon", pokemonRefMap);

  src = ensureImport(src, `import { Pokemon } from "./consts";`);

  writeFileSync(filePath, src, "utf-8");
  console.log(`Rewrote ${filePath}`);
}

// ---------------------------------------------------------------------------
// 5. locations.ts — item slug arrays -> Item constants
// ---------------------------------------------------------------------------
{
  const filePath = join(root, "app", "lib", "data", "locations.ts");
  let src = readFileSync(filePath, "utf-8");

  // Replace item arrays
  src = replaceInArrayField(src, "materials", itemMap);
  src = replaceInArrayField(src, "blocksAndPlants", itemMap);
  src = replaceInArrayField(src, "itemsInArea", itemMap);
  src = replaceInArrayField(src, "itemsInPokeballs", itemMap);
  src = replaceInArrayField(src, "treasure", itemMap);

  // Replace shopItems[].slug field
  src = src.replace(/"slug":\s*"([^"]+)"/g, (match, slug) => {
    const ref = itemMap.get(slug);
    if (ref) { replacementCount++; return `"slug": ${ref}`; }
    return match;
  });

  src = ensureImport(src, `import { Item } from "./consts";`);

  writeFileSync(filePath, src, "utf-8");
  console.log(`Rewrote ${filePath}`);
}

// ---------------------------------------------------------------------------
// 6. habitat-requirements.ts — item value fields -> Item constants
// ---------------------------------------------------------------------------
{
  const filePath = join(root, "app", "lib", "data", "habitat-requirements.ts");
  let src = readFileSync(filePath, "utf-8");

  // Replace "value": "item-slug" only for type=item entries
  // Strategy: use context matching to only replace when preceded by "type": "item"
  // Process block by block: find each object in the array
  // Simpler approach: replace "value": "slug" only when the slug exists in itemMap
  // (group keys like "bed", "seat" won't match itemMap, so they're left alone)
  src = src.replace(/"value":\s*"([^"]+)"/g, (match, slug) => {
    const ref = itemMap.get(slug);
    if (ref) { replacementCount++; return `"value": ${ref}`; }
    return match;
  });

  src = ensureImport(src, `import { Item } from "./consts";`);

  writeFileSync(filePath, src, "utf-8");
  console.log(`Rewrote ${filePath}`);
}

// ---------------------------------------------------------------------------
// 7. crafting.ts — materials[].slug -> Item constants
// ---------------------------------------------------------------------------
{
  const filePath = join(root, "app", "lib", "data", "crafting.ts");
  let src = readFileSync(filePath, "utf-8");

  // Replace "slug": "item-slug" in materials
  src = src.replace(/"slug":\s*"([^"]+)"/g, (match, slug) => {
    const ref = itemMap.get(slug);
    if (ref) { replacementCount++; return `"slug": ${ref}`; }
    return match;
  });

  src = ensureImport(src, `import { Item } from "./consts";`);

  writeFileSync(filePath, src, "utf-8");
  console.log(`Rewrote ${filePath}`);
}

// ---------------------------------------------------------------------------
// 8. item-groups.ts — item slug values in arrays -> Item constants
//    Keys of the outer Record stay as raw strings; only array element values change.
// ---------------------------------------------------------------------------
{
  const filePath = join(root, "app", "lib", "data", "item-groups.ts");
  let src = readFileSync(filePath, "utf-8");

  // Replace only array element values (strings inside [...])
  // Use replaceInArrayField approach — but the keys are arbitrary group names,
  // so we can't name them. Instead, use regex to match the array body patterns.
  // Strategy: parse line by line and replace quoted strings that appear as array elements.
  // A line that is an array element looks like: whitespace + "slug", or whitespace + "slug"
  // (indented by at least 2 spaces and not followed by : indicating an object key)
  const lines = src.split("\n");
  const newLines = lines.map((line) => {
    // Match lines that are array elements: leading whitespace, then a quoted string, optional comma
    // NOT object keys (which would have : after the closing quote)
    const arrayElemMatch = line.match(/^(\s+)"([^"]+)"(\s*,?\s*)$/);
    if (arrayElemMatch) {
      const [, indent, slug, trailing] = arrayElemMatch as [string, string, string, string];
      const ref = itemMap.get(slug);
      if (ref) {
        replacementCount++;
        return `${indent}${ref}${trailing}`;
      }
    }
    return line;
  });
  src = newLines.join("\n");

  src = ensureImport(src, `import { Item } from "./consts";`);

  writeFileSync(filePath, src, "utf-8");
  console.log(`Rewrote ${filePath}`);
}

console.log(`\nTotal replacements: ${replacementCount}`);
