/**
 * scripts/rewrite-data-files.ts
 * Rewrites app/lib/data/pokemon.ts to replace raw slug strings
 * with typed constant references from app/lib/data/consts.ts.
 *
 * Uses scripts/consts-map.json (generated by gen-consts.ts) as the slug lookup.
 *
 * Run AFTER gen-consts.ts:
 *   npx tsx scripts/rewrite-data-files.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const root = join(__dirname, "..");

// ---------------------------------------------------------------------------
// Load the consts map
// ---------------------------------------------------------------------------
const mapPath = join(root, "scripts", "consts-map.json");
const constsMap: Record<string, string> = JSON.parse(
  readFileSync(mapPath, "utf-8")
);

// Build per-type slug -> constant-ref maps
const categoryMap = new Map<string, string>();
const habitatConfigMap = new Map<string, string>();
const locationMap = new Map<string, string>();
const specialtyMap = new Map<string, string>();
const pokemonHabitatMap = new Map<string, string>();
const weatherMap = new Map<string, string>();
const timeMap = new Map<string, string>();
const rarityMap = new Map<string, string>();
const flavorMap = new Map<string, string>();

for (const [key, ref] of Object.entries(constsMap)) {
  const parts = key.split("::");
  const type = parts[0]!;
  const slug = parts[1]!;
  switch (type) {
    case "Category":       categoryMap.set(slug, ref); break;
    case "HabitatConfig":  habitatConfigMap.set(slug, ref); break;
    case "Location":       locationMap.set(slug, ref); break;
    case "Specialty":      specialtyMap.set(slug, ref); break;
    case "PokemonHabitat": pokemonHabitatMap.set(slug, ref); break;
    case "Weather":        weatherMap.set(slug, ref); break;
    case "Time":           timeMap.set(slug, ref); break;
    case "Rarity":         rarityMap.set(slug, ref); break;
    case "Flavor":         flavorMap.set(slug, ref); break;
  }
}

// ---------------------------------------------------------------------------
// Read pokemon.ts
// ---------------------------------------------------------------------------
const pokemonPath = join(root, "app", "lib", "data", "pokemon.ts");
let src = readFileSync(pokemonPath, "utf-8");

// ---------------------------------------------------------------------------
// Replacement strategy
//
// The file has these slug-string patterns in pokemon data:
//
//  1. "categories": [...]       -> category slugs
//  2. "specialties": [...]      -> specialty slugs
//  3. "locations": [...]        -> location slugs (inside habitatList)
//  4. "primaryLocation": "..."  -> location slug
//  5. "habitatSlug": "..."
//       - top-level (4-space indent): PokemonHabitat
//       - inside habitatList (6-space indent): HabitatConfig
//
// ---------------------------------------------------------------------------

let replacementCount = 0;

// Replace all quoted slug values inside a named array field.
function replaceInArrayField(
  text: string,
  fieldName: string,
  map: Map<string, string>
): string {
  const startPattern = new RegExp(`"${fieldName}":\\s*\\[`, "g");
  let result = "";
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = startPattern.exec(text)) !== null) {
    const startIdx = match.index + match[0].length;
    // Find the matching closing bracket
    let depth = 1;
    let i = startIdx;
    while (i < text.length && depth > 0) {
      if (text[i] === "[") depth++;
      else if (text[i] === "]") depth--;
      i++;
    }
    const beforeAndStart = text.slice(lastIndex, match.index + match[0].length);
    let arrayContent = text.slice(startIdx, i - 1);
    const closingBracket = text[i - 1];

    for (const [slug, ref] of map) {
      const escaped = slug.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const re = new RegExp(`"${escaped}"`, "g");
      const prevLen = arrayContent.length;
      const newContent = arrayContent.replace(re, ref);
      if (newContent !== arrayContent) {
        const delta = Math.floor(
          (newContent.length - prevLen) / (ref.length - slug.length - 2)
        );
        replacementCount += Math.max(1, delta);
      }
      arrayContent = newContent;
    }

    result += beforeAndStart + arrayContent + closingBracket;
    lastIndex = i;
  }

  result += text.slice(lastIndex);
  return result;
}

// Apply array-field replacements
src = replaceInArrayField(src, "categories", categoryMap);
src = replaceInArrayField(src, "specialties", specialtyMap);
src = replaceInArrayField(src, "locations", locationMap);
src = replaceInArrayField(src, "weather", weatherMap);
src = replaceInArrayField(src, "time", timeMap);

// Replace "primaryLocation": "slug" (single-value field)
src = src.replace(/"primaryLocation":\s*"([^"]+)"/g, (match, slug) => {
  const ref = locationMap.get(slug);
  if (ref) { replacementCount++; return `"primaryLocation": ${ref}`; }
  return match;
});

// Replace "rarity": "value" (single-value field)
src = src.replace(/"rarity":\s*"([^"]+)"/g, (match, val) => {
  const ref = rarityMap.get(val);
  if (ref) { replacementCount++; return `"rarity": ${ref}`; }
  return match;
});

// Replace "flavor": "value" (single-value field)
src = src.replace(/"flavor":\s*"([^"]+)"/g, (match, val) => {
  const ref = flavorMap.get(val);
  if (ref) { replacementCount++; return `"flavor": ${ref}`; }
  return match;
});

// Replace "habitatSlug": "slug"
// Top-level pokemon field: 4-space indent -> PokemonHabitat
// Inside habitatList object: 6-space indent -> HabitatConfig
src = src.replace(
  /([ \t]*)"habitatSlug":\s*"([^"]+)"/g,
  (match, indent, slug) => {
    const indentLen = indent.replace(/\t/g, "  ").length;
    if (indentLen <= 4) {
      const ref = pokemonHabitatMap.get(slug);
      if (ref) {
        replacementCount++;
        return `${indent}"habitatSlug": ${ref}`;
      }
    } else {
      const ref = habitatConfigMap.get(slug);
      if (ref) {
        replacementCount++;
        return `${indent}"habitatSlug": ${ref}`;
      }
    }
    return match;
  }
);

// Add the import statement after existing import lines
const newImport = `import { Category, HabitatConfig, Location, Specialty, PokemonHabitat, Weather, Time, Rarity, Flavor } from "./consts";`;
src = src.replace(
  /^(import type \{ PokemonEntry \} from "\.\.\/types";)/m,
  `$1\n${newImport}`
);

// Write result
writeFileSync(pokemonPath, src, "utf-8");
console.log(`Rewrote ${pokemonPath}`);
console.log(`Total replacements: ${replacementCount}`);
